import type { SpineCapability } from "../contracts.ts";

export const BUSINESS_MISSION_CREATE = {
  key:"business_mission.create",domain:"business_mission",owner:"business-mission-system",humanSurface:"/solo/:account/command-center/business-game-plan",
  action:{classification:"mutate",executor:"public.create_business_mission",chatTool:"mission_create",riskPolicyKey:"high",approvalAuthority:"chat-canonical",idempotency:"Owner and tenant scoped request UUID plus canonical payload hash; mismatched replay fails closed."},
  outcome:{kinds:["proposed","refused","failed"],projector:"public.get_business_mission",railVisibility:"PARTIAL: paige-ai-chat re-reads and verifies the canonical Mission before recording mission_create through the existing capability_run Rail writer; authenticated runtime proof remains owed."},
  chatBinding:"LIVE",mindBinding:"UNAVAILABLE",sharedPrimitiveChange:"NONE",maturity:"PARTIAL",
} as const satisfies SpineCapability;
export const BUSINESS_MISSION_REVISE = {
  key:"business_mission.revise",domain:"business_mission",owner:"business-mission-system",humanSurface:"/solo/:account/command-center/business-game-plan",
  action:{classification:"mutate",executor:"public.revise_business_mission_brief",chatTool:"mission_revise",riskPolicyKey:"high",approvalAuthority:"chat-canonical",idempotency:"Mission scoped request UUID, immutable brief version, payload hash, and expected revision compare-and-swap."},
  outcome:{kinds:["revised","refused","failed"],projector:"public.get_business_mission",railVisibility:"PARTIAL: paige-ai-chat re-reads and verifies the canonical Mission before recording mission_revise through the existing capability_run Rail writer; authenticated runtime proof remains owed."},
  chatBinding:"LIVE",mindBinding:"UNAVAILABLE",sharedPrimitiveChange:"NONE",maturity:"PARTIAL",
} as const satisfies SpineCapability;
export const BUSINESS_MISSION_TRANSITION = {
  key:"business_mission.transition",domain:"business_mission",owner:"business-mission-system",humanSurface:"/solo/:account/command-center/business-game-plan",
  action:{classification:"mutate",executor:"public.transition_business_mission",chatTool:"mission_transition",riskPolicyKey:"high",approvalAuthority:"chat-canonical",idempotency:"Mission scoped request UUID, payload hash, and expected revision compare-and-swap; retry replays the committed state."},
  outcome:{kinds:["active","blocked","paused","completed","stopped","refused","failed"],projector:"public.get_business_mission",railVisibility:"PARTIAL: paige-ai-chat re-reads and verifies the canonical Mission before recording mission_transition through the existing capability_run Rail writer; authenticated runtime proof remains owed."},
  chatBinding:"LIVE",mindBinding:"UNAVAILABLE",sharedPrimitiveChange:"NONE",maturity:"PARTIAL",
} as const satisfies SpineCapability;
export const BUSINESS_MISSION_CAPABILITIES=[BUSINESS_MISSION_CREATE,BUSINESS_MISSION_REVISE,BUSINESS_MISSION_TRANSITION] as const;

export const BUSINESS_MISSION_TOOLS = [
  {type:"function",function:{name:"mission_create",description:"Propose a private Business Mission from an owner outcome. Ask only for material missing details. Creates a PROPOSED brief only; it runs no business work, contacts nobody, and publishes nothing. After approval, Paige verifies the canonical Mission readback before recording the saved outcome on Rail. Requires the rendered approval card.",parameters:{type:"object",properties:{title:{type:"string",minLength:3,maxLength:180},desired_outcome:{type:"string",minLength:3,maxLength:2000},deadline_on:{type:"string",description:"ISO date, or omit when unknown."},baseline:{type:"string",minLength:1,maxLength:4000},strategy:{type:"string",minLength:1,maxLength:6000},constraints:{type:"array",maxItems:30,items:{type:"string",minLength:1,maxLength:600}},success_definition:{type:"string",minLength:1,maxLength:3000},owner_authority:{type:"string",minLength:1,maxLength:3000,description:"Documentary boundary only; never grants autonomy."},assumptions:{type:"array",maxItems:30,items:{type:"string",minLength:1,maxLength:600}},missing_information:{type:"array",maxItems:30,items:{type:"string",minLength:1,maxLength:600}},next_action:{type:"string",maxLength:1200}},required:["title","desired_outcome","baseline","strategy","success_definition","owner_authority"]}}},
  {type:"function",function:{name:"mission_revise",description:"Propose an immutable revision to an existing private Mission brief from a server-resolved canonical Mission read. Runs no business work. After approval, Paige verifies every requested persisted field before recording the saved outcome on Rail. Requires the rendered approval card.",parameters:{type:"object",properties:{mission_id:{type:"string",format:"uuid"},expected_revision:{type:"integer",minimum:1},title:{type:"string",minLength:3,maxLength:180},desired_outcome:{type:"string",minLength:3,maxLength:2000},deadline_on:{type:"string"},baseline:{type:"string",minLength:1,maxLength:4000},strategy:{type:"string",minLength:1,maxLength:6000},constraints:{type:"array",maxItems:30,items:{type:"string",minLength:1,maxLength:600}},success_definition:{type:"string",minLength:1,maxLength:3000},owner_authority:{type:"string",minLength:1,maxLength:3000},assumptions:{type:"array",maxItems:30,items:{type:"string",minLength:1,maxLength:600}},missing_information:{type:"array",maxItems:30,items:{type:"string",minLength:1,maxLength:600}},next_action:{type:"string",maxLength:1200},revision_reason:{type:"string",minLength:1,maxLength:1200}},required:["mission_id","expected_revision","desired_outcome","baseline","strategy","success_definition","owner_authority","revision_reason"]}}},
  {type:"function",function:{name:"mission_transition",description:"Propose changing a private Mission lifecycle state from a server-resolved canonical Mission read. Runs no business work. Completion or stopping requires an honest owner outcome summary. After approval, Paige verifies the persisted lifecycle change before recording the saved outcome on Rail. Requires the rendered approval card.",parameters:{type:"object",properties:{mission_id:{type:"string",format:"uuid"},expected_revision:{type:"integer",minimum:1},to_state:{type:"string",enum:["active","blocked","paused","completed","stopped"]},reason:{type:"string",maxLength:1200},closure_outcome:{type:"string",enum:["achieved","partly_achieved","blocked","stopped"]},outcome_summary:{type:"string",maxLength:4000},outcome_unknowns:{type:"string",maxLength:4000}},required:["mission_id","expected_revision","to_state"]}}},
] as const;
