-- @generated by scripts/ci/crm-patch-field-gen.mjs — DO NOT EDIT BY HAND.
--
-- The patch field list Paige is shown must equal the allowlist that refuses her patch.
-- On 2026-09-25 it did not: she sent `company_name` and `zip`, the executor accepts
-- `entity_name` and `zip_code`, and an approved contact create died as
-- CRM_PATCH_FIELDS_INVALID:company_name,zip. The names below are GENERATED from the
-- allowlists, and this proof reads them back out of a real database via
-- pg_get_functiondef() — so Postgres, not a regex over migration files, is the authority
-- on which definition is live.
--
-- Regenerate:  node scripts/ci/crm-patch-field-gen.mjs --write

BEGIN;
SELECT plan(10);

-- COMPLETENESS. Exactly these functions can refuse a patch field; a new one is drift.
SELECT is(
  (SELECT count(*)::int FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.prokind = 'f'
      AND pg_get_functiondef(p.oid) LIKE '%CRM_PATCH_FIELDS_INVALID%'),
  2,
  'only the known functions can refuse a CRM patch field'
);

-- A new allowlist inside a known function is drift too, even if the others still match.
SELECT is(
  (SELECT count(*)::int FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    CROSS JOIN LATERAL regexp_matches(pg_get_functiondef(p.oid), 'k not in \(([^)]*)\)', 'g') AS m
    WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname = 'execute_crm_command_reversible'),
  6,
  'public.execute_crm_command_reversible carries exactly 6 patch allowlist(s)'
);

-- A new allowlist inside a known function is drift too, even if the others still match.
SELECT is(
  (SELECT count(*)::int FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    CROSS JOIN LATERAL regexp_matches(pg_get_functiondef(p.oid), 'k not in \(([^)]*)\)', 'g') AS m
    WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname = 'preview_crm_command'),
  1,
  'public.preview_crm_command carries exactly 1 patch allowlist(s)'
);

-- contact.create — allowlist 1 of public.execute_crm_command_reversible
SELECT is(
  (SELECT (SELECT array_agg(g[1] ORDER BY o)
             FROM regexp_matches(s.site, '''([^'']+)''', 'g') WITH ORDINALITY AS x(g, o))
     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     CROSS JOIN LATERAL (
       SELECT arr[1] AS site, ord FROM regexp_matches(
         pg_get_functiondef(p.oid), 'k not in \(([^)]*)\)', 'g') WITH ORDINALITY AS t(arr, ord)
     ) s
     WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname = 'execute_crm_command_reversible' AND s.ord = 1),
  ARRAY['first_name', 'last_name', 'email', 'phone', 'entity_name', 'entity_type', 'title', 'lifecycle_stage', 'source', 'tags', 'primary_offer', 'notes', 'do_not_contact', 'website', 'linkedin_url', 'street_address', 'city', 'state', 'zip_code', 'funding_goal', 'monthly_revenue']::text[],
  'contact.create patch fields match the schema Paige is shown'
);

-- contact.update — allowlist 2 of public.execute_crm_command_reversible
SELECT is(
  (SELECT (SELECT array_agg(g[1] ORDER BY o)
             FROM regexp_matches(s.site, '''([^'']+)''', 'g') WITH ORDINALITY AS x(g, o))
     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     CROSS JOIN LATERAL (
       SELECT arr[1] AS site, ord FROM regexp_matches(
         pg_get_functiondef(p.oid), 'k not in \(([^)]*)\)', 'g') WITH ORDINALITY AS t(arr, ord)
     ) s
     WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname = 'execute_crm_command_reversible' AND s.ord = 2),
  ARRAY['first_name', 'last_name', 'email', 'phone', 'entity_name', 'entity_type', 'title', 'lifecycle_stage', 'source', 'tags', 'primary_offer', 'current_notes', 'do_not_contact', 'website', 'linkedin_url', 'street_address', 'city', 'state', 'zip_code', 'funding_goal', 'monthly_revenue']::text[],
  'contact.update patch fields match the schema Paige is shown'
);

-- task.create — allowlist 3 of public.execute_crm_command_reversible
SELECT is(
  (SELECT (SELECT array_agg(g[1] ORDER BY o)
             FROM regexp_matches(s.site, '''([^'']+)''', 'g') WITH ORDINALITY AS x(g, o))
     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     CROSS JOIN LATERAL (
       SELECT arr[1] AS site, ord FROM regexp_matches(
         pg_get_functiondef(p.oid), 'k not in \(([^)]*)\)', 'g') WITH ORDINALITY AS t(arr, ord)
     ) s
     WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname = 'execute_crm_command_reversible' AND s.ord = 3),
  ARRAY['title', 'description', 'assignee_user_id', 'contact_id', 'company_id', 'deal_id', 'due_date', 'track', 'metadata']::text[],
  'task.create patch fields match the schema Paige is shown'
);

-- task.update — allowlist 4 of public.execute_crm_command_reversible
SELECT is(
  (SELECT (SELECT array_agg(g[1] ORDER BY o)
             FROM regexp_matches(s.site, '''([^'']+)''', 'g') WITH ORDINALITY AS x(g, o))
     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     CROSS JOIN LATERAL (
       SELECT arr[1] AS site, ord FROM regexp_matches(
         pg_get_functiondef(p.oid), 'k not in \(([^)]*)\)', 'g') WITH ORDINALITY AS t(arr, ord)
     ) s
     WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname = 'execute_crm_command_reversible' AND s.ord = 4),
  ARRAY['title', 'description', 'track', 'metadata']::text[],
  'task.update patch fields match the schema Paige is shown'
);

-- company.create — allowlist 5 of public.execute_crm_command_reversible
SELECT is(
  (SELECT (SELECT array_agg(g[1] ORDER BY o)
             FROM regexp_matches(s.site, '''([^'']+)''', 'g') WITH ORDINALITY AS x(g, o))
     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     CROSS JOIN LATERAL (
       SELECT arr[1] AS site, ord FROM regexp_matches(
         pg_get_functiondef(p.oid), 'k not in \(([^)]*)\)', 'g') WITH ORDINALITY AS t(arr, ord)
     ) s
     WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname = 'execute_crm_command_reversible' AND s.ord = 5),
  ARRAY['legal_name', 'entity_type', 'dba', 'website', 'business_email', 'business_phone', 'naics', 'revenue_band', 'state_of_formation']::text[],
  'company.create patch fields match the schema Paige is shown'
);

-- company.update — allowlist 6 of public.execute_crm_command_reversible
SELECT is(
  (SELECT (SELECT array_agg(g[1] ORDER BY o)
             FROM regexp_matches(s.site, '''([^'']+)''', 'g') WITH ORDINALITY AS x(g, o))
     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     CROSS JOIN LATERAL (
       SELECT arr[1] AS site, ord FROM regexp_matches(
         pg_get_functiondef(p.oid), 'k not in \(([^)]*)\)', 'g') WITH ORDINALITY AS t(arr, ord)
     ) s
     WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname = 'execute_crm_command_reversible' AND s.ord = 6),
  ARRAY['legal_name', 'entity_type', 'dba', 'website', 'business_email', 'business_phone', 'naics', 'revenue_band', 'state_of_formation']::text[],
  'company.update patch fields match the schema Paige is shown'
);

-- contact.bulk_update — allowlist 1 of public.preview_crm_command
SELECT is(
  (SELECT (SELECT array_agg(g[1] ORDER BY o)
             FROM regexp_matches(s.site, '''([^'']+)''', 'g') WITH ORDINALITY AS x(g, o))
     FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     CROSS JOIN LATERAL (
       SELECT arr[1] AS site, ord FROM regexp_matches(
         pg_get_functiondef(p.oid), 'k not in \(([^)]*)\)', 'g') WITH ORDINALITY AS t(arr, ord)
     ) s
     WHERE n.nspname = 'public' AND p.prokind = 'f' AND p.proname = 'preview_crm_command' AND s.ord = 1),
  ARRAY['lifecycle_stage', 'tags', 'do_not_contact', 'assigned_coach_user_id']::text[],
  'contact.bulk_update patch fields match the schema Paige is shown'
);

SELECT * FROM finish();
ROLLBACK;
