// @ts-nocheck
import React from "react";

export const CLAY={
meet:['Meetings','var(--violet)','Client calls, consults and signings'],
dead:['Compliance deadlines','var(--bad)','Obligations pulled from Trust Compass'],
run:['Automation runs','var(--gold)','Scheduled firings from Automations'],
mile:['Onboarding milestones','#2E7D8F','Client Success checkpoints'],
avail:['Availability blocks','#3F7A4B','Protected time, half days, out of office'],
fu:['Paige follow-ups','#8A5A9E','Nudges she thinks you should make']};
export const CPRIM=['meet','dead'];
export const CAL={
today:16,todayDow:0,month:'August',mAbbr:'Aug',year:2026,first:6,days:31,prev:31,label:'August 2026',
strip:[['Meetings this week','9','Four consults, three reviews, two signings'],
 ['Deadlines in 14 days','5','Two inside a booked day'],
 ['Conflicts','2','Aug 10 and Aug 18'],
 ['Booked capacity','68%','Of the hours you opened']],
ev:[
{id:'e1',d:3,k:'run',m:390,t:'6:30am',n:'Monday brief',sub:'Monday brief · Weekly owner digest',src:'Automations',note:'Assembled from eleven sources. You opened it at 6:38am.'},
{id:'e2',d:3,k:'meet',m:600,t:'10:00am',n:'Onboarding call · Cairn Advisory',sub:'45 min · Google Meet',dur:'45 min',src:'Client onboarding call',note:'Booked through your link on Jul 30. Two intake answers attached.'},
{id:'e3',d:4,k:'meet',m:780,t:'1:00pm',n:'Quarterly review · Ridgeline Co.',sub:'60 min · Zoom',dur:'60 min',src:'Quarterly compliance review',note:'Third quarterly with Ridgeline. Last one ran nine minutes over.'},
{id:'e4',d:4,k:'fu',m:900,t:'3:00pm',n:'Follow up · Vance Group proposal',sub:'Open 6 days, no reply',src:'Paige',note:'Proposal chase is drafted but not live, so she is putting this on you by hand.'},
{id:'e5',d:5,k:'dead',m:-1,t:'All day',n:'Form 5500 · Bellweather Trust',sub:'Statutory filing',src:'Trust Compass',note:'Filed Aug 4, one day early. Confirmation is in the vault.'},
{id:'e6',d:5,k:'meet',m:555,t:'9:15am',n:'Free consult · inbound lead',sub:'15 min · Phone',dur:'15 min',src:'Free consult',note:'Came from the pricing page. Became Harlow & Reed.'},
{id:'e7',d:6,k:'avail',m:480,t:'8:00–11:00am',n:'Protected block · deep work',sub:'No bookings accepted',src:'Client hours',note:'Held every Thursday morning. Nothing has broken it since June.'},
{id:'e8',d:6,k:'meet',m:900,t:'3:00pm',n:'Doc signing · Mercer Studio',sub:'30 min · In person',dur:'30 min',src:'Document signing session',note:'Two signatures, both captured.'},
{id:'e9',d:7,k:'mile',m:540,t:'9:00am',n:'Cairn Advisory · kickoff week complete',sub:'Onboarding step 3 of 5',src:'Client Success',note:'Four checklist items closed on time, one left with you.'},
{id:'e10',d:10,k:'run',m:390,t:'6:30am',n:'Monday brief',sub:'Monday brief · Weekly owner digest',src:'Automations',note:'Clean run. 28.4 seconds.'},
{id:'e11',d:10,k:'meet',m:660,t:'11:00am',n:'Trust setup deep-dive · Linley Coaching',sub:'90 min · Zoom',dur:'90 min',src:'Trust setup deep-dive',note:'Ran the full structure walkthrough. Two follow-ups opened.'},
{id:'e12',d:10,k:'dead',m:-1,t:'All day',n:'Annual report · Vance Group',sub:'State filing, hard date',src:'Trust Compass',note:'Landed on the same day as a 90-minute deep-dive. She wanted you to see it before it got tight.'},
{id:'e13',d:11,k:'fu',m:840,t:'2:00pm',n:'Quiet-client nudge · Mercer Studio',sub:'Eleven days silent',src:'Paige',note:'No inbound mail, no answered call, no portal login.'},
{id:'e14',d:12,k:'meet',m:540,t:'9:00am',n:'Free consult · inbound lead',sub:'15 min · Phone',dur:'15 min',src:'Free consult',note:'No-show. She sent the reschedule link automatically.'},
{id:'e15',d:12,k:'meet',m:840,t:'2:00pm',n:'Onboarding call · Harlow & Reed',sub:'45 min · Google Meet',dur:'45 min',src:'Client onboarding call',note:'Signed the same afternoon.'},
{id:'e16',d:13,k:'dead',m:-1,t:'All day',n:'Quarterly estimate · Ridgeline Co.',sub:'Tax obligation',src:'Trust Compass',note:'Paid Aug 13. Receipt in the vault.'},
{id:'e17',d:13,k:'run',m:420,t:'7:00am',n:'Token expiry watch · failed',sub:'Sync repair · Token expiry watch',src:'Automations',note:'Condition referenced a webhook removed with the old HubSpot app.'},
{id:'e18',d:14,k:'mile',m:540,t:'9:00am',n:'Harlow & Reed · vault complete',sub:'Onboarding step 2 of 5',src:'Client Success',note:'All six formation documents in.'},
{id:'e19',d:14,k:'avail',m:780,t:'1:00pm–end',n:'Half day',sub:'Bookings closed after 1pm',src:'Date override',note:'You set this on Aug 2.'},
{id:'e20',d:17,k:'run',m:390,t:'6:30am',n:'Monday brief',sub:'Monday brief · Weekly owner digest',src:'Automations',note:'Will fire in the morning. Nothing to do.'},
{id:'e21',d:17,k:'meet',m:600,t:'10:00am',n:'Quarterly review · Bellweather Trust',sub:'60 min · Zoom',dur:'60 min',src:'Quarterly compliance review',note:'Booked three weeks out. Intake answers already in.'},
{id:'e22',d:17,k:'meet',m:990,t:'4:30pm',n:'Free consult · inbound lead',sub:'15 min · Phone',dur:'15 min',src:'Free consult',note:'Booked Friday night through the public link.'},
{id:'e23',d:18,k:'meet',m:570,t:'9:30am',n:'Trust setup deep-dive · Ridgeline Co.',sub:'90 min · Zoom',dur:'90 min',src:'Trust setup deep-dive',note:'Runs until 11am, which is the morning this filing needs.'},
{id:'e24',d:18,k:'dead',m:-1,t:'All day',n:'Beneficial ownership update · Cairn Advisory',sub:'Federal filing, hard date',src:'Trust Compass',note:'This is the conflict she would move first. The deep-dive has slack, the filing does not.'},
{id:'e25',d:18,k:'fu',m:960,t:'4:00pm',n:'Follow up · Linley renewal',sub:'45 days from term end',src:'Paige',note:'Retainer renewal automation has not fired since April.'},
{id:'e26',d:19,k:'meet',m:660,t:'11:00am',n:'Doc signing · Vance Group',sub:'30 min · In person',dur:'30 min',src:'Document signing session',note:'Annual report package, three signatures.'},
{id:'e27',d:19,k:'run',m:420,t:'7:00am',n:'Competitor price scan',sub:'Competitor watch · Daily price scan',src:'Automations',note:'Firing per competitor instead of per scan.'},
{id:'e28',d:20,k:'avail',m:480,t:'8:00–11:00am',n:'Protected block · deep work',sub:'No bookings accepted',src:'Client hours',note:'Standing Thursday hold.'},
{id:'e29',d:20,k:'meet',m:810,t:'1:30pm',n:'Onboarding call · new signee',sub:'45 min · Google Meet',dur:'45 min',src:'Client onboarding call',note:'Placeholder from the onboarding automation. Client picks the slot.'},
{id:'e30',d:20,k:'mile',m:540,t:'9:00am',n:'Linley Coaching · quarter-one review due',sub:'Onboarding step 5 of 5',src:'Client Success',note:'Last step. Closing it graduates them out of onboarding.'},
{id:'e31',d:21,k:'dead',m:-1,t:'All day',n:'Sales tax filing · your own books',sub:'Monthly obligation',src:'Trust Compass',note:'Recurring. She files the numbers, you confirm.'},
{id:'e32',d:24,k:'run',m:390,t:'6:30am',n:'Monday brief',sub:'Monday brief · Weekly owner digest',src:'Automations',note:'Scheduled.'},
{id:'e33',d:24,k:'meet',m:540,t:'9:00am',n:'Free consult · open slot booked',sub:'15 min · Phone',dur:'15 min',src:'Free consult',note:'Booked Aug 14.'},
{id:'e34',d:25,k:'meet',m:840,t:'2:00pm',n:'Quarterly review · Mercer Studio',sub:'60 min · Zoom',dur:'60 min',src:'Quarterly compliance review',note:'The quiet account. This is the call that fixes it.'},
{id:'e35',d:26,k:'dead',m:-1,t:'All day',n:'Annual minutes · Bellweather Trust',sub:'Corporate record',src:'Trust Compass',note:'Draft is written, waiting on your read.'},
{id:'e36',d:27,k:'meet',m:600,t:'10:00am',n:'Trust setup deep-dive · prospect',sub:'90 min · Zoom',dur:'90 min',src:'Trust setup deep-dive',note:'Paid hold. Card captured at booking.'},
{id:'e37',d:27,k:'fu',m:960,t:'4:00pm',n:'Follow up · consult that went quiet',sub:'Aug 12 no-show',src:'Paige',note:'Second attempt. She will draft it if you want.'},
{id:'e38',d:28,k:'mile',m:540,t:'9:00am',n:'Ridgeline Co. · year-one review',sub:'Retention checkpoint',src:'Client Success',note:'A year on Aug 28. Worth a note from you, not from her.'},
{id:'e39',d:31,k:'run',m:390,t:'6:30am',n:'Monday brief',sub:'Monday brief · Weekly owner digest',src:'Automations',note:'Scheduled.'},
{id:'e40',d:31,k:'dead',m:-1,t:'All day',n:'Month-end close',sub:'Finance obligation',src:'Trust Compass',note:'She closes it, you sign off.'}],
next:[['Mon Aug 17','6:30am','Monday brief fires','run'],['Mon Aug 17','10:00am','Quarterly review · Bellweather Trust','meet'],
 ['Mon Aug 17','4:30pm','Free consult · inbound lead','meet'],['Tue Aug 18','9:30am','Trust setup deep-dive · Ridgeline','meet'],
 ['Tue Aug 18','All day','Beneficial ownership update · Cairn','dead']],
read:'Two days this month have a hard filing sitting under a long call — Aug 10 and Aug 18. The deep-dive on the eighteenth is the one with slack in it; the filing is not movable. Everything else on your grid is either booked through a link or fired by a rule, which is how it should read.'};
export const CBK={
types:[
 {n:'Free consult',dur:'15 min',sched:'Consult only',active:true,bk30:14,slug:'jordan/consult',loc:'Phone',buf:'5 min after',notice:'4 hours',cap:'4 a day',price:'Free',
  d:'Fifteen minutes to hear what you are trying to build and tell you whether we are the right fit.',
  q:['What are you trying to set up?','How did you hear about us?'],
  cf:'You are on for {time}. I will call the number you gave me. If anything changes, the link in this email moves it.'},
 {n:'Client onboarding call',dur:'45 min',sched:'Client hours',active:true,bk30:5,slug:'jordan/onboarding',loc:'Google Meet',buf:'15 min after',notice:'1 day',cap:'2 a day',price:'Included',
  d:'The working session where we set up your entities, your calendar and the automations that run behind them.',
  q:['Which entities are we covering?','Anything already filed this year?','Who else should be on the call?'],
  cf:'Booked for {time}. The kickoff kit is already in your inbox — bring anything on the checklist that is still open.'},
 {n:'Quarterly compliance review',dur:'60 min',sched:'Client hours',active:true,bk30:3,slug:'jordan/quarterly',loc:'Zoom',buf:'15 min after',notice:'2 days',cap:'2 a day',price:'Included',
  d:'A full pass over filings, deadlines and anything Paige flagged since we last spoke.',
  q:['Anything you want covered first?'],
  cf:'See you {time}. Your compliance summary will be attached twenty-four hours before we talk.'},
 {n:'Document signing session',dur:'30 min',sched:'Client hours',active:true,bk30:6,slug:'jordan/signing',loc:'In person or Zoom',buf:'10 min after',notice:'1 day',cap:'3 a day',price:'Included',
  d:'Sit down and sign. Everything is prepared before you arrive.',
  q:['Which documents are we signing?','In person or remote?'],
  cf:'Confirmed for {time}. The signing packet is in your portal — nothing to print.'},
 {n:'Trust setup deep-dive',dur:'90 min',sched:'Deep-dive windows',active:true,bk30:2,slug:'jordan/deep-dive',loc:'Zoom',buf:'30 min after',notice:'3 days',cap:'1 a day',price:'$450',
  d:'Ninety minutes on structure. We map the trust, the entities and who controls what, and you leave with the diagram.',
  q:['What structure do you have today?','What are you protecting against?','Who are the beneficiaries?'],
  cf:'Held for {time}. Your card is authorised, not charged — it settles after we talk.'},
 {n:'Ad-hoc · request a time',dur:'Flexible',sched:'Client hours',active:false,bk30:0,slug:'jordan/ask',loc:'You pick',buf:'None',notice:'1 day',cap:'No cap',price:'Quoted',
  d:'For anything that does not fit the other five. Tell me what you need and how long you think it takes.',
  q:['What do you need?','How long do you think it takes?'],
  cf:'Got your request. I will confirm or propose a different time within a business day.'}],
sched:[
 {n:'Client hours',tz:'America/New_York',used:4,def:true,
  h:[['Mon','9:00am – 5:00pm'],['Tue','9:00am – 5:00pm'],['Wed','9:00am – 5:00pm'],['Thu','11:00am – 5:00pm'],['Fri','9:00am – 1:00pm'],['Sat','Unavailable'],['Sun','Unavailable']],
  ov:[['Aug 14','Closes at 1:00pm'],['Aug 31','Unavailable · month-end close'],['Sep 7','Unavailable · holiday']],
  note:'Thursday starts at eleven because the protected block runs 8 to 11. Friday afternoon is closed on purpose.'},
 {n:'Deep-dive windows',tz:'America/New_York',used:1,def:false,
  h:[['Mon','Unavailable'],['Tue','9:00am – 12:00pm'],['Wed','Unavailable'],['Thu','11:00am – 2:00pm'],['Fri','Unavailable'],['Sat','Unavailable'],['Sun','Unavailable']],
  ov:[['Aug 25','Unavailable']],
  note:'Two windows a week, one booking each. Ninety minutes plus a thirty-minute buffer is a two-hour hole in a day.'},
 {n:'Consult only',tz:'America/New_York',used:1,def:false,
  h:[['Mon','3:00pm – 5:00pm'],['Tue','Unavailable'],['Wed','3:00pm – 5:00pm'],['Thu','Unavailable'],['Fri','3:00pm – 5:00pm'],['Sat','Unavailable'],['Sun','Unavailable']],
  ov:[],
  note:'Late afternoon on three days. Fifteen-minute calls are cheap to take when the real work is done.'}],
req:[
 {who:'Delia Marsh',co:'Marsh & Co.',type:'Trust setup deep-dive',want:'Tue Aug 18 · 9:00am',st:'Needs a decision',
  why:'Falls inside a deep-dive window, but it collides with the Ridgeline session already held at 9:30.',ans:[['What structure do you have today?','Two LLCs, no trust yet.'],['What are you protecting against?','A partner buyout.'],['Who are the beneficiaries?','My two children.']],paid:'Card authorised · $450'},
 {who:'Owen Castellan',co:'Castellan Group',type:'Free consult',want:'Wed Aug 19 · 3:15pm',st:'Needs a decision',
  why:'Clean slot, inside Consult only. Nothing in the way.',ans:[['What are you trying to set up?','A holding company for three rentals.'],['How did you hear about us?','Referred by Ridgeline.']],paid:'Free'},
 {who:'Priya Raman',co:'Harlow & Reed',type:'Quarterly compliance review',want:'Moved to Thu Aug 27 · 2:00pm',st:'Rescheduled',
  why:'She moved it herself through the link. Your grid already reflects it.',ans:[['Anything you want covered first?','The beneficial ownership filing.']],paid:'Included'},
 {who:'Nils Boquet',co:'Boquet Ventures',type:'Document signing session',want:'Was Fri Aug 14 · 10:00am',st:'Cancelled',
  why:'Cancelled ninety minutes before. The slot reopened automatically and was rebooked the same afternoon.',ans:[['Which documents are we signing?','Operating agreement.']],paid:'Included'}],
health:[
 {t:'Two hard filings sit under long calls',b:'Aug 10 and Aug 18 both have a ninety-minute session and a hard-date filing. The filings cannot move.',act:'Review both days',tone:'warn'},
 {t:'Ad-hoc link is off',b:'It is the only one of your six that is not live. Everything that does not fit the other five currently reaches you by email instead.',act:'Turn it on',tone:'warn'},
 {t:'Deep-dive windows are fully booked',b:'Both windows this week and next are taken. Two people asked for a third.',act:'Open a window',tone:'ok'},
 {t:'Consult no-show rate is 1 in 14',b:'One no-show in fourteen consults. She sends the reschedule link on her own, and eleven of fourteen rebooked.',act:'Leave it alone',tone:'ok'}],
pend:'Booking pages, availability schedules and the request queue are not built yet — no public endpoint, no slot solver, no calendar write scope. Fixture data below runs through the real interface.',
slots:{17:['9:00am','9:30am','10:30am','11:00am','1:00pm','2:00pm','3:00pm'],
 18:['12:00pm','1:00pm','2:00pm','3:30pm'],19:['9:00am','10:00am','3:00pm','3:15pm','4:00pm'],
 20:['11:00am','11:30am','2:00pm','3:00pm','4:30pm'],21:['9:00am','9:30am','10:00am','11:00am','12:00pm'],
 24:['9:30am','10:00am','1:00pm','2:30pm','3:00pm','4:00pm'],25:['9:00am','11:00am','1:30pm','3:00pm'],
 26:['9:00am','10:00am','10:30am','2:00pm','3:00pm','4:00pm'],27:['11:00am','1:00pm','2:00pm'],
 28:['9:00am','9:30am','10:00am','11:30am']}};
