// Guest self-serve: view / cancel / reschedule a booking via a signed link.
// No login — the link carries an HMAC token (signed with the service-role key)
// that resolves to exactly one booking. Availability for rescheduling is fetched
// by the client from the public-booking function, so slot logic lives in one
// place; here we only re-validate the chosen slot before writing.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const cors = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const json = (b: unknown, s = 200) => new Response(JSON.stringify(b), { status: s, headers: { ...cors, "Content-Type": "application/json" } });

const SECRET = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "";
const enc = new TextEncoder();

function b64urlFromBytes(bytes: Uint8Array): string {
  let bin = ""; for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, "");
}
function b64urlToStr(s: string): string {
  const pad = s.length % 4 === 0 ? "" : "=".repeat(4 - (s.length % 4));
  return atob(s.replace(/-/g, "+").replace(/_/g, "/") + pad);
}
async function hmac(data: string): Promise<string> {
  const key = await crypto.subtle.importKey("raw", enc.encode(SECRET), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  return b64urlFromBytes(new Uint8Array(await crypto.subtle.sign("HMAC", key, enc.encode(data))));
}
// Exported shape (also generated by public-booking / notifications):
//   token = base64url(JSON{b:bookingId}) + "." + base64url(HMAC)
async function verifyToken(token: string): Promise<string | null> {
  const [payload, sig] = (token || "").split(".");
  if (!payload || !sig) return null;
  if ((await hmac(payload)) !== sig) return null;
  try { const o = JSON.parse(b64urlToStr(payload)); return typeof o.b === "string" ? o.b : null; } catch { return null; }
}

// --- Minimal slot re-validation (mirrors public-booking) --------------------
interface DayWindow { day: number; start: string; end: string }
function offsetMin(atUtcMs: number, tz: string): number {
  const dtf = new Intl.DateTimeFormat("en-US", { timeZone: tz, hour12: false, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", second: "2-digit" });
  const p: Record<string, string> = {}; for (const part of dtf.formatToParts(new Date(atUtcMs))) p[part.type] = part.value;
  const asUtc = Date.UTC(+p.year, +p.month - 1, +p.day, +p.hour === 24 ? 0 : +p.hour, +p.minute, +p.second);
  return (asUtc - atUtcMs) / 60000;
}
function zonedWallToUtcMs(y: number, mo: number, d: number, h: number, mi: number, tz: string): number {
  const guess = Date.UTC(y, mo, d, h, mi); return guess - offsetMin(guess, tz) * 60000;
}
function ymdInTz(ms: number, tz: string): { y: number; mo: number; d: number; wd: number } {
  const dtf = new Intl.DateTimeFormat("en-US", { timeZone: tz, year: "numeric", month: "2-digit", day: "2-digit", weekday: "short" });
  const p: Record<string, string> = {}; for (const part of dtf.formatToParts(new Date(ms))) p[part.type] = part.value;
  return { y: +p.year, mo: +p.month, d: +p.day, wd: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].indexOf(p.weekday) };
}
function isWindowStart(avail: DayWindow[], tz: string, durMin: number, minNoticeMin: number, startMs: number, nowMs: number): boolean {
  if (startMs < nowMs + minNoticeMin * 60000) return false;
  const durMs = durMin * 60000;
  const { y, mo, d, wd } = ymdInTz(startMs, tz);
  for (const w of avail.filter((x) => x.day === wd)) {
    const [sh, sm] = w.start.split(":").map(Number); const [eh, em] = w.end.split(":").map(Number);
    const winStart = zonedWallToUtcMs(y, mo - 1, d, sh, sm, tz); const winEnd = zonedWallToUtcMs(y, mo - 1, d, eh, em, tz);
    for (let s = winStart; s + durMs <= winEnd; s += durMs) if (s === startMs) return true;
  }
  return false;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: cors });
  try {
    if (!SECRET) return json({ error: "server not configured" }, 500);
    const admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
    const body = await req.json().catch(() => ({}));
    const action = body?.action;
    const bookingId = await verifyToken(String(body?.token ?? ""));
    if (!bookingId) return json({ error: "This link is invalid or has expired." }, 401);

    const { data: b } = await admin.from("internal_bookings")
      .select("id, calendar_id, host_user_id, guest_name, guest_email, title, start_at, end_at, timezone, status, location_type, location_value, booking_kind, collective_group_id")
      .eq("id", bookingId).maybeSingle();
    if (!b) return json({ error: "Booking not found." }, 404);

    // Calendar backs slug/availability/branding for the manage view + reschedule.
    let slug: string | null = null, avail: DayWindow[] = [], durationMin = 30, minNotice = 60, cal: Record<string, unknown> | null = null;
    if (b.calendar_id) {
      const { data: c } = await admin.from("calendars")
        .select("slug, availability_json, duration_min, min_notice_min, title, accent")
        .eq("id", b.calendar_id).maybeSingle();
      if (c) {
        cal = c; slug = c.slug as string;
        avail = Array.isArray(c.availability_json) ? (c.availability_json as DayWindow[]) : [];
        durationMin = Math.max(5, (c.duration_min as number) ?? 30);
        minNotice = Math.max(0, (c.min_notice_min as number) ?? 60);
      }
    }

    if (action === "manage") {
      // Collective only: tell the guest who they're actually meeting with —
      // every row in the group is a symmetric leg for one attending host.
      let withNames: string | null = null;
      if (b.collective_group_id) {
        const { data: siblings } = await admin.from("internal_bookings")
          .select("host_user_id").eq("collective_group_id", b.collective_group_id).neq("status", "cancelled");
        const hostIds = Array.from(new Set((siblings ?? []).map((s) => s.host_user_id as string)));
        if (hostIds.length > 1) {
          const { data: profs } = await admin.from("profiles").select("user_id, full_name").in("user_id", hostIds);
          const nameByUid = new Map((profs ?? []).map((p) => [p.user_id as string, p.full_name as string | null]));
          const names = (await Promise.all(hostIds.map(async (uid) => {
            const { data: u } = await admin.auth.admin.getUserById(uid);
            return nameByUid.get(uid) || (u as { user?: { email?: string } } | null)?.user?.email || null;
          }))).filter((n): n is string => !!n);
          if (names.length) withNames = names.join(", ");
        }
      }
      return json({
        booking: {
          id: b.id, title: (cal?.title as string) || b.title, start_at: b.start_at, status: b.status,
          guest_name: b.guest_name, timezone: b.timezone, slug, accent: (cal?.accent as string) || "#EBB94C",
          durationMin, canModify: b.status === "scheduled",
          ...(withNames ? { with: withNames } : {}),
        },
      });
    }

    if (b.status !== "scheduled") return json({ error: "This booking can no longer be changed." }, 409);

    if (action === "cancel") {
      await admin.from("internal_bookings").update({ status: "cancelled" }).eq("id", b.id);
      return json({ ok: true, status: "cancelled" });
    }

    if (action === "reschedule") {
      const newStart = Date.parse(body?.start);
      if (!Number.isFinite(newStart)) return json({ error: "Pick a new time." }, 400);
      const now = Date.now();
      const tz = (b.timezone as string) || "America/New_York";
      if (!isWindowStart(avail, tz, durationMin, minNotice, newStart, now)) {
        return json({ error: "That time isn't open. Please pick another." }, 409);
      }
      const newEnd = newStart + durationMin * 60000;

      // Class: the host is SUPPOSED to be busy with other guests' seats at an
      // existing session, so the single-host "is free" check below is the
      // wrong tool entirely — this needs the same lock/find-or-create/count
      // shape create_class_booking uses, ending in a move instead of an insert.
      if (b.booking_kind === "class_seat") {
        const { data: seat, error } = await admin.rpc("reschedule_class_booking", {
          _seat_id: b.id,
          _new_start_at: new Date(newStart).toISOString(),
          _new_end_at: new Date(newEnd).toISOString(),
        });
        if (error) {
          if ((error as { message?: string }).message === "sold_out")
            return json({ error: "That class is full. Please pick another time." }, 409);
          const code = (error as { code?: string }).code;
          if (code === "23P01" || code === "23505")
            return json({ error: "That time was just taken. Please pick another." }, 409);
          return json({ error: error.message }, 500);
        }
        return json({ ok: true, status: "scheduled", start_at: (seat as { start_at: string }).start_at });
      }

      // Collective: every attending host must be free at the new time, and
      // every symmetric leg moves together — moving only the token's own row
      // would leave the group split across two different times.
      if (b.collective_group_id) {
        const { data: siblings } = await admin.from("internal_bookings")
          .select("id, host_user_id").eq("collective_group_id", b.collective_group_id).neq("status", "cancelled");
        const group = siblings?.length ? siblings : [{ id: b.id, host_user_id: b.host_user_id }];
        const groupIds = new Set(group.map((m) => m.id as string));
        for (const member of group) {
          const { data: clash } = await admin.from("internal_bookings")
            .select("id, start_at, end_at").eq("host_user_id", member.host_user_id).neq("status", "cancelled")
            .gte("start_at", new Date(newStart - 86_400_000).toISOString()).lte("start_at", new Date(newStart + 86_400_000).toISOString());
          const busy = (clash ?? []).some((x) => !groupIds.has(x.id as string) && newStart < Date.parse(x.end_at) && newEnd > Date.parse(x.start_at));
          if (busy) return json({ error: "That time was just taken. Please pick another." }, 409);
        }
        const { error } = await admin.from("internal_bookings")
          .update({ start_at: new Date(newStart).toISOString(), end_at: new Date(newEnd).toISOString() })
          .eq("collective_group_id", b.collective_group_id).neq("status", "cancelled");
        if (error) {
          const code = (error as { code?: string }).code;
          if (code === "23505" || code === "23P01") return json({ error: "That time was just taken. Please pick another." }, 409);
          return json({ error: error.message }, 500);
        }
        return json({ ok: true, status: "scheduled", start_at: new Date(newStart).toISOString() });
      }

      // Single / round-robin — unchanged, except 23P01 (the GiST exclusion
      // constraint, e.g. a mixed-duration overlap) now maps to the same clean
      // 409 23505 (exact-start clash) already got; previously it fell through
      // to a raw 500.
      const { data: clash } = await admin.from("internal_bookings")
        .select("id, start_at, end_at").eq("host_user_id", b.host_user_id).neq("status", "cancelled").neq("id", b.id)
        .gte("start_at", new Date(newStart - 86_400_000).toISOString()).lte("start_at", new Date(newStart + 86_400_000).toISOString());
      const busy = (clash ?? []).some((x) => newStart < Date.parse(x.end_at) && newEnd > Date.parse(x.start_at));
      if (busy) return json({ error: "That time was just taken. Please pick another." }, 409);

      const { error } = await admin.from("internal_bookings")
        .update({ start_at: new Date(newStart).toISOString(), end_at: new Date(newEnd).toISOString() })
        .eq("id", b.id);
      if (error) {
        const code = (error as { code?: string }).code;
        if (code === "23505" || code === "23P01") return json({ error: "That time was just taken. Please pick another." }, 409);
        return json({ error: error.message }, 500);
      }
      return json({ ok: true, status: "scheduled", start_at: new Date(newStart).toISOString() });
    }

    return json({ error: "Unknown action" }, 400);
  } catch (e) {
    return json({ error: (e as Error).message }, 500);
  }
});
