// Image mode — the absorbed Content Studio image generator, re-laid as a Studio workspace.
//
// Rail: the prompt + shape with an indigo "Generate image" pinned at the bottom.
// Canvas: the result (or the honest needs_config gate, preserved verbatim). There is NO
// gold in this mode — the act is the server auto-filing the image into the library, and
// the success StatePill reports that it happened (§13: report what actually happened).
//
// Backend unchanged (§10): the exact `generate-image` invoke, including the needs_config
// branch, lifted from the old ImagePanel.
import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { SectionCard, EmptyState, Toolbar, StatePill } from "@/components/ui/page";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { Download, Info, Loader2, Send, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { StudioRailHeading, StudioSplit } from "../StudioChrome";
import { MODE_EMPTY, MODE_RAIL } from "../studio-copy";
import { growthSeamMessage } from "@/lib/growth-templates";

export interface ImageModeProps {
  tenantId: string | null;
  className?: string;
}

export function ImageMode({ tenantId, className }: ImageModeProps) {
  const [prompt, setPrompt] = useState("");
  const [size, setSize] = useState("square");
  const [busy, setBusy] = useState(false);
  const [needsConfig, setNeedsConfig] = useState(false);
  const [result, setResult] = useState<{ url: string; size: string } | null>(null);

  const generate = async () => {
    if (prompt.trim().length < 4) { toast.error("Describe the image you want."); return; }
    setBusy(true); setNeedsConfig(false);
    try {
      const { data, error } = await supabase.functions.invoke("generate-image", {
        body: { prompt, size, tenant_id: tenantId },
      });
      if (error) throw error;
      if ((data as any)?.needs_config) { setNeedsConfig(true); return; }
      if ((data as any)?.error) throw new Error((data as any).error);
      const url = (data as any)?.url;
      if (!url) throw new Error("No image came back. Try again.");
      setResult({ url, size: (data as any)?.size || size });
      // Auto-filed to the library server-side — the StatePill below says so.
    } catch (e) {
      toast.error(growthSeamMessage(e, "Couldn't generate that image. Try again."));
    } finally { setBusy(false); }
  };

  return (
    <StudioSplit
      className={className}
      railHeader={
        <StudioRailHeading
          heading={MODE_RAIL.image.heading}
          description={MODE_RAIL.image.description}
        />
      }
      railBody={
        <>
          <div className="space-y-1.5">
            <Label htmlFor="img-prompt">Prompt</Label>
            <Textarea
              id="img-prompt" value={prompt} onChange={(e) => setPrompt(e.target.value)} rows={6}
              className="resize-none text-sm leading-relaxed"
              placeholder="e.g. A clean, modern promo graphic for a consulting webinar — indigo and gold palette, confident, minimal, space for a headline."
            />
          </div>
          <div className="space-y-1.5">
            <Label>Shape</Label>
            <Select value={size} onValueChange={setSize}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                <SelectItem value="square">Square (1:1)</SelectItem>
                <SelectItem value="portrait">Portrait (2:3)</SelectItem>
                <SelectItem value="landscape">Landscape (3:2)</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </>
      }
      railFooter={
        /* Indigo — generating isn't the act; the auto-file to the library is. */
        <Button onClick={generate} disabled={busy} variant="default" className="w-full gap-2">
          {busy
            ? <><Loader2 className="h-4 w-4 animate-spin motion-reduce:animate-none" /> Generating…</>
            : <><Send className="h-4 w-4" /> Generate image</>}
        </Button>
      }
      canvas={
        <div className="mx-auto w-full max-w-3xl">
          <SectionCard>
            {needsConfig ? (
              <EmptyState
                icon={Info} title="Image generation isn't switched on yet"
                description="It's not available on your account right now — reach out to turn it on. Drafting copy works now regardless."
              />
            ) : result ? (
              <div className="space-y-3">
                <div className="overflow-hidden rounded-[var(--radius)] border border-border bg-muted/30">
                  <img src={result.url} alt="Generated by Paige" className="mx-auto max-h-[60vh] w-auto max-w-full" />
                </div>
                <Toolbar>
                  <StatePill state="success">Saved to library</StatePill>
                  <Button asChild variant="outline" size="sm" className="gap-1.5">
                    <a href={result.url} download target="_blank" rel="noreferrer">
                      <Download className="h-3.5 w-3.5" /> Download
                    </a>
                  </Button>
                </Toolbar>
              </div>
            ) : (
              <EmptyState
                icon={Sparkles} tone="brand"
                title={MODE_EMPTY.image.title}
                description={MODE_EMPTY.image.description}
              />
            )}
          </SectionCard>
        </div>
      }
    />
  );
}

export default ImageMode;
