// Image mode — the absorbed Content Studio image generator, re-laid as a Studio workspace.
//
// Rail: shape picker, then the SHARED PromptComposer (§18 — the same conversational input
// page mode uses) pinned at the bottom, indigo submit. Canvas: the result (or the honest
// needs_config gate, preserved verbatim). There is NO gold in this mode — the act is the
// server auto-filing the image into the library, and the success StatePill reports that it
// happened (§13: report what actually happened).
//
// Generation routes through studio.ts's draftImage() seam (§10) — the exact `generate-image`
// invoke that used to live directly in this component, relocated behind the seam, unchanged
// in behavior, including the needs_config branch.
import { useState } from "react";
import { SectionCard, EmptyState, Toolbar, StatePill } from "@/components/ui/page";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { Download, Info, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { StudioRailHeading, StudioSplit } from "../StudioChrome";
import { MODE_EMPTY, MODE_RAIL } from "../studio-copy";
import { PromptComposer } from "../PromptComposer";
import { draftImage, isStudioError } from "../studio";
import { growthSeamMessage } from "@/lib/growth-templates";

export interface ImageModeProps {
  tenantId: string | null;
  className?: string;
  /** A prompt Paige already routed here from the Studio's single entry point (§18) — seeds
   *  the composer on this mode's first mount. Additive: an operator who deliberately clicks
   *  the Image chip still gets the normal blank composer and writes their own prompt. */
  initialPrompt?: string;
}

export function ImageMode({ tenantId, className, initialPrompt }: ImageModeProps) {
  const [prompt, setPrompt] = useState(initialPrompt ?? "");
  const [size, setSize] = useState("square");
  const [busy, setBusy] = useState(false);
  const [needsConfig, setNeedsConfig] = useState(false);
  const [result, setResult] = useState<{ url: string; size: string } | null>(null);

  const generate = async (value: string) => {
    const thePrompt = value.trim();
    if (thePrompt.length < 4) { toast.error("Describe the image you want."); return; }
    setBusy(true); setNeedsConfig(false);
    try {
      const out = await draftImage({ tenantId: tenantId ?? "", prompt: thePrompt, size });
      if (out.needsConfig) { setNeedsConfig(true); return; }
      setResult({ url: out.url, size: out.size });
      // Auto-filed to the library server-side — the StatePill below says so.
    } catch (e) {
      toast.error(isStudioError(e) ? e.message : growthSeamMessage(e, "Couldn't generate that image. Try again."));
    } finally { setBusy(false); }
  };

  return (
    <StudioSplit
      className={className}
      railHeader={
        <StudioRailHeading
          heading={MODE_RAIL.image.heading}
          description={MODE_RAIL.image.description}
        />
      }
      railBody={
        <div className="space-y-1.5">
          <Label>Shape</Label>
          <Select value={size} onValueChange={setSize}>
            <SelectTrigger><SelectValue /></SelectTrigger>
            <SelectContent>
              <SelectItem value="square">Square (1:1)</SelectItem>
              <SelectItem value="portrait">Portrait (2:3)</SelectItem>
              <SelectItem value="landscape">Landscape (3:2)</SelectItem>
            </SelectContent>
          </Select>
        </div>
      }
      railFooter={
        <PromptComposer
          mode="page"
          value={prompt}
          onChange={setPrompt}
          onSubmit={(value) => void generate(value)}
          busy={busy}
          heading={MODE_RAIL.image.heading}
          placeholder="e.g. A clean, modern promo graphic for a consulting webinar — indigo and gold palette, confident, minimal, space for a headline."
          helperText="Say what you need — the more specific the scene, palette, and mood, the closer the first result lands."
          submitLabel="Generate image"
          busyLabel="Generating…"
        />
      }
      canvas={
        <div className="mx-auto w-full max-w-3xl">
          <SectionCard>
            {needsConfig ? (
              <EmptyState
                icon={Info} title="Image generation isn't switched on yet"
                description="It's not available on your account right now — reach out to turn it on. Drafting copy works now regardless."
              />
            ) : result ? (
              <div className="space-y-3">
                <div className="overflow-hidden rounded-[var(--radius)] border border-border bg-muted/30">
                  <img src={result.url} alt="Generated by Paige" className="mx-auto max-h-[60vh] w-auto max-w-full" />
                </div>
                <Toolbar>
                  <StatePill state="success">Saved to library</StatePill>
                  <Button asChild variant="outline" size="sm" className="gap-1.5">
                    <a href={result.url} download target="_blank" rel="noreferrer">
                      <Download className="h-3.5 w-3.5" /> Download
                    </a>
                  </Button>
                </Toolbar>
              </div>
            ) : (
              <EmptyState
                icon={Sparkles} tone="brand"
                title={MODE_EMPTY.image.title}
                description={MODE_EMPTY.image.description}
              />
            )}
          </SectionCard>
        </div>
      }
    />
  );
}

export default ImageMode;
