import {useSyncExternalStore} from 'react';
const listeners=new Set<()=>void>();
let revision=0;
let tenant='A',mode='success',calls:any[]=[],pending:(()=>void)[]=[];
const pipeline=(id:string,ref:string,count=0)=>({id,name:'Build to Fund Again',shortRef:ref,description:'Deterministic local browser fixture',version:1,lifecycleStatus:'active',stageCount:2,dealCount:count,createdAt:'2026-08-31T12:00:00Z',updatedAt:'2026-09-03T12:00:00Z',createdByName:'Fixture owner',createdThrough:'owner',folderId:null});
let records:any={A:[pipeline('A1','PPL-AAAAA'),pipeline('A2','PPL-AAAAB'),pipeline('A3','PPL-AAAAC',2)],B:[pipeline('B1','PPL-BBBBB')]};
function emit(){revision++;listeners.forEach(fn=>fn());}
export const harness={setTenant(value:string){tenant=value;emit();},setMode(value:string){mode=value;emit();},reset(){tenant='A';mode='success';calls=[];pending=[];records={A:[pipeline('A1','PPL-AAAAA'),pipeline('A2','PPL-AAAAB'),pipeline('A3','PPL-AAAAC',2)],B:[pipeline('B1','PPL-BBBBB')]};emit();},resolve(){pending.splice(0).forEach(fn=>fn());},snapshot(){return structuredClone({tenant,mode,calls,records,catalog:{id:'service-1',name:'Build to Fund program',version:7}});}};
(window as any).pipelineHarness=harness;
export function useSoloCampaigns(){useSyncExternalStore(fn=>{listeners.add(fn);return()=>listeners.delete(fn);},()=>revision);const scope=tenant;const pipelines=records[scope];return {tenantId:scope,phase:mode==='loading'?'loading':'ready',campaigns:[],artifacts:[],submissions:[],retry:()=>{},pipelineWorkspace:{canManage:mode!=='readonly',canDelete:mode!=='readonly',canArchiveFolders:true,folders:[],pipelines,stages:pipelines.flatMap((p:any)=>[0,1].map(n=>({id:p.id+'s'+n,pipelineId:p.id,label:n?'Review':'Intake',description:'Owner-authored fixture stage',orderIndex:n,movePolicy:'direct',archivedAt:null}))),deals:[]},pipelineAction:async(action:any)=>{calls.push({scope,action});const operation=mode;const finish=()=>{if(operation==='error')return {ok:false,message:'Local test: connected route blocks deletion. Nothing changed.'};records[scope]=records[scope].filter((p:any)=>p.id!==action.pipelineId);emit();return {ok:true,message:'Pipeline deleted. Other pipelines and Catalog are unchanged.'};};if(operation==='pending')return new Promise(resolve=>pending.push(()=>resolve(finish())));return finish();}};}
