-- =============================================================================
-- SPRINT P.S.M — Phase 2 — Foreign-Key Harness — RE-ADD ALL (333)
-- =============================================================================
-- (a) Generated from BYO catalog (xygzykjyynhzqytbqnzu) on 2026-07-06 via
--     pg_get_constraintdef() — constraint definitions are verbatim from catalog.
-- (b) FK count: 333 — matches Cowork's pre-migration catalog count.
-- (c) The re-add IS the referential-integrity gate: every constraint re-validates
--     against imported data as it is recreated.
--
-- NOT VALID FALLBACK (inline, per Approach B): if any single ADD below fails on a
-- dangling production reference, replace that one line with the NOT VALID form —
--     ALTER TABLE public."<child>" ADD CONSTRAINT "<name>" <def> NOT VALID;
-- This preserves the byte-exact snapshot while flagging the drift for post-cutover
-- triage (validate later with: ALTER TABLE ... VALIDATE CONSTRAINT "<name>";).
-- Companion: PSM_phase2_fk_harness_drop_all.sql
-- =============================================================================

ALTER TABLE public."account_modifications" ADD CONSTRAINT "account_modifications_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."affiliate_applications" ADD CONSTRAINT "affiliate_applications_resulting_affiliate_id_fkey" FOREIGN KEY (resulting_affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE SET NULL;
ALTER TABLE public."affiliate_profiles" ADD CONSTRAINT "affiliate_profiles_commission_tier_id_fkey" FOREIGN KEY (commission_tier_id) REFERENCES affiliate_commission_tiers(id) ON DELETE RESTRICT;
ALTER TABLE public."affiliate_profiles" ADD CONSTRAINT "affiliate_profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."api_rate_limits" ADD CONSTRAINT "api_rate_limits_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."audit_logs" ADD CONSTRAINT "audit_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."balance_snapshots" ADD CONSTRAINT "balance_snapshots_account_id_fkey" FOREIGN KEY (account_id) REFERENCES connected_bank_accounts(id) ON DELETE CASCADE;
ALTER TABLE public."balance_snapshots" ADD CONSTRAINT "balance_snapshots_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."banking_relationships" ADD CONSTRAINT "banking_relationships_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."broker_client_relationships" ADD CONSTRAINT "broker_client_relationships_broker_id_fkey" FOREIGN KEY (broker_id) REFERENCES broker_profiles(id) ON DELETE CASCADE;
ALTER TABLE public."broker_paige_sessions" ADD CONSTRAINT "broker_paige_sessions_broker_id_fkey" FOREIGN KEY (broker_id) REFERENCES broker_profiles(id) ON DELETE CASCADE;
ALTER TABLE public."broker_paige_sessions" ADD CONSTRAINT "broker_paige_sessions_client_relationship_id_fkey" FOREIGN KEY (client_relationship_id) REFERENCES broker_client_relationships(id) ON DELETE CASCADE;
ALTER TABLE public."broker_paige_sessions" ADD CONSTRAINT "broker_paige_sessions_team_member_id_fkey" FOREIGN KEY (team_member_id) REFERENCES broker_team_members(id) ON DELETE SET NULL;
ALTER TABLE public."broker_referral_commissions" ADD CONSTRAINT "broker_referral_commissions_referred_broker_id_fkey" FOREIGN KEY (referred_broker_id) REFERENCES broker_profiles(id) ON DELETE CASCADE;
ALTER TABLE public."broker_referral_commissions" ADD CONSTRAINT "broker_referral_commissions_referring_broker_id_fkey" FOREIGN KEY (referring_broker_id) REFERENCES broker_profiles(id) ON DELETE CASCADE;
ALTER TABLE public."broker_session_messages" ADD CONSTRAINT "broker_session_messages_session_id_fkey" FOREIGN KEY (session_id) REFERENCES broker_paige_sessions(id) ON DELETE CASCADE;
ALTER TABLE public."broker_team_members" ADD CONSTRAINT "broker_team_members_auth_user_id_fkey" FOREIGN KEY (auth_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."broker_team_members" ADD CONSTRAINT "broker_team_members_broker_id_fkey" FOREIGN KEY (broker_id) REFERENCES broker_profiles(id) ON DELETE CASCADE;
ALTER TABLE public."browser_use_sessions" ADD CONSTRAINT "browser_use_sessions_related_business_id_fkey" FOREIGN KEY (related_business_id) REFERENCES businesses(id) ON DELETE SET NULL;
ALTER TABLE public."browser_use_sessions" ADD CONSTRAINT "browser_use_sessions_related_contact_id_fkey" FOREIGN KEY (related_contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."build_progress" ADD CONSTRAINT "build_progress_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."build_progress" ADD CONSTRAINT "build_progress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."build_recommendations" ADD CONSTRAINT "build_recommendations_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."build_scores" ADD CONSTRAINT "build_scores_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."business_certifications" ADD CONSTRAINT "business_certifications_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."business_credit_history" ADD CONSTRAINT "business_credit_history_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."business_credit_reports" ADD CONSTRAINT "business_credit_reports_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL;
ALTER TABLE public."business_financial_docs" ADD CONSTRAINT "business_financial_docs_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."business_financial_docs" ADD CONSTRAINT "business_financial_docs_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL;
ALTER TABLE public."business_public_presence" ADD CONSTRAINT "business_public_presence_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."business_vendors" ADD CONSTRAINT "business_vendors_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."business_vendors" ADD CONSTRAINT "business_vendors_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."business_verification_runs" ADD CONSTRAINT "business_verification_runs_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."business_verification_runs" ADD CONSTRAINT "business_verification_runs_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."business_verifications" ADD CONSTRAINT "business_verifications_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."business_verifications" ADD CONSTRAINT "business_verifications_run_id_fkey" FOREIGN KEY (run_id) REFERENCES business_verification_runs(id) ON DELETE CASCADE;
ALTER TABLE public."businesses" ADD CONSTRAINT "businesses_owner_user_id_fkey" FOREIGN KEY (owner_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."businesses" ADD CONSTRAINT "businesses_parent_business_id_fkey" FOREIGN KEY (parent_business_id) REFERENCES businesses(id) ON DELETE SET NULL;
ALTER TABLE public."chat_message_embeddings" ADD CONSTRAINT "chat_message_embeddings_message_id_fkey" FOREIGN KEY (message_id) REFERENCES chat_messages(id) ON DELETE CASCADE;
ALTER TABLE public."client_files" ADD CONSTRAINT "client_files_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."client_files" ADD CONSTRAINT "client_files_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."client_memory" ADD CONSTRAINT "client_memory_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."client_notes" ADD CONSTRAINT "client_notes_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."client_notes" ADD CONSTRAINT "client_notes_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."clients" ADD CONSTRAINT "clients_assigned_coach_user_id_fkey" FOREIGN KEY (assigned_coach_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."clients" ADD CONSTRAINT "clients_cs_primary_user_id_fkey" FOREIGN KEY (cs_primary_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."clients" ADD CONSTRAINT "clients_journey_stage_id_fkey" FOREIGN KEY (journey_stage_id) REFERENCES paige_journey_stages(id);
ALTER TABLE public."clients" ADD CONSTRAINT "clients_lead_owner_user_id_fkey" FOREIGN KEY (lead_owner_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."clients" ADD CONSTRAINT "clients_primary_business_id_fkey" FOREIGN KEY (primary_business_id) REFERENCES businesses(id) ON DELETE SET NULL;
ALTER TABLE public."clients" ADD CONSTRAINT "clients_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."coach_clients" ADD CONSTRAINT "coach_clients_client_user_id_fkey" FOREIGN KEY (client_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."coach_clients" ADD CONSTRAINT "coach_clients_coach_user_id_fkey" FOREIGN KEY (coach_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."commission_payments" ADD CONSTRAINT "commission_payments_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
ALTER TABLE public."communications_consents" ADD CONSTRAINT "communications_consents_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."compliance_checkpoints" ADD CONSTRAINT "compliance_checkpoints_consent_event_id_fkey" FOREIGN KEY (consent_event_id) REFERENCES consent_events(id);
ALTER TABLE public."compliance_checkpoints" ADD CONSTRAINT "compliance_checkpoints_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."connected_bank_account_secrets" ADD CONSTRAINT "connected_bank_account_secrets_account_row_id_fkey" FOREIGN KEY (account_row_id) REFERENCES connected_bank_accounts(id) ON DELETE CASCADE;
ALTER TABLE public."connected_bank_accounts" ADD CONSTRAINT "connected_bank_accounts_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."connected_bank_accounts" ADD CONSTRAINT "connected_bank_accounts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."consent_events" ADD CONSTRAINT "consent_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."conversation_context" ADD CONSTRAINT "conversation_context_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."course_certificates" ADD CONSTRAINT "course_certificates_course_id_fkey" FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE;
ALTER TABLE public."course_certificates" ADD CONSTRAINT "course_certificates_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."credit_accounts" ADD CONSTRAINT "credit_accounts_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."credit_accounts" ADD CONSTRAINT "credit_accounts_duplicate_of_id_fkey" FOREIGN KEY (duplicate_of_id) REFERENCES credit_accounts(id) ON DELETE SET NULL;
ALTER TABLE public."credit_accounts" ADD CONSTRAINT "credit_accounts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."credit_alerts" ADD CONSTRAINT "credit_alerts_client_id_fkey" FOREIGN KEY (client_id) REFERENCES profiles(user_id) ON DELETE CASCADE;
ALTER TABLE public."credit_alerts" ADD CONSTRAINT "credit_alerts_dismissed_by_fkey" FOREIGN KEY (dismissed_by) REFERENCES profiles(user_id);
ALTER TABLE public."credit_factor_scores" ADD CONSTRAINT "credit_factor_scores_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."credit_negative_items" ADD CONSTRAINT "credit_negative_items_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."credit_negative_items" ADD CONSTRAINT "credit_negative_items_duplicate_of_id_fkey" FOREIGN KEY (duplicate_of_id) REFERENCES credit_negative_items(id) ON DELETE SET NULL;
ALTER TABLE public."credit_predictions" ADD CONSTRAINT "credit_predictions_account_id_fkey" FOREIGN KEY (account_id) REFERENCES credit_accounts(id) ON DELETE SET NULL;
ALTER TABLE public."credit_report_personal_info" ADD CONSTRAINT "credit_report_personal_info_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."credit_report_personal_info" ADD CONSTRAINT "credit_report_personal_info_credit_report_upload_id_fkey" FOREIGN KEY (credit_report_upload_id) REFERENCES credit_report_uploads(id) ON DELETE CASCADE;
ALTER TABLE public."credit_report_uploads" ADD CONSTRAINT "credit_report_uploads_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."credit_report_verifications" ADD CONSTRAINT "credit_report_verifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."credit_utilization_snapshots" ADD CONSTRAINT "credit_utilization_snapshots_credit_account_id_fkey" FOREIGN KEY (credit_account_id) REFERENCES credit_accounts(id) ON DELETE CASCADE;
ALTER TABLE public."data_deletion_requests" ADD CONSTRAINT "data_deletion_requests_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."deal_activities" ADD CONSTRAINT "deal_activities_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."deal_activities" ADD CONSTRAINT "deal_activities_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE;
ALTER TABLE public."deals" ADD CONSTRAINT "deals_contact_client_id_fkey" FOREIGN KEY (contact_client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."deals" ADD CONSTRAINT "deals_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."deals" ADD CONSTRAINT "deals_owner_user_id_fkey" FOREIGN KEY (owner_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."deals" ADD CONSTRAINT "deals_pipeline_id_fkey" FOREIGN KEY (pipeline_id) REFERENCES pipelines(id) ON DELETE RESTRICT;
ALTER TABLE public."deals" ADD CONSTRAINT "deals_stage_id_fkey" FOREIGN KEY (stage_id) REFERENCES pipeline_stages(id) ON DELETE RESTRICT;
ALTER TABLE public."deals" ADD CONSTRAINT "deals_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."documents" ADD CONSTRAINT "documents_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."documents" ADD CONSTRAINT "documents_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."documents" ADD CONSTRAINT "documents_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."email_send_log" ADD CONSTRAINT "email_send_log_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."email_templates" ADD CONSTRAINT "email_templates_created_by_user_id_fkey" FOREIGN KEY (created_by_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."email_templates" ADD CONSTRAINT "email_templates_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."email_templates" ADD CONSTRAINT "email_templates_updated_by_user_id_fkey" FOREIGN KEY (updated_by_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."extraction_quality_log" ADD CONSTRAINT "extraction_quality_log_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."extraction_quality_log" ADD CONSTRAINT "extraction_quality_log_report_id_fkey" FOREIGN KEY (report_id) REFERENCES credit_report_uploads(id) ON DELETE CASCADE;
ALTER TABLE public."feature_request_votes" ADD CONSTRAINT "feature_request_votes_feature_request_id_fkey" FOREIGN KEY (feature_request_id) REFERENCES feature_requests(id) ON DELETE CASCADE;
ALTER TABLE public."financial_api_logs" ADD CONSTRAINT "financial_api_logs_consent_event_id_fkey" FOREIGN KEY (consent_event_id) REFERENCES consent_events(id);
ALTER TABLE public."financial_api_logs" ADD CONSTRAINT "financial_api_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."financial_document_analyses" ADD CONSTRAINT "financial_document_analyses_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id);
ALTER TABLE public."financial_document_analyses" ADD CONSTRAINT "financial_document_analyses_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE;
ALTER TABLE public."financial_kpis" ADD CONSTRAINT "financial_kpis_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."funding_application_outcomes" ADD CONSTRAINT "funding_application_outcomes_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."funding_application_sequence" ADD CONSTRAINT "funding_application_sequence_lender_product_id_fkey" FOREIGN KEY (lender_product_id) REFERENCES lender_products(id);
ALTER TABLE public."funding_applications" ADD CONSTRAINT "funding_applications_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."funding_applications" ADD CONSTRAINT "funding_applications_offer_id_fkey" FOREIGN KEY (offer_id) REFERENCES funding_offers(id) ON DELETE CASCADE;
ALTER TABLE public."funding_applications" ADD CONSTRAINT "funding_applications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."funding_journey_applications" ADD CONSTRAINT "funding_journey_applications_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL;
ALTER TABLE public."funding_matches" ADD CONSTRAINT "funding_matches_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."funding_matches" ADD CONSTRAINT "funding_matches_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."funding_matches" ADD CONSTRAINT "funding_matches_offer_id_fkey" FOREIGN KEY (offer_id) REFERENCES funding_offers(id) ON DELETE CASCADE;
ALTER TABLE public."funding_matches" ADD CONSTRAINT "funding_matches_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."funding_plans" ADD CONSTRAINT "funding_plans_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."funding_plans" ADD CONSTRAINT "funding_plans_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."growth_external_sources" ADD CONSTRAINT "growth_external_sources_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public."growth_external_sources" ADD CONSTRAINT "growth_external_sources_target_form_id_fkey" FOREIGN KEY (target_form_id) REFERENCES growth_forms(id) ON DELETE SET NULL;
ALTER TABLE public."growth_external_sources" ADD CONSTRAINT "growth_external_sources_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."growth_form_submissions" ADD CONSTRAINT "growth_form_submissions_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."growth_form_submissions" ADD CONSTRAINT "growth_form_submissions_form_id_fkey" FOREIGN KEY (form_id) REFERENCES growth_forms(id) ON DELETE CASCADE;
ALTER TABLE public."growth_form_submissions" ADD CONSTRAINT "growth_form_submissions_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."growth_forms" ADD CONSTRAINT "growth_forms_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public."growth_forms" ADD CONSTRAINT "growth_forms_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."growth_funnel_steps" ADD CONSTRAINT "growth_funnel_steps_form_id_fkey" FOREIGN KEY (form_id) REFERENCES growth_forms(id) ON DELETE SET NULL;
ALTER TABLE public."growth_funnel_steps" ADD CONSTRAINT "growth_funnel_steps_funnel_id_fkey" FOREIGN KEY (funnel_id) REFERENCES growth_funnels(id) ON DELETE CASCADE;
ALTER TABLE public."growth_funnel_steps" ADD CONSTRAINT "growth_funnel_steps_page_id_fkey" FOREIGN KEY (page_id) REFERENCES growth_pages(id) ON DELETE SET NULL;
ALTER TABLE public."growth_funnel_steps" ADD CONSTRAINT "growth_funnel_steps_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."growth_funnels" ADD CONSTRAINT "growth_funnels_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public."growth_funnels" ADD CONSTRAINT "growth_funnels_entry_page_id_fkey" FOREIGN KEY (entry_page_id) REFERENCES growth_pages(id) ON DELETE SET NULL;
ALTER TABLE public."growth_funnels" ADD CONSTRAINT "growth_funnels_success_page_id_fkey" FOREIGN KEY (success_page_id) REFERENCES growth_pages(id) ON DELETE SET NULL;
ALTER TABLE public."growth_funnels" ADD CONSTRAINT "growth_funnels_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."growth_pages" ADD CONSTRAINT "growth_pages_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public."growth_pages" ADD CONSTRAINT "growth_pages_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."internal_bookings" ADD CONSTRAINT "internal_bookings_cancelled_by_fkey" FOREIGN KEY (cancelled_by) REFERENCES auth.users(id);
ALTER TABLE public."internal_bookings" ADD CONSTRAINT "internal_bookings_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."internal_bookings" ADD CONSTRAINT "internal_bookings_host_user_id_fkey" FOREIGN KEY (host_user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."internal_bookings" ADD CONSTRAINT "internal_bookings_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."invitations" ADD CONSTRAINT "invitations_invited_by_fkey" FOREIGN KEY (invited_by) REFERENCES auth.users(id);
ALTER TABLE public."invitations" ADD CONSTRAINT "invitations_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."kb_coverage_signal" ADD CONSTRAINT "kb_coverage_signal_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."kb_query_telemetry" ADD CONSTRAINT "kb_query_telemetry_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."legal_acceptances" ADD CONSTRAINT "legal_acceptances_document_id_fkey" FOREIGN KEY (document_id) REFERENCES legal_documents(id);
ALTER TABLE public."legal_acceptances" ADD CONSTRAINT "legal_acceptances_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."legal_documents" ADD CONSTRAINT "legal_documents_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public."lessons" ADD CONSTRAINT "lessons_course_id_fkey" FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE;
ALTER TABLE public."notification_preferences" ADD CONSTRAINT "notification_preferences_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."notifications" ADD CONSTRAINT "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."orders" ADD CONSTRAINT "orders_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."paige_admin_notifications" ADD CONSTRAINT "paige_admin_notifications_assigned_user_id_fkey" FOREIGN KEY (assigned_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_admin_notifications" ADD CONSTRAINT "paige_admin_notifications_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_approval_comments" ADD CONSTRAINT "paige_approval_comments_approval_id_fkey" FOREIGN KEY (approval_id) REFERENCES paige_pending_approvals(id) ON DELETE CASCADE;
ALTER TABLE public."paige_audit_log" ADD CONSTRAINT "paige_audit_log_actor_user_id_fkey" FOREIGN KEY (actor_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_audit_log" ADD CONSTRAINT "paige_audit_log_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."paige_bank_connections" ADD CONSTRAINT "paige_bank_connections_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_bank_transactions" ADD CONSTRAINT "paige_bank_transactions_bank_connection_id_fkey" FOREIGN KEY (bank_connection_id) REFERENCES paige_bank_connections(id) ON DELETE CASCADE;
ALTER TABLE public."paige_bookings" ADD CONSTRAINT "paige_bookings_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_business_credit_profiles" ADD CONSTRAINT "paige_business_credit_profiles_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_cash_flow_snapshots" ADD CONSTRAINT "paige_cash_flow_snapshots_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_chat_threads" ADD CONSTRAINT "paige_chat_threads_caller_user_id_fkey" FOREIGN KEY (caller_user_id) REFERENCES auth.users(id) ON DELETE RESTRICT;
ALTER TABLE public."paige_chat_threads" ADD CONSTRAINT "paige_chat_threads_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_chat_threads" ADD CONSTRAINT "paige_chat_threads_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE public."paige_chat_turns" ADD CONSTRAINT "paige_chat_turns_thread_id_fkey" FOREIGN KEY (thread_id) REFERENCES paige_chat_threads(id) ON DELETE CASCADE;
ALTER TABLE public."paige_client_intake_submissions" ADD CONSTRAINT "paige_client_intake_submissions_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_coach_assignments" ADD CONSTRAINT "paige_coach_assignments_coach_id_fkey" FOREIGN KEY (coach_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_coach_assignments" ADD CONSTRAINT "paige_coach_assignments_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_coach_assignments" ADD CONSTRAINT "paige_coach_assignments_rep_user_id_fkey" FOREIGN KEY (rep_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_coach_assignments" ADD CONSTRAINT "paige_coach_assignments_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."paige_config" ADD CONSTRAINT "paige_config_updated_by_fkey" FOREIGN KEY (updated_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_conversations" ADD CONSTRAINT "paige_conversations_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_conversations" ADD CONSTRAINT "paige_conversations_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."paige_customer_actions" ADD CONSTRAINT "paige_customer_actions_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_customer_actions" ADD CONSTRAINT "paige_customer_actions_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."paige_customer_responses" ADD CONSTRAINT "paige_customer_responses_action_id_fkey" FOREIGN KEY (action_id) REFERENCES paige_customer_actions(id) ON DELETE CASCADE;
ALTER TABLE public."paige_customer_responses" ADD CONSTRAINT "paige_customer_responses_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_data_source_sync_state" ADD CONSTRAINT "paige_data_source_sync_state_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."paige_enrichment_log" ADD CONSTRAINT "paige_enrichment_log_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_health_snapshots" ADD CONSTRAINT "paige_health_snapshots_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_ingestion_proposals" ADD CONSTRAINT "paige_ingestion_proposals_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_invoices" ADD CONSTRAINT "paige_invoices_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_invoices" ADD CONSTRAINT "paige_invoices_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_invoices" ADD CONSTRAINT "paige_invoices_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL;
ALTER TABLE public."paige_invoices" ADD CONSTRAINT "paige_invoices_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."paige_journey_stage_transitions" ADD CONSTRAINT "paige_journey_stage_transitions_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_journey_stage_transitions" ADD CONSTRAINT "paige_journey_stage_transitions_from_stage_id_fkey" FOREIGN KEY (from_stage_id) REFERENCES paige_journey_stages(id);
ALTER TABLE public."paige_journey_stage_transitions" ADD CONSTRAINT "paige_journey_stage_transitions_to_stage_id_fkey" FOREIGN KEY (to_stage_id) REFERENCES paige_journey_stages(id);
ALTER TABLE public."paige_mcp_oauth_clients" ADD CONSTRAINT "paige_mcp_oauth_clients_created_by_user_id_fkey" FOREIGN KEY (created_by_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_mcp_oauth_codes" ADD CONSTRAINT "paige_mcp_oauth_codes_client_id_fkey" FOREIGN KEY (client_id) REFERENCES paige_mcp_oauth_clients(client_id) ON DELETE CASCADE;
ALTER TABLE public."paige_mcp_oauth_codes" ADD CONSTRAINT "paige_mcp_oauth_codes_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."paige_mcp_oauth_tokens" ADD CONSTRAINT "paige_mcp_oauth_tokens_client_id_fkey" FOREIGN KEY (client_id) REFERENCES paige_mcp_oauth_clients(client_id) ON DELETE CASCADE;
ALTER TABLE public."paige_mcp_oauth_tokens" ADD CONSTRAINT "paige_mcp_oauth_tokens_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."paige_messages_audit" ADD CONSTRAINT "paige_messages_audit_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_messages_audit" ADD CONSTRAINT "paige_messages_audit_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES paige_conversations(id) ON DELETE SET NULL;
ALTER TABLE public."paige_nps_responses" ADD CONSTRAINT "paige_nps_responses_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_owner_credit_snapshots" ADD CONSTRAINT "paige_owner_credit_snapshots_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_payment_authorizations" ADD CONSTRAINT "paige_payment_authorizations_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_pending_approvals" ADD CONSTRAINT "paige_pending_approvals_assigned_to_user_id_fkey" FOREIGN KEY (assigned_to_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_pending_approvals" ADD CONSTRAINT "paige_pending_approvals_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_pending_approvals" ADD CONSTRAINT "paige_pending_approvals_conversation_id_fkey" FOREIGN KEY (conversation_id) REFERENCES paige_conversations(id) ON DELETE SET NULL;
ALTER TABLE public."paige_pending_approvals" ADD CONSTRAINT "paige_pending_approvals_reviewed_by_user_id_fkey" FOREIGN KEY (reviewed_by_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_pending_approvals" ADD CONSTRAINT "paige_pending_approvals_sent_message_audit_id_fkey" FOREIGN KEY (sent_message_audit_id) REFERENCES paige_messages_audit(id) ON DELETE SET NULL;
ALTER TABLE public."paige_pending_approvals" ADD CONSTRAINT "paige_pending_approvals_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."paige_readiness_proposals" ADD CONSTRAINT "paige_readiness_proposals_approved_by_fkey" FOREIGN KEY (approved_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_readiness_proposals" ADD CONSTRAINT "paige_readiness_proposals_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_readiness_proposals" ADD CONSTRAINT "paige_readiness_proposals_rejected_by_fkey" FOREIGN KEY (rejected_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_readiness_proposals" ADD CONSTRAINT "paige_readiness_proposals_scan_run_id_fkey" FOREIGN KEY (scan_run_id) REFERENCES paige_readiness_scan_runs(id) ON DELETE SET NULL;
ALTER TABLE public."paige_readiness_proposals" ADD CONSTRAINT "paige_readiness_proposals_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."paige_readiness_scan_runs" ADD CONSTRAINT "paige_readiness_scan_runs_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."paige_referrals" ADD CONSTRAINT "paige_referrals_referred_contact_id_fkey" FOREIGN KEY (referred_contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_referrals" ADD CONSTRAINT "paige_referrals_referrer_contact_id_fkey" FOREIGN KEY (referrer_contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_signature_envelopes" ADD CONSTRAINT "paige_signature_envelopes_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_signature_envelopes" ADD CONSTRAINT "paige_signature_envelopes_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_signed_agreements" ADD CONSTRAINT "paige_signed_agreements_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_skill_proposals" ADD CONSTRAINT "paige_skill_proposals_published_skill_id_fkey" FOREIGN KEY (published_skill_id) REFERENCES paige_skills(id) ON DELETE SET NULL;
ALTER TABLE public."paige_skill_runs" ADD CONSTRAINT "paige_skill_runs_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_skill_runs" ADD CONSTRAINT "paige_skill_runs_skill_id_fkey" FOREIGN KEY (skill_id) REFERENCES paige_skills(id) ON DELETE CASCADE;
ALTER TABLE public."paige_sla_alert_log" ADD CONSTRAINT "paige_sla_alert_log_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."paige_social_posts" ADD CONSTRAINT "paige_social_posts_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_subagent_invocations" ADD CONSTRAINT "paige_subagent_invocations_invoked_by_fkey" FOREIGN KEY (invoked_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."paige_subagent_proposals" ADD CONSTRAINT "paige_subagent_proposals_resulting_subagent_id_fkey" FOREIGN KEY (resulting_subagent_id) REFERENCES paige_subagents(id) ON DELETE SET NULL;
ALTER TABLE public."paige_subscription_events" ADD CONSTRAINT "paige_subscription_events_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."paige_workflow_registry" ADD CONSTRAINT "paige_workflow_registry_connection_id_fkey" FOREIGN KEY (connection_id) REFERENCES paige_n8n_connections(id) ON DELETE SET NULL;
ALTER TABLE public."paige_workflow_registry" ADD CONSTRAINT "paige_workflow_registry_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."paige_workflow_runs" ADD CONSTRAINT "paige_workflow_runs_registry_id_fkey" FOREIGN KEY (registry_id) REFERENCES paige_workflow_registry(id) ON DELETE CASCADE;
ALTER TABLE public."paige_workflow_runs" ADD CONSTRAINT "paige_workflow_runs_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."paige_workflow_runs" ADD CONSTRAINT "paige_workflow_runs_triggered_by_user_id_fkey" FOREIGN KEY (triggered_by_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."pipeline_stages" ADD CONSTRAINT "pipeline_stages_pipeline_id_fkey" FOREIGN KEY (pipeline_id) REFERENCES pipelines(id) ON DELETE CASCADE;
ALTER TABLE public."pipeline_stages" ADD CONSTRAINT "pipeline_stages_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."pipelines" ADD CONSTRAINT "pipelines_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."pipelines" ADD CONSTRAINT "pipelines_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."plaid_notifications" ADD CONSTRAINT "plaid_notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."plaid_transactions" ADD CONSTRAINT "plaid_transactions_account_id_fkey" FOREIGN KEY (account_id) REFERENCES connected_bank_accounts(id) ON DELETE CASCADE;
ALTER TABLE public."plaid_transactions" ADD CONSTRAINT "plaid_transactions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."plaid_webhook_events" ADD CONSTRAINT "plaid_webhook_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."platform_invoices" ADD CONSTRAINT "platform_invoices_subscription_id_fkey" FOREIGN KEY (subscription_id) REFERENCES platform_subscriptions(id) ON DELETE SET NULL;
ALTER TABLE public."platform_invoices" ADD CONSTRAINT "platform_invoices_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."platform_metered_events" ADD CONSTRAINT "platform_metered_events_end_customer_contact_id_fkey" FOREIGN KEY (end_customer_contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."platform_metered_events" ADD CONSTRAINT "platform_metered_events_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."platform_metering_reconciliation" ADD CONSTRAINT "platform_metering_reconciliation_invoice_id_fkey" FOREIGN KEY (invoice_id) REFERENCES platform_invoices(id) ON DELETE SET NULL;
ALTER TABLE public."platform_metering_reconciliation" ADD CONSTRAINT "platform_metering_reconciliation_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."platform_subscriptions" ADD CONSTRAINT "platform_subscriptions_plan_id_fkey" FOREIGN KEY (plan_id) REFERENCES platform_subscription_plans(id);
ALTER TABLE public."platform_subscriptions" ADD CONSTRAINT "platform_subscriptions_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."platform_usage_events" ADD CONSTRAINT "platform_usage_events_reconciled_invoice_id_fkey" FOREIGN KEY (reconciled_invoice_id) REFERENCES platform_invoices(id) ON DELETE SET NULL;
ALTER TABLE public."platform_usage_events" ADD CONSTRAINT "platform_usage_events_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_active_tenant_id_fkey" FOREIGN KEY (active_tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_suspended_by_fkey" FOREIGN KEY (suspended_by) REFERENCES auth.users(id);
ALTER TABLE public."profiles" ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."program_approvals" ADD CONSTRAINT "program_approvals_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."program_approvals" ADD CONSTRAINT "program_approvals_enrollment_id_fkey" FOREIGN KEY (enrollment_id) REFERENCES program_enrollments(id) ON DELETE CASCADE;
ALTER TABLE public."program_document_requests" ADD CONSTRAINT "program_document_requests_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."program_document_requests" ADD CONSTRAINT "program_document_requests_document_id_fkey" FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL;
ALTER TABLE public."program_document_requests" ADD CONSTRAINT "program_document_requests_enrollment_id_fkey" FOREIGN KEY (enrollment_id) REFERENCES program_enrollments(id) ON DELETE CASCADE;
ALTER TABLE public."program_enrollments" ADD CONSTRAINT "program_enrollments_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."program_enrollments" ADD CONSTRAINT "program_enrollments_program_id_fkey" FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE;
ALTER TABLE public."program_messages" ADD CONSTRAINT "program_messages_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."program_messages" ADD CONSTRAINT "program_messages_enrollment_id_fkey" FOREIGN KEY (enrollment_id) REFERENCES program_enrollments(id) ON DELETE CASCADE;
ALTER TABLE public."program_phase_item_states" ADD CONSTRAINT "program_phase_item_states_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."program_phase_item_states" ADD CONSTRAINT "program_phase_item_states_enrollment_id_fkey" FOREIGN KEY (enrollment_id) REFERENCES program_enrollments(id) ON DELETE CASCADE;
ALTER TABLE public."program_phase_item_states" ADD CONSTRAINT "program_phase_item_states_phase_item_id_fkey" FOREIGN KEY (phase_item_id) REFERENCES program_phase_items(id) ON DELETE RESTRICT;
ALTER TABLE public."program_phase_items" ADD CONSTRAINT "program_phase_items_phase_id_fkey" FOREIGN KEY (phase_id) REFERENCES program_phases(id) ON DELETE CASCADE;
ALTER TABLE public."program_phases" ADD CONSTRAINT "program_phases_program_id_fkey" FOREIGN KEY (program_id) REFERENCES programs(id) ON DELETE CASCADE;
ALTER TABLE public."programs" ADD CONSTRAINT "programs_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."push_notification_log" ADD CONSTRAINT "push_notification_log_subscription_id_fkey" FOREIGN KEY (subscription_id) REFERENCES push_subscriptions(id) ON DELETE SET NULL;
ALTER TABLE public."quickbooks_connections" ADD CONSTRAINT "quickbooks_connections_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL;
ALTER TABLE public."quickbooks_financials" ADD CONSTRAINT "quickbooks_financials_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE SET NULL;
ALTER TABLE public."quickbooks_financials" ADD CONSTRAINT "quickbooks_financials_qb_connection_id_fkey" FOREIGN KEY (qb_connection_id) REFERENCES quickbooks_connections(id) ON DELETE CASCADE;
ALTER TABLE public."quickbooks_transactions" ADD CONSTRAINT "quickbooks_transactions_qb_connection_id_fkey" FOREIGN KEY (qb_connection_id) REFERENCES quickbooks_connections(id) ON DELETE CASCADE;
ALTER TABLE public."rag_documents" ADD CONSTRAINT "rag_documents_client_id_fkey" FOREIGN KEY (client_id) REFERENCES profiles(user_id) ON DELETE SET NULL;
ALTER TABLE public."rag_retrieval_log" ADD CONSTRAINT "rag_retrieval_log_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(user_id) ON DELETE SET NULL;
ALTER TABLE public."referral_clicks" ADD CONSTRAINT "referral_clicks_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE SET NULL;
ALTER TABLE public."referral_codes" ADD CONSTRAINT "referral_codes_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
ALTER TABLE public."referral_conversions" ADD CONSTRAINT "referral_conversions_affiliate_id_fkey" FOREIGN KEY (affiliate_id) REFERENCES affiliate_profiles(id) ON DELETE CASCADE;
ALTER TABLE public."referral_conversions" ADD CONSTRAINT "referral_conversions_referred_user_id_fkey" FOREIGN KEY (referred_user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."staff_calendar_settings" ADD CONSTRAINT "staff_calendar_settings_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."staff_calendar_settings" ADD CONSTRAINT "staff_calendar_settings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."stage_automation_events" ADD CONSTRAINT "stage_automation_events_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."stage_automation_events" ADD CONSTRAINT "stage_automation_events_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE CASCADE;
ALTER TABLE public."stage_automation_events" ADD CONSTRAINT "stage_automation_events_rule_id_fkey" FOREIGN KEY (rule_id) REFERENCES stage_automation_rules(id) ON DELETE SET NULL;
ALTER TABLE public."stage_automation_events" ADD CONSTRAINT "stage_automation_events_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."stage_automation_rules" ADD CONSTRAINT "stage_automation_rules_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."stage_automation_rules" ADD CONSTRAINT "stage_automation_rules_from_stage_id_fkey" FOREIGN KEY (from_stage_id) REFERENCES pipeline_stages(id) ON DELETE CASCADE;
ALTER TABLE public."stage_automation_rules" ADD CONSTRAINT "stage_automation_rules_pipeline_id_fkey" FOREIGN KEY (pipeline_id) REFERENCES pipelines(id) ON DELETE CASCADE;
ALTER TABLE public."stage_automation_rules" ADD CONSTRAINT "stage_automation_rules_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."stage_automation_rules" ADD CONSTRAINT "stage_automation_rules_to_stage_id_fkey" FOREIGN KEY (to_stage_id) REFERENCES pipeline_stages(id) ON DELETE CASCADE;
ALTER TABLE public."support_ticket_last_seen" ADD CONSTRAINT "support_ticket_last_seen_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE;
ALTER TABLE public."support_ticket_messages" ADD CONSTRAINT "support_ticket_messages_ticket_id_fkey" FOREIGN KEY (ticket_id) REFERENCES support_tickets(id) ON DELETE CASCADE;
ALTER TABLE public."tasks" ADD CONSTRAINT "tasks_biz_id_fkey" FOREIGN KEY (biz_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."tasks" ADD CONSTRAINT "tasks_deal_id_fkey" FOREIGN KEY (deal_id) REFERENCES deals(id) ON DELETE SET NULL;
ALTER TABLE public."tasks" ADD CONSTRAINT "tasks_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."tasks" ADD CONSTRAINT "tasks_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_account_number_seq" ADD CONSTRAINT "tenant_account_number_seq_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_agreement_versions" ADD CONSTRAINT "tenant_agreement_versions_base_template_id_fkey" FOREIGN KEY (base_template_id) REFERENCES agreement_templates(id);
ALTER TABLE public."tenant_agreement_versions" ADD CONSTRAINT "tenant_agreement_versions_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE public."tenant_agreement_versions" ADD CONSTRAINT "tenant_agreement_versions_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_delegations" ADD CONSTRAINT "tenant_delegations_from_tenant_id_fkey" FOREIGN KEY (from_tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_delegations" ADD CONSTRAINT "tenant_delegations_to_tenant_id_fkey" FOREIGN KEY (to_tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_email_domains" ADD CONSTRAINT "tenant_email_domains_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_entity_relationships" ADD CONSTRAINT "tenant_entity_relationships_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES clients(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_entity_relationships" ADD CONSTRAINT "tenant_entity_relationships_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."tenant_entity_relationships" ADD CONSTRAINT "tenant_entity_relationships_entity_id_fkey" FOREIGN KEY (entity_id) REFERENCES corporate_entity_registry(id) ON DELETE RESTRICT;
ALTER TABLE public."tenant_entity_relationships" ADD CONSTRAINT "tenant_entity_relationships_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE public."tenant_features" ADD CONSTRAINT "tenant_features_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_invite_tokens" ADD CONSTRAINT "tenant_invite_tokens_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_knowledge_chunks" ADD CONSTRAINT "tenant_knowledge_chunks_doc_id_fkey" FOREIGN KEY (doc_id) REFERENCES tenant_knowledge_docs(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_knowledge_chunks" ADD CONSTRAINT "tenant_knowledge_chunks_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_knowledge_docs" ADD CONSTRAINT "tenant_knowledge_docs_promoted_to_canon_id_fkey" FOREIGN KEY (promoted_to_canon_id) REFERENCES knowledge_base(id) ON DELETE SET NULL;
ALTER TABLE public."tenant_knowledge_docs" ADD CONSTRAINT "tenant_knowledge_docs_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_legal_profile" ADD CONSTRAINT "tenant_legal_profile_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_members" ADD CONSTRAINT "tenant_members_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_orders" ADD CONSTRAINT "tenant_orders_price_id_fkey" FOREIGN KEY (price_id) REFERENCES tenant_prices(id) ON DELETE SET NULL;
ALTER TABLE public."tenant_orders" ADD CONSTRAINT "tenant_orders_product_id_fkey" FOREIGN KEY (product_id) REFERENCES tenant_products(id) ON DELETE SET NULL;
ALTER TABLE public."tenant_orders" ADD CONSTRAINT "tenant_orders_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_prices" ADD CONSTRAINT "tenant_prices_product_id_fkey" FOREIGN KEY (product_id) REFERENCES tenant_products(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_prices" ADD CONSTRAINT "tenant_prices_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_products" ADD CONSTRAINT "tenant_products_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."tenant_products" ADD CONSTRAINT "tenant_products_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_service_subscriptions" ADD CONSTRAINT "tenant_service_subscriptions_end_customer_contact_id_fkey" FOREIGN KEY (end_customer_contact_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."tenant_service_subscriptions" ADD CONSTRAINT "tenant_service_subscriptions_price_id_fkey" FOREIGN KEY (price_id) REFERENCES tenant_prices(id) ON DELETE SET NULL;
ALTER TABLE public."tenant_service_subscriptions" ADD CONSTRAINT "tenant_service_subscriptions_product_id_fkey" FOREIGN KEY (product_id) REFERENCES tenant_products(id) ON DELETE SET NULL;
ALTER TABLE public."tenant_service_subscriptions" ADD CONSTRAINT "tenant_service_subscriptions_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_service_usage_events" ADD CONSTRAINT "tenant_service_usage_events_subscription_id_fkey" FOREIGN KEY (subscription_id) REFERENCES tenant_service_subscriptions(id) ON DELETE SET NULL;
ALTER TABLE public."tenant_service_usage_events" ADD CONSTRAINT "tenant_service_usage_events_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenant_stripe_accounts" ADD CONSTRAINT "tenant_stripe_accounts_tenant_id_fkey" FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE public."tenants" ADD CONSTRAINT "tenants_parent_tenant_id_fkey" FOREIGN KEY (parent_tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE public."tier_state" ADD CONSTRAINT "tier_state_client_id_fkey" FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL;
ALTER TABLE public."tier_state" ADD CONSTRAINT "tier_state_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE public."user_build_milestones" ADD CONSTRAINT "user_build_milestones_business_id_fkey" FOREIGN KEY (business_id) REFERENCES businesses(id) ON DELETE CASCADE;
ALTER TABLE public."user_build_milestones" ADD CONSTRAINT "user_build_milestones_milestone_id_fkey" FOREIGN KEY (milestone_id) REFERENCES build_milestones(id) ON DELETE CASCADE;
ALTER TABLE public."user_build_milestones" ADD CONSTRAINT "user_build_milestones_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."user_business_limits" ADD CONSTRAINT "user_business_limits_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."user_funding_matches" ADD CONSTRAINT "user_funding_matches_lender_product_id_fkey" FOREIGN KEY (lender_product_id) REFERENCES lender_products(id) ON DELETE CASCADE;
ALTER TABLE public."user_progress" ADD CONSTRAINT "user_progress_course_id_fkey" FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE;
ALTER TABLE public."user_progress" ADD CONSTRAINT "user_progress_lesson_id_fkey" FOREIGN KEY (lesson_id) REFERENCES lessons(id) ON DELETE CASCADE;
ALTER TABLE public."user_progress" ADD CONSTRAINT "user_progress_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."user_roles" ADD CONSTRAINT "user_roles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public."voice_command_logs" ADD CONSTRAINT "voice_command_logs_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
