import { PAIGE_SPINE_CAPABILITIES, validateSpineRegistry } from '../../../supabase/functions/_shared/paige-spine/registry.ts';
import { classifyAction } from '../../../supabase/functions/_shared/action-risk.ts';
/* eslint-disable @typescript-eslint/no-explicit-any -- Executed server helper with isolated RPC/provider test ports. */
// @vitest-environment node
import type {SpineCapability} from '../../../supabase/functions/_shared/paige-spine/contracts';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
import {describe,it,expect,vi} from 'vitest';
function harness(options:{scope?:string[];response?:unknown;missingTool?:boolean;rpcFail?:string;failSecondCheck?:boolean;callError?:Error;expired?:boolean;refreshScopes?:string[]}={}){
 const lease={lease:'lease',generation:'generation',server_url:'https://n8n.example/mcp-server/http',access_token:'canary-access',refresh_token:'canary-refresh',client_secret:'canary-client',expires_at:'2099-01-01',issuer:'https://n8n.example',client_id:'client',oauth_scopes:options.scope??['workflow:read','workflow:write','workflow:execute','execution:read']};
 let checks=0;
 const admin={rpc:vi.fn(async(_name:string,args:any)=>({data:args._operation==='acquire'?lease:{ok:true},error:(args._operation===options.rpcFail||(args._operation==='check'&&++checks===2&&options.failSecondCheck))?{message:'N8N_TENANT_CHANGED canary-private'}:null}))};
 const call=vi.fn(async()=>{if(options.callError)throw options.callError;return options.response??{structuredContent:{workflowId:'wf1',name:'Workflow',active:false,success:true,activeVersionId:'v1'}}});
 const session=vi.fn(async(_opts:any,body:any)=>body({tools:options.missingTool?[]:['get_workflow_sdk_reference','search_workflows','get_workflow_details','search_workflow_executions','get_workflow_execution','create_workflow_from_code','update_workflow','publish_workflow','unpublish_workflow','archive_workflow','execute_workflow','validate_workflow'].map(name=>({name})),call}));
 const revoke=vi.fn(async()=>true);
 const modules:any={'./mcp-client.ts':{withApprovedCapabilitySession:session},'./mcp-oauth.ts':{discoverAuthorizationServer:async()=>({issuer:lease.issuer}),isExpired:(expiry:string)=>options.expired&&expiry==='2099-01-01',refreshTokens:async()=>({accessToken:'canary-rotated',refreshToken:'canary-refresh-new',expiresAt:'2100-01-01',scopes:options.refreshScopes??lease.oauth_scopes}),revokeToken:revoke},'./n8n-oauth.ts':{validateN8nResource:()=>{},validateServer:()=>{}}};
 const output:any={};const js=ts.transpileModule(readFileSync('supabase/functions/_shared/n8n-management.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
 new Function('require','exports',js)((key:string)=>modules[key],output);
 const run=(tool='n8n_activate_workflow',args:any={workflow_id:'wf1',version_id:'v1'},approved=true)=>output.runN8nManagement({admin,userId:'owner',tenantId:'tenant',sessionId:'20000000-0000-0000-0000-000000000001',tool,args,mutationApproved:approved});
 return {run,admin,call,session,revoke,output};
}
describe('executed server-only n8n management adapter',()=>{
 it('refuses mutation before any secret lookup without owner approval',async()=>{const h=harness();expect(await h.run(undefined,undefined,false)).toMatchObject({error:'owner_approval_required'});expect(h.admin.rpc).not.toHaveBeenCalled();expect(h.call).not.toHaveBeenCalled()});
 it('passes exact approved operations and checks bound session around provider call',async()=>{const h=harness();const operations=[{type:'removeNode',nodeName:'Old'}];expect(await h.run('n8n_update_workflow',{workflow_id:'wf1',operations,versionName:'Remove old node',versionDescription:'Approved change'})).toMatchObject({ok:true});expect(h.call).toHaveBeenCalledExactlyOnceWith('update_workflow',{workflowId:'wf1',operations,versionName:'Remove old node',versionDescription:'Approved change'});expect(h.admin.rpc.mock.calls.map(c=>c[1]._operation??c[0])).toEqual(['acquire','check','check','record_capability_run','release']);for(const c of h.admin.rpc.mock.calls.filter(c=>c[1]._operation))expect(c[1]._input).toMatchObject({actor_id:'owner',tenant_id:'tenant',session_id:'20000000-0000-0000-0000-000000000001'})});
 it('refuses missing runtime provider capability and releases lease',async()=>{const h=harness({missingTool:true});expect(await h.run()).toMatchObject({error:'provider_tool_unavailable'});expect(h.call).not.toHaveBeenCalled();expect(h.admin.rpc.mock.calls.at(-1)?.[1]._operation).toBe('release')});
 it('does not break existing read/write connection when execute scope absent',async()=>{const h=harness({scope:['workflow:read','workflow:write']});expect(await h.run('n8n_run_workflow',{workflow_id:'wf1',execution_mode:'production'})).toMatchObject({error:'authorization_needed',required_scope:'workflow:execute'});expect(h.call).not.toHaveBeenCalled()});
 it('fails before provider call on workspace/session fence failure',async()=>{const h=harness({rpcFail:'check'});expect(await h.run()).toMatchObject({error:'tenant_changed'});expect(h.call).not.toHaveBeenCalled()});
 it('suppresses provider result when the workspace fence changes during a write',async()=>{const h=harness({failSecondCheck:true});expect(await h.run()).toEqual({ok:false,error:'outcome_unknown',retry_safe:false});expect(h.call).toHaveBeenCalledTimes(1)});
 it('suppresses read data when the workspace fence changes during provider read',async()=>{const h=harness({failSecondCheck:true,response:{structuredContent:{count:1,data:[{id:'wf1',name:'Private workflow'}]}}});const out=await h.run('n8n_list_workflows',{});expect(out).toMatchObject({ok:false,error:'tenant_changed'});expect(JSON.stringify(out)).not.toContain('Private workflow')});
 it('does not retry uncertain mutation or expose exception',async()=>{const h=harness({callError:new Error('canary-access raw private response')});const out=await h.run();expect(out).toEqual({ok:false,error:'outcome_unknown',retry_safe:false});expect(h.call).toHaveBeenCalledTimes(1);expect(JSON.stringify(out)).not.toContain('canary')});
 it('projects 203 total without inventing complete inventory or dropping non-MCP rows',async()=>{const h=harness({response:{structuredContent:{count:203,data:[{id:'wf1',name:'Workflow',availableInMCP:false,nodes:[{parameters:'canary-customer'}]}]}}});const out=await h.run('n8n_list_workflows',{});expect(out).toMatchObject({total_count:203,inventory_complete:false,workflows:[{id:'wf1',name:'Workflow',availableInMCP:false}]});expect(JSON.stringify(out)).not.toContain('canary')});
 it('forces execution history metadata only',async()=>{const h=harness({response:{structuredContent:{execution:{id:'e1',workflowId:'wf1',status:'success',data:'canary-data'}}}});const out=await h.run('n8n_execution_get',{workflow_id:'wf1',execution_id:'e1'});expect(h.call).toHaveBeenCalledWith('get_workflow_execution',{workflowId:'wf1',executionId:'e1',includeData:false});expect(out).toMatchObject({execution:{id:'e1',status:'success'},delivered:null});expect(JSON.stringify(out)).not.toContain('canary')});
 it('redacts credentials and node configuration from workflow projection',async()=>{const h=harness({response:{structuredContent:{workflow:{id:'wf1',name:'canary-access',nodes:[{id:'node1',name:'Node',type:'n8n-nodes-base.httpRequest',parameters:{authorization:'canary-header'},credentials:{id:'credential'}}]}}}});const out=await h.run('n8n_get_workflow',{workflow_id:'wf1'});expect(out).toMatchObject({workflow:{id:'wf1'},nodes:[{id:'node1',name:'Node',type:'n8n-nodes-base.httpRequest'}],configuration_redacted:true});expect(JSON.stringify(out)).not.toMatch(/canary|credential/)});
 it('rejects permanent deletion without outbound calls',async()=>{const h=harness();expect(await h.run('n8n_delete_workflow',{workflow_id:'wf1'})).toMatchObject({error:'unsupported_operation'});expect(h.admin.rpc).not.toHaveBeenCalled()});
 it('refreshes exact existing scopes and commits before call',async()=>{const h=harness({expired:true});expect(await h.run()).toMatchObject({ok:true});expect(h.admin.rpc.mock.calls.map(c=>c[1]._operation??c[0])).toEqual(['acquire','rotate','check','check','record_capability_run','release']);expect(JSON.stringify(await h.run())).not.toContain('canary')});
 it('revokes unsafe rotated scope expansion and never calls a workflow',async()=>{const h=harness({expired:true,refreshScopes:['workflow:read','workflow:write','agent:write']});expect(await h.run()).toMatchObject({error:'provider_scope_refused'});expect(h.revoke).toHaveBeenCalledOnce();expect(h.call).not.toHaveBeenCalled()});
 it('requires explicit execution intent and refuses old REST payload silently reinterpreted as inputs',async()=>{const h=harness();expect(await h.run('n8n_run_workflow',{workflow_id:'wf1'})).toMatchObject({error:'invalid_arguments'});expect(await h.run('n8n_run_workflow',{workflow_id:'wf1',execution_mode:'production',payload:{}})).toMatchObject({error:'invalid_arguments'});expect(h.call).not.toHaveBeenCalled()});
 it.each(['n8n_create_workflow','n8n_activate_workflow','n8n_update_workflow','n8n_run_workflow'])('does not invent success from empty provider receipt for %s',async tool=>{const h=harness({response:{structuredContent:{}}});const args=tool==='n8n_create_workflow'?{code:'code',versionName:'v',versionDescription:'d'}:tool==='n8n_update_workflow'?{workflow_id:'wf1',operations:[{type:'removeNode',nodeName:'n'}],versionName:'v',versionDescription:'d'}:tool==='n8n_run_workflow'?{workflow_id:'wf1',execution_mode:'production'}:{workflow_id:'wf1',version_id:'v1'};expect(await h.run(tool,args)).toMatchObject({ok:false,error:'outcome_unknown',retry_safe:false})});
 it('reports n8n started receipt without inventing completion or delivery',async()=>{const h=harness({response:{structuredContent:{status:'started',executionId:'e1'}}});expect(await h.run('n8n_run_workflow',{workflow_id:'wf1',execution_mode:'production'})).toMatchObject({ok:true,started:true,executionId:'e1',execution_completed:null,delivered:null})});
 // ── SCR-2026-09-05: PAIGE'S WORK IS ON THE RAIL, AND ONLY THE PART THAT IS HERS ──
 //
 // Before this, a workflow could be executed against a live n8n instance and the only
 // trace was a `paige_audit_log` row that no surface in the product reads. These four
 // assert the record exists, names itself, tells the truth about an uncertain result,
 // and does not fire for the things that are not acts.
 const railCall=(h:any)=>h.admin.rpc.mock.calls.find((c:any)=>c[0]==='record_capability_run')?.[1];
 it('records the capability it ran, against the tenant and actor the server resolved',async()=>{const h=harness({response:{structuredContent:{status:'started',executionId:'e1'}}});expect(await h.run('n8n_run_workflow',{workflow_id:'wf1',execution_mode:'production'})).toMatchObject({ok:true});expect(railCall(h)).toMatchObject({_tenant_id:'tenant',_actor_id:'owner',_capability_key:'n8n_run_workflow',_outcome:'capability_succeeded'});expect(railCall(h)._run_id).toMatch(/^[0-9a-f-]{36}$/i)});
 it('records an uncertain write as UNKNOWN rather than as a failure',async()=>{const h=harness({callError:new Error('dropped')});expect(await h.run()).toMatchObject({error:'outcome_unknown'});expect(railCall(h)).toMatchObject({_outcome:'capability_outcome_unknown'})});
 it('does not put reads on the Rail',async()=>{const h=harness({response:{structuredContent:{count:1,data:[{id:'wf1',name:'W'}]}}});await h.run('n8n_list_workflows',{});expect(railCall(h)).toBeUndefined()});
 // The peer-gate found this one: a scope refusal happens AFTER the fence, so it must record —
 // and it was the one post-fence refusal that returned without doing so, which made
 // RAIL_OUTCOME.authorization_needed dead code. Two refusals of the same act class, one of them
 // findable afterwards and one not.
 it('records a post-fence scope refusal, so it is findable afterwards',async()=>{const h=harness({scope:['workflow:read','workflow:write']});expect(await h.run('n8n_run_workflow',{workflow_id:'wf1',execution_mode:'production'})).toMatchObject({error:'authorization_needed',required_scope:'workflow:execute'});expect(railCall(h)).toMatchObject({_capability_key:'n8n_run_workflow',_outcome:'capability_refused'});expect(h.call).not.toHaveBeenCalled()});
 it('records nothing at all before the tenant/session fence has passed',async()=>{const h=harness({rpcFail:'acquire'});await h.run();expect(railCall(h)).toBeUndefined()});
 it('a Rail write that fails never turns a completed run into a failure',async()=>{const h=harness();h.admin.rpc.mockImplementation(async(name:string,args:any)=>name==='record_capability_run'?{data:null,error:{message:'rail down'}}:({data:args._operation==='acquire'?{lease:'lease',generation:'generation',server_url:'https://n8n.example/mcp-server/http',access_token:'a',refresh_token:'r',client_secret:'c',expires_at:'2099-01-01',issuer:'https://n8n.example',client_id:'client',oauth_scopes:['workflow:read','workflow:write','workflow:execute','execution:read']}:{ok:true},error:null}));expect(await h.run()).toMatchObject({ok:true})});
 it('requires true publish receipt',async()=>{const h=harness({response:{structuredContent:{success:false,workflowId:'wf1',activeVersionId:null}}});expect(await h.run()).toMatchObject({ok:false,error:'outcome_unknown'})});
 it('offers bounded SDK reference as untrusted documentation and rejects token echoes',async()=>{const h=harness({response:{structuredContent:{reference:'workflow().add(node())'}}});expect(await h.run('n8n_get_sdk_reference',{})).toMatchObject({ok:true,reference_is_untrusted:true});const bad=harness({response:{structuredContent:{reference:'canary-access'}}});expect(await bad.run('n8n_get_sdk_reference',{})).toMatchObject({ok:false,error:'provider_response_invalid'})});
 it('maps SDK creation without publishing or executing',async()=>{const h=harness();const args={code:'export default workflow;',versionName:'Initial draft',versionDescription:'Approved draft'};expect(await h.run('n8n_create_workflow',args)).toMatchObject({ok:true,workflowId:'wf1',executed:false});expect(h.call).toHaveBeenCalledExactlyOnceWith('create_workflow_from_code',args)});
});

it('registers every exported n8n tool with exact canonical governance',()=>{
 const tools=harness().output.N8N_MANAGEMENT_TOOLS;
 const capabilities:readonly SpineCapability[]=PAIGE_SPINE_CAPABILITIES;
 const entries=capabilities.filter(c=>c.key.startsWith('integrations.n8n_')&&c.action?.chatTool);
 expect(entries.map(c=>c.action?.chatTool).sort()).toEqual(tools.map((t:any)=>t.function.name).sort());
 expect(entries.some(c=>c.action?.chatTool==='n8n_delete_workflow')).toBe(false);
 for(const entry of entries){expect(entry.action!.executor).toBe('edge.paige-ai-chat');if(entry.action!.classification==='external_effect'){expect(classifyAction(entry.action!.chatTool!)).toBe('high');expect(entry.action!.approvalAuthority).toBe('chat-canonical')}else{expect(entry.action!.riskPolicyKey).toBe('read_only');expect(entry.action!.approvalAuthority).toBe('none')}}
 expect(validateSpineRegistry(PAIGE_SPINE_CAPABILITIES)).toEqual([]);
});
it.each(['edge.other','edge.paige-ai-chat.evil','client.n8n'])('rejects arbitrary executor %s',executor=>{
 const entry=PAIGE_SPINE_CAPABILITIES.find(c=>c.key==='integrations.n8n_create_workflow')!;
 expect(validateSpineRegistry([{...entry,action:{...entry.action!,executor}}])).not.toEqual([]);
});
it('rejects unknown, missing or mismatched tool and downgraded edge authority',()=>{
 const entry=PAIGE_SPINE_CAPABILITIES.find(c=>c.key==='integrations.n8n_create_workflow')!;
 for(const change of [{chatTool:undefined},{chatTool:'n8n_run_workflow'},{chatTool:'unregistered'}, {classification:'read',riskPolicyKey:'read_only',approvalAuthority:'none'}])expect(validateSpineRegistry([{...entry,action:{...entry.action!,...change}}] as any)).not.toEqual([]);
});
it('requires a source-backed explicit publish version before any provider call',async()=>{const h=harness();expect(await h.run('n8n_activate_workflow',{workflow_id:'wf1'})).toMatchObject({error:'invalid_arguments'});expect(h.call).not.toHaveBeenCalled()});
it.each([{workflowId:'other',success:true,activeVersionId:'v1'},{workflowId:'wf1',success:true,activeVersionId:'other'}])('refuses mismatched publish identity/version %#',async receipt=>{const h=harness({response:{structuredContent:receipt}});expect(await h.run()).toMatchObject({error:'outcome_unknown',retry_safe:false})});
it.each(['n8n_update_workflow','n8n_deactivate_workflow','n8n_archive_workflow'])('refuses mismatched %s workflow receipt',async tool=>{const h=harness({response:{structuredContent:{workflowId:'other',success:true,archived:true}}});const args=tool==='n8n_update_workflow'?{workflow_id:'wf1',operations:[{type:'removeNode',nodeName:'x'}],versionName:'v',versionDescription:'d'}:{workflow_id:'wf1'};expect(await h.run(tool,args)).toMatchObject({error:'outcome_unknown'})});
it('refuses a different workflow or execution in read evidence',async()=>{for(const [tool,args,response]of [['n8n_get_workflow',{workflow_id:'wf1'},{workflow:{id:'other',name:'Private'}}],['n8n_execution_get',{workflow_id:'wf1',execution_id:'e1'},{execution:{id:'e1',workflowId:'other',status:'success'}}],['n8n_execution_get',{workflow_id:'wf1',execution_id:'e1'},{execution:{id:'other',workflowId:'wf1',status:'success'}}],['n8n_get_executions',{workflow_id:'wf1'},{data:[{id:'e1',workflowId:'other'}],count:1}]]as const){const h=harness({response:{structuredContent:response}});expect(await h.run(tool,args)).toMatchObject({ok:false,error:'provider_response_invalid'})}});

it('records freshness only after valid projected provider evidence',async()=>{const good=harness();await good.run();expect(good.admin.rpc.mock.calls.filter(c=>c[1]._operation==='check').at(-1)?.[1]._input).toMatchObject({record_success:true});const bad=harness({response:{structuredContent:{}}});await bad.run();expect(bad.admin.rpc.mock.calls.some(c=>c[1]._input?.record_success===true)).toBe(false)});
