-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260708223948 (grant_calendars_service_role)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260708223948 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- The public booking engine runs as service_role. service_role has BYPASSRLS
-- but that does NOT bypass table-level GRANTs — and these tables (created via
-- migration) never got the service_role grant, so the booking function hit
-- "permission denied for table calendars" and every booking page showed
-- "unavailable". Grant the service role full DML on the calendar tables.
GRANT SELECT, INSERT, UPDATE, DELETE ON public.calendars TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.calendar_hosts TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.calendar_groups TO service_role;
