-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260709181825 (create_class_booking_contact_id)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260709181825 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

DROP FUNCTION IF EXISTS public.create_class_booking(uuid, uuid, uuid, timestamptz, timestamptz, text, integer, text, text, text, text, text, text, text, jsonb, text);

CREATE OR REPLACE FUNCTION public.create_class_booking(
  _calendar_id uuid, _host_user_id uuid, _tenant_id uuid,
  _start_at timestamptz, _end_at timestamptz, _timezone text, _capacity integer,
  _title text, _guest_name text, _guest_email text, _guest_phone text, _notes text,
  _location_type text, _location_value text, _intake_answers jsonb, _source text,
  _contact_id uuid DEFAULT NULL
) RETURNS public.internal_bookings
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $$
DECLARE
  _session public.internal_bookings;
  _seat public.internal_bookings;
  _booked integer;
  _attempts integer := 0;
BEGIN
  LOOP
    SELECT * INTO _session FROM public.internal_bookings
     WHERE calendar_id = _calendar_id AND start_at = _start_at
       AND booking_kind = 'class_session' AND status <> 'cancelled'
     FOR UPDATE;
    EXIT WHEN FOUND;

    _attempts := _attempts + 1;
    IF _attempts > 5 THEN
      RAISE EXCLUSION_VIOLATION USING MESSAGE = 'That time is no longer available.';
    END IF;

    BEGIN
      INSERT INTO public.internal_bookings
        (tenant_id, host_user_id, calendar_id, booking_kind, capacity,
         title, start_at, end_at, timezone, status, source)
      VALUES (_tenant_id, _host_user_id, _calendar_id, 'class_session', _capacity,
              _title, _start_at, _end_at, _timezone, 'scheduled', _source)
      RETURNING * INTO _session;
      EXIT;
    EXCEPTION WHEN unique_violation OR exclusion_violation THEN
      CONTINUE;
    END;
  END LOOP;

  SELECT count(*) INTO _booked FROM public.internal_bookings
   WHERE class_session_id = _session.id AND status <> 'cancelled';
  IF _booked >= _session.capacity THEN
    RAISE EXCEPTION 'sold_out';
  END IF;

  INSERT INTO public.internal_bookings
    (tenant_id, host_user_id, calendar_id, booking_kind, class_session_id, contact_id,
     title, start_at, end_at, timezone, status, source,
     guest_name, guest_email, guest_phone, notes, location_type, location_value, intake_answers)
  VALUES (_tenant_id, _host_user_id, _calendar_id, 'class_seat', _session.id, _contact_id,
          _title, _start_at, _end_at, _timezone, 'scheduled', _source,
          _guest_name, _guest_email, _guest_phone, _notes, _location_type, _location_value, _intake_answers)
  RETURNING * INTO _seat;
  RETURN _seat;
END;
$$;

REVOKE ALL ON FUNCTION public.create_class_booking(uuid, uuid, uuid, timestamptz, timestamptz, text, integer, text, text, text, text, text, text, text, jsonb, text, uuid) FROM public;
GRANT EXECUTE ON FUNCTION public.create_class_booking(uuid, uuid, uuid, timestamptz, timestamptz, text, integer, text, text, text, text, text, text, text, jsonb, text, uuid) TO service_role;

