-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260713034248 (agency_login_default)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260713034248 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS agency_login_default text NOT NULL DEFAULT 'agency'
    CHECK (agency_login_default IN ('agency', 'last_account'));

CREATE OR REPLACE FUNCTION public.set_agency_login_default(_pref text)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF _pref IS NULL OR _pref NOT IN ('agency', 'last_account') THEN
    RAISE EXCEPTION 'invalid_agency_login_default' USING ERRCODE = '22023';
  END IF;

  UPDATE public.profiles
     SET agency_login_default = _pref
   WHERE user_id = auth.uid();

  RETURN jsonb_build_object('agency_login_default', _pref);
END;
$$;

REVOKE ALL ON FUNCTION public.set_agency_login_default(text) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.set_agency_login_default(text) TO authenticated;
