-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260710022523 (tenant_skills_toggle)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260710022523 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Paige "skills" (marketplace add-ons) — a tenant layers a capability skill on
-- top of WHATEVER coach-type skin they authored, without swapping their persona.
-- Stored as features.enabled_skills (jsonb array of slugs). Funding is the first
-- skill; this generalizes the earlier boolean gate (design lead's #1 rec) so a
-- second skill doesn't need new plumbing (§8 marketplace seam).
CREATE OR REPLACE FUNCTION public.set_tenant_skill(_tenant_id uuid, _skill text, _enabled boolean)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE _skills jsonb;
BEGIN
  IF NOT (public.is_platform_owner() OR public.is_tenant_admin(_tenant_id)) THEN
    RAISE EXCEPTION 'not authorized to change this tenant''s skills';
  END IF;
  IF _skill IS NULL OR _skill !~ '^[a-z0-9_]+$' THEN
    RAISE EXCEPTION 'invalid skill slug';
  END IF;

  -- current set, minus this skill (so we can re-add cleanly / de-dupe)
  SELECT COALESCE(
           (SELECT jsonb_agg(DISTINCT v)
            FROM jsonb_array_elements_text(COALESCE(t.features->'enabled_skills', '[]'::jsonb)) AS v
            WHERE v <> _skill),
           '[]'::jsonb)
  INTO _skills
  FROM public.tenants t WHERE t.id = _tenant_id;

  IF _enabled THEN
    _skills := _skills || to_jsonb(_skill);
  END IF;

  UPDATE public.tenants
  SET features = COALESCE(features, '{}'::jsonb) || jsonb_build_object('enabled_skills', _skills)
  WHERE id = _tenant_id;

  RETURN _skills;
END $$;
REVOKE EXECUTE ON FUNCTION public.set_tenant_skill(uuid, text, boolean) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_tenant_skill(uuid, text, boolean) TO authenticated;

-- Fold enabled_skills into the funding gate the AI chat reads. Keeps every prior
-- condition (preset slug / legacy flag) for back-compat; adds the skill-array path
-- so funding can be layered on a non-funding skin.
CREATE OR REPLACE FUNCTION public.get_paige_persona_context()
RETURNS TABLE (
  tenant_id uuid,
  tenant_name text,
  playbook_config jsonb,
  playbook_slug text,
  funding_enabled boolean
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  _tid uuid;
BEGIN
  SELECT c.tenant_id INTO _tid
  FROM public.clients c
  WHERE c.linked_user_id = auth.uid()
  ORDER BY c.created_at ASC
  LIMIT 1;

  IF _tid IS NULL THEN
    SELECT p.active_tenant_id INTO _tid FROM public.profiles p WHERE p.id = auth.uid();
  END IF;
  IF _tid IS NULL THEN
    SELECT m.tenant_id INTO _tid FROM public.tenant_members m WHERE m.user_id = auth.uid() LIMIT 1;
  END IF;
  IF _tid IS NULL THEN
    SELECT t.id INTO _tid FROM public.tenants t WHERE t.owner_user_id = auth.uid() LIMIT 1;
  END IF;

  IF _tid IS NULL THEN
    RETURN;
  END IF;

  RETURN QUERY
  SELECT
    t.id,
    t.name,
    (t.features -> 'playbook_config'),
    NULLIF(t.features ->> 'playbook', ''),
    COALESCE(
      (t.features ->> 'paige_funding_skill') = 'true'
        OR (t.features ->> 'playbook') = 'funding'
        OR (t.features -> 'playbook_config' ->> 'slug') = 'funding'
        OR (t.features -> 'enabled_skills') @> '["funding"]'::jsonb,
      false
    )
  FROM public.tenants t
  WHERE t.id = _tid;
END $$;
REVOKE EXECUTE ON FUNCTION public.get_paige_persona_context() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_paige_persona_context() TO authenticated;
