-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260714180619 (marketplace_bundle_refcount_3_helpers)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260714180619 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Wave 1 chunk 3/5: internal helpers (skill cross-ref guard, active-bundle-holds, teardown+cascade)
CREATE OR REPLACE FUNCTION public._marketplace_skill_referenced_elsewhere(
  _tenant_id uuid, _slug text, _exclude_install uuid
) RETURNS boolean
 LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.marketplace_installs mi
     WHERE mi.tenant_id = _tenant_id
       AND mi.status = 'active'
       AND mi.id <> _exclude_install
       AND (COALESCE(mi.seeded_refs->'skill_slugs','[]'::jsonb) ? _slug)
  );
$function$;
REVOKE ALL ON FUNCTION public._marketplace_skill_referenced_elsewhere(uuid, text, uuid) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public._marketplace_active_bundle_holds(_child_install uuid)
 RETURNS integer
 LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$
  SELECT COUNT(*)::int
    FROM public.marketplace_install_bundle_links l
    JOIN public.marketplace_installs bi
      ON bi.id = l.bundle_install_id AND bi.status = 'active'
   WHERE l.child_install_id = _child_install;
$function$;
REVOKE ALL ON FUNCTION public._marketplace_active_bundle_holds(uuid) FROM PUBLIC;

CREATE OR REPLACE FUNCTION public._marketplace_teardown_install(
  _tenant_id uuid, _install_id uuid
) RETURNS jsonb
 LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
DECLARE
  _inst         public.marketplace_installs%ROWTYPE;
  _slug         text;
  _doc          uuid;
  _skills_off   text[] := '{}';
  _docs_removed integer := 0;
  _link         record;
  _child        public.marketplace_installs%ROWTYPE;
  _remaining    integer;
  _children     jsonb := '[]'::jsonb;
BEGIN
  SELECT * INTO _inst FROM public.marketplace_installs WHERE id = _install_id FOR UPDATE;
  IF NOT FOUND OR _inst.status = 'uninstalled' THEN
    RETURN jsonb_build_object('install_id', _install_id, 'torn_down', false);
  END IF;

  UPDATE public.marketplace_installs
     SET status = 'uninstalled', held_directly = false, uninstalled_at = now()
   WHERE id = _install_id;

  FOR _slug IN SELECT jsonb_array_elements_text(COALESCE(_inst.seeded_refs->'skill_slugs','[]'::jsonb))
  LOOP
    IF NOT public._marketplace_skill_referenced_elsewhere(_tenant_id, _slug, _install_id) THEN
      PERFORM public.set_tenant_skill(_tenant_id, _slug, false);
      _skills_off := array_append(_skills_off, _slug);
    END IF;
  END LOOP;

  FOR _doc IN SELECT (jsonb_array_elements_text(COALESCE(_inst.seeded_refs->'kb_doc_ids','[]'::jsonb)))::uuid
  LOOP
    DELETE FROM public.tenant_knowledge_docs WHERE id = _doc AND tenant_id = _tenant_id;
    IF FOUND THEN _docs_removed := _docs_removed + 1; END IF;
  END LOOP;

  INSERT INTO public.marketplace_install_ledger
    (install_id, item_id, vendor_id, tenant_id, event_type, gross_cents, take_rate_bps, platform_fee_cents, vendor_net_cents)
  SELECT _inst.id, _inst.item_id, i.vendor_id, _tenant_id, 'uninstall', 0, 0, 0, 0
    FROM public.marketplace_items i WHERE i.id = _inst.item_id;
  UPDATE public.marketplace_items
     SET install_count = GREATEST(install_count - 1, 0) WHERE id = _inst.item_id;

  FOR _link IN SELECT * FROM public.marketplace_install_bundle_links
                WHERE bundle_install_id = _install_id
  LOOP
    DELETE FROM public.marketplace_install_bundle_links
     WHERE bundle_install_id = _install_id AND child_install_id = _link.child_install_id;

    SELECT * INTO _child FROM public.marketplace_installs WHERE id = _link.child_install_id;
    IF FOUND AND _child.status = 'active' THEN
      _remaining := (CASE WHEN _child.held_directly THEN 1 ELSE 0 END)
                    + public._marketplace_active_bundle_holds(_child.id);
      IF _remaining = 0 THEN
        _children := _children || jsonb_build_array(
          public._marketplace_teardown_install(_tenant_id, _child.id));
      ELSE
        _children := _children || jsonb_build_array(jsonb_build_object(
          'install_id', _child.id, 'item_slug', _link.child_item_slug,
          'torn_down', false, 'retained_holds', _remaining));
      END IF;
    END IF;
  END LOOP;

  RETURN jsonb_build_object(
    'install_id', _inst.id, 'item_id', _inst.item_id, 'torn_down', true,
    'skills_disabled', to_jsonb(_skills_off), 'kb_docs_removed', _docs_removed,
    'children', _children);
END $function$;
REVOKE ALL ON FUNCTION public._marketplace_teardown_install(uuid, uuid) FROM PUBLIC;
