-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712223000 (agency_mcp_enter_exit)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712223000 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================


CREATE OR REPLACE FUNCTION public.actor_manages_any_agency(_actor uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.tenant_members m
    JOIN public.tenants t ON t.id = m.tenant_id
    WHERE m.user_id = _actor
      AND m.status = 'active'
      AND m.role IN ('owner', 'admin')
      AND t.account_type IN ('agency', 'enterprise')
  );
$$;

CREATE OR REPLACE FUNCTION public.actor_primary_agency(_actor uuid)
RETURNS uuid
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT t.id
  FROM public.tenant_members m
  JOIN public.tenants t ON t.id = m.tenant_id
  WHERE m.user_id = _actor
    AND m.status = 'active'
    AND m.role IN ('owner', 'admin')
    AND t.account_type IN ('agency', 'enterprise')
  ORDER BY m.joined_at ASC NULLS LAST, t.created_at ASC
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.agency_enter_subaccount(_child uuid, _actor uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.agency_can_manage_child(_child, _actor) THEN
    RAISE EXCEPTION 'agency_scope_forbidden' USING ERRCODE = '42501';
  END IF;
  INSERT INTO public.tenant_members (tenant_id, user_id, role, status, joined_at)
  VALUES (_child, _actor, 'admin', 'active', now())
  ON CONFLICT (tenant_id, user_id) DO NOTHING;
  UPDATE public.profiles SET active_tenant_id = _child WHERE user_id = _actor;
END;
$$;

CREATE OR REPLACE FUNCTION public.agency_exit_subaccount(_actor uuid)
RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  _agency uuid;
BEGIN
  SELECT public.actor_primary_agency(_actor) INTO _agency;
  IF _agency IS NULL THEN
    RAISE EXCEPTION 'no_agency_home' USING ERRCODE = '42501';
  END IF;
  UPDATE public.profiles SET active_tenant_id = _agency WHERE user_id = _actor;
  RETURN _agency;
END;
$$;

REVOKE ALL ON FUNCTION public.actor_manages_any_agency(uuid)     FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.actor_primary_agency(uuid)         FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.agency_enter_subaccount(uuid,uuid) FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.agency_exit_subaccount(uuid)       FROM public, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.actor_manages_any_agency(uuid)     TO service_role;
GRANT EXECUTE ON FUNCTION public.actor_primary_agency(uuid)         TO service_role;
GRANT EXECUTE ON FUNCTION public.agency_enter_subaccount(uuid,uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.agency_exit_subaccount(uuid)       TO service_role;

