-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260713140004 (growth_authoring_seam)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260713140004 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Growth authoring seam (§10) — tenant-scoped RPCs for the vibe-coding studio.
ALTER TABLE public.growth_pages
  ADD COLUMN IF NOT EXISTS draft_blocks_json jsonb,
  ADD COLUMN IF NOT EXISTS draft_theme_json  jsonb,
  ADD COLUMN IF NOT EXISTS draft_seo_json    jsonb;

-- Column-scoped anon read (§9): omit draft_* so the public can't read unpublished edits.
REVOKE SELECT ON public.growth_pages FROM anon;
GRANT SELECT (
  id, tenant_id, slug, title, status, template_key,
  theme_json, blocks_json, seo_json, og_image_url,
  published_at, created_by, created_at, updated_at
) ON public.growth_pages TO anon;

CREATE OR REPLACE FUNCTION public.growth_page_upsert(
  p_tenant_id  uuid, p_slug text, p_title text, p_blocks_json jsonb,
  p_theme_json jsonb DEFAULT NULL, p_seo_json jsonb DEFAULT NULL, p_id uuid DEFAULT NULL
) RETURNS public.growth_pages
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  _caller uuid := auth.uid();
  _tenant uuid;
  _slug   text := NULLIF(btrim(p_slug), '');
  _block  jsonb;
  _btype  text;
  _row    public.growth_pages;
BEGIN
  IF _caller IS NOT NULL THEN
    IF NOT public.has_any_role(_caller, ARRAY['admin','super_admin','coach']) THEN
      RAISE EXCEPTION 'GROWTH_FORBIDDEN: admin, coach or super_admin required' USING ERRCODE = '42501';
    END IF;
    _tenant := public.current_user_tenant_id();
  ELSE
    _tenant := p_tenant_id;
  END IF;
  IF _tenant IS NULL THEN RAISE EXCEPTION 'GROWTH_NO_TENANT: a tenant context is required' USING ERRCODE = '22023'; END IF;
  IF _slug IS NULL THEN RAISE EXCEPTION 'GROWTH_INVALID_SLUG: a non-empty slug is required' USING ERRCODE = '22023'; END IF;
  IF p_blocks_json IS NULL OR jsonb_typeof(p_blocks_json) <> 'array' THEN
    RAISE EXCEPTION 'GROWTH_INVALID_BLOCKS: blocks_json must be a JSON array' USING ERRCODE = '22023';
  END IF;
  FOR _block IN SELECT value FROM jsonb_array_elements(p_blocks_json) LOOP
    IF jsonb_typeof(_block) <> 'object' THEN
      RAISE EXCEPTION 'GROWTH_INVALID_BLOCKS: each block must be an object' USING ERRCODE = '22023';
    END IF;
    _btype := _block->>'type';
    IF _btype IS NULL OR _btype NOT IN ('hero','phase_cards','feature_grid','cta','rich_text','embedded_form') THEN
      RAISE EXCEPTION 'GROWTH_INVALID_BLOCKS: unknown block type %', COALESCE(_btype, '(null)') USING ERRCODE = '22023';
    END IF;
    IF _btype = 'rich_text' AND char_length(COALESCE(_block->>'html', '')) > 20000 THEN
      RAISE EXCEPTION 'GROWTH_INVALID_BLOCKS: rich_text html exceeds 20000 characters' USING ERRCODE = '22023';
    END IF;
  END LOOP;
  IF p_id IS NOT NULL THEN
    UPDATE public.growth_pages SET
      slug = _slug, title = COALESCE(NULLIF(btrim(p_title), ''), title),
      draft_blocks_json = p_blocks_json,
      draft_theme_json  = COALESCE(p_theme_json, draft_theme_json),
      draft_seo_json    = COALESCE(p_seo_json, draft_seo_json)
    WHERE id = p_id AND tenant_id = _tenant RETURNING * INTO _row;
    IF _row.id IS NULL THEN RAISE EXCEPTION 'GROWTH_NOT_FOUND: page not found in this tenant' USING ERRCODE = 'P0002'; END IF;
  ELSE
    INSERT INTO public.growth_pages (tenant_id, slug, title, status, created_by, draft_blocks_json, draft_theme_json, draft_seo_json)
    VALUES (_tenant, _slug, COALESCE(NULLIF(btrim(p_title), ''), 'Untitled'), 'draft', _caller, p_blocks_json, p_theme_json, p_seo_json)
    ON CONFLICT (tenant_id, slug) DO UPDATE SET
      title = COALESCE(NULLIF(btrim(EXCLUDED.title), ''), public.growth_pages.title),
      draft_blocks_json = EXCLUDED.draft_blocks_json,
      draft_theme_json  = COALESCE(EXCLUDED.draft_theme_json, public.growth_pages.draft_theme_json),
      draft_seo_json    = COALESCE(EXCLUDED.draft_seo_json, public.growth_pages.draft_seo_json)
    RETURNING * INTO _row;
  END IF;
  INSERT INTO public.audit_logs (user_id, entity, action, entity_id, data)
  VALUES (_caller, 'growth_pages', 'growth_page_upsert', _row.id,
          jsonb_build_object('tenant_id', _tenant, 'slug', _row.slug, 'blocks', jsonb_array_length(p_blocks_json)));
  RETURN _row;
END; $$;

CREATE OR REPLACE FUNCTION public.growth_page_publish(p_tenant_id uuid, p_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  _caller uuid := auth.uid();
  _tenant uuid;
  _row    public.growth_pages;
  _tenant_slug text;
BEGIN
  IF _caller IS NOT NULL THEN
    IF NOT public.has_any_role(_caller, ARRAY['admin','super_admin','coach']) THEN
      RAISE EXCEPTION 'GROWTH_FORBIDDEN: admin, coach or super_admin required' USING ERRCODE = '42501';
    END IF;
    _tenant := public.current_user_tenant_id();
  ELSE
    _tenant := p_tenant_id;
  END IF;
  IF _tenant IS NULL THEN RAISE EXCEPTION 'GROWTH_NO_TENANT: a tenant context is required' USING ERRCODE = '22023'; END IF;
  SELECT * INTO _row FROM public.growth_pages WHERE id = p_id AND tenant_id = _tenant;
  IF _row.id IS NULL THEN RAISE EXCEPTION 'GROWTH_NOT_FOUND: page not found in this tenant' USING ERRCODE = 'P0002'; END IF;
  IF _row.draft_blocks_json IS NULL OR jsonb_typeof(_row.draft_blocks_json) <> 'array' THEN
    RAISE EXCEPTION 'GROWTH_NO_DRAFT: nothing to publish — save draft blocks first' USING ERRCODE = '22023';
  END IF;
  IF _row.draft_blocks_json::text ~ '\[[A-Za-z0-9]*_[A-Za-z0-9_]*\]'
     OR _row.draft_blocks_json::text ~* '\[[^\]]*\y(add|paste|insert|enter|fill|tbd|placeholder|replace|example|your)\y[^\]]*\]'
     OR COALESCE(_row.draft_seo_json::text, '') ~ '\[[A-Za-z0-9]*_[A-Za-z0-9_]*\]'
     OR COALESCE(_row.draft_seo_json::text, '') ~* '\[[^\]]*\y(add|paste|insert|enter|fill|tbd|placeholder|replace|example|your)\y[^\]]*\]' THEN
    RAISE EXCEPTION 'GROWTH_UNRESOLVED_PLACEHOLDER: page has unresolved editable placeholders (e.g. [ADD_WEBINAR_DATE]) — fill them before publishing' USING ERRCODE = '22023';
  END IF;
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements(_row.draft_blocks_json) AS b
    WHERE b->>'type' = 'embedded_form'
      AND NOT EXISTS (SELECT 1 FROM public.growth_forms f WHERE f.tenant_id = _tenant AND f.slug = b->>'form_slug' AND f.status = 'active')
  ) THEN
    RAISE EXCEPTION 'GROWTH_FORM_MISSING: a signup form on this page does not exist yet — re-save the page to author it before publishing' USING ERRCODE = '22023';
  END IF;
  UPDATE public.growth_pages SET
    blocks_json = draft_blocks_json,
    theme_json  = COALESCE(draft_theme_json, theme_json),
    seo_json    = COALESCE(draft_seo_json, seo_json),
    status = 'published', published_at = now()
  WHERE id = _row.id AND tenant_id = _tenant RETURNING * INTO _row;
  SELECT slug INTO _tenant_slug FROM public.tenants WHERE id = _tenant;
  IF _tenant_slug IS NULL OR btrim(_tenant_slug) = '' THEN
    RAISE EXCEPTION 'GROWTH_NO_TENANT_SLUG: this workspace has no public slug — set one before publishing' USING ERRCODE = '22023';
  END IF;
  INSERT INTO public.audit_logs (user_id, entity, action, entity_id, data)
  VALUES (_caller, 'growth_pages', 'growth_page_publish', _row.id, jsonb_build_object('tenant_id', _tenant, 'slug', _row.slug));
  RETURN jsonb_build_object('id', _row.id, 'slug', _row.slug, 'tenant_slug', _tenant_slug,
    'status', _row.status, 'published_at', _row.published_at, 'url', '/p/' || _tenant_slug || '/' || _row.slug);
END; $$;

CREATE OR REPLACE FUNCTION public.growth_form_upsert(
  p_tenant_id uuid, p_slug text, p_name text, p_schema_json jsonb,
  p_success_action_json jsonb DEFAULT NULL, p_auto_create_contact boolean DEFAULT true,
  p_pipeline_id uuid DEFAULT NULL, p_stage_id uuid DEFAULT NULL, p_id uuid DEFAULT NULL
) RETURNS public.growth_forms
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  _caller uuid := auth.uid();
  _tenant uuid;
  _slug   text := NULLIF(btrim(p_slug), '');
  _row    public.growth_forms;
  _schema_ok boolean;
BEGIN
  IF _caller IS NOT NULL THEN
    IF NOT public.has_any_role(_caller, ARRAY['admin','super_admin','coach']) THEN
      RAISE EXCEPTION 'GROWTH_FORBIDDEN: admin, coach or super_admin required' USING ERRCODE = '42501';
    END IF;
    _tenant := public.current_user_tenant_id();
  ELSE
    _tenant := p_tenant_id;
  END IF;
  IF _tenant IS NULL THEN RAISE EXCEPTION 'GROWTH_NO_TENANT: a tenant context is required' USING ERRCODE = '22023'; END IF;
  IF _slug IS NULL THEN RAISE EXCEPTION 'GROWTH_INVALID_SLUG: a non-empty slug is required' USING ERRCODE = '22023'; END IF;
  _schema_ok := p_schema_json IS NOT NULL AND (
       (jsonb_typeof(p_schema_json) = 'object' AND jsonb_typeof(p_schema_json->'sections') = 'array')
    OR (jsonb_typeof(p_schema_json) = 'array'));
  IF NOT _schema_ok THEN
    RAISE EXCEPTION 'GROWTH_INVALID_SCHEMA: schema_json must be {sections:[…]} or an array of sections' USING ERRCODE = '22023';
  END IF;
  IF p_id IS NOT NULL THEN
    UPDATE public.growth_forms SET
      slug = _slug, name = COALESCE(NULLIF(btrim(p_name), ''), name),
      schema_json = p_schema_json,
      success_action_json = COALESCE(p_success_action_json, success_action_json),
      auto_create_contact = COALESCE(p_auto_create_contact, auto_create_contact),
      pipeline_id = COALESCE(p_pipeline_id, pipeline_id),
      stage_id = COALESCE(p_stage_id, stage_id)
    WHERE id = p_id AND tenant_id = _tenant RETURNING * INTO _row;
    IF _row.id IS NULL THEN RAISE EXCEPTION 'GROWTH_NOT_FOUND: form not found in this tenant' USING ERRCODE = 'P0002'; END IF;
  ELSE
    INSERT INTO public.growth_forms (tenant_id, slug, name, status, schema_json, success_action_json, auto_create_contact, pipeline_id, stage_id, created_by)
    VALUES (_tenant, _slug, COALESCE(NULLIF(btrim(p_name), ''), 'Lead form'), 'active', p_schema_json,
      COALESCE(p_success_action_json, '{"type":"thank_you","message":"Thanks — we''ll be in touch."}'::jsonb),
      COALESCE(p_auto_create_contact, true), p_pipeline_id, p_stage_id, _caller)
    ON CONFLICT (tenant_id, slug) DO UPDATE SET
      name = COALESCE(NULLIF(btrim(EXCLUDED.name), ''), public.growth_forms.name),
      schema_json = EXCLUDED.schema_json,
      success_action_json = COALESCE(EXCLUDED.success_action_json, public.growth_forms.success_action_json),
      auto_create_contact = EXCLUDED.auto_create_contact,
      pipeline_id = COALESCE(EXCLUDED.pipeline_id, public.growth_forms.pipeline_id),
      stage_id = COALESCE(EXCLUDED.stage_id, public.growth_forms.stage_id)
    RETURNING * INTO _row;
  END IF;
  INSERT INTO public.audit_logs (user_id, entity, action, entity_id, data)
  VALUES (_caller, 'growth_forms', 'growth_form_upsert', _row.id, jsonb_build_object('tenant_id', _tenant, 'slug', _row.slug));
  RETURN _row;
END; $$;

REVOKE ALL ON FUNCTION public.growth_page_upsert(uuid, text, text, jsonb, jsonb, jsonb, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.growth_page_upsert(uuid, text, text, jsonb, jsonb, jsonb, uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.growth_page_publish(uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.growth_page_publish(uuid, uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.growth_form_upsert(uuid, text, text, jsonb, jsonb, boolean, uuid, uuid, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.growth_form_upsert(uuid, text, text, jsonb, jsonb, boolean, uuid, uuid, uuid) TO authenticated, service_role;
