-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260709004618 (calendar_host_candidates_rpc)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260709004618 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Roster data source for the calendar builder's "Team / hosts" section.
-- profiles SELECT RLS is own-row-only, so a manager can't read teammates' names
-- directly. This SECURITY DEFINER function returns the candidate pool (tenant
-- members, or platform staff for operator/null-tenant calendars) plus the
-- current hosts with names — gated on can_manage_calendar so name exposure is
-- scoped exactly to people who already manage the calendar.
CREATE OR REPLACE FUNCTION public.list_calendar_host_candidates(_cal uuid)
RETURNS TABLE(user_id uuid, full_name text, is_host boolean, priority int)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE _tenant uuid;
BEGIN
  IF NOT public.can_manage_calendar(_cal) THEN
    RAISE EXCEPTION 'Not authorized to manage this calendar';
  END IF;
  SELECT c.tenant_id INTO _tenant FROM public.calendars c WHERE c.id = _cal;

  RETURN QUERY
  WITH hosts AS (
    SELECT ch.user_id AS uid, ch.priority AS prio
      FROM public.calendar_hosts ch WHERE ch.calendar_id = _cal
  ),
  pool AS (
    SELECT tm.user_id AS uid
      FROM public.tenant_members tm
     WHERE _tenant IS NOT NULL AND tm.tenant_id = _tenant
    UNION
    SELECT ur.user_id AS uid
      FROM public.user_roles ur
     WHERE _tenant IS NULL AND ur.role IN ('super_admin', 'platform_admin')
    UNION
    SELECT h.uid FROM hosts h            -- keep current hosts even if off the pool
  )
  SELECT p.uid,
         COALESCE(pr.full_name, (u.raw_user_meta_data->>'full_name'))::text,
         (h.uid IS NOT NULL),
         h.prio
    FROM pool p
    LEFT JOIN public.profiles pr ON pr.user_id = p.uid
    LEFT JOIN auth.users u ON u.id = p.uid
    LEFT JOIN hosts h ON h.uid = p.uid
   ORDER BY (h.uid IS NOT NULL) DESC, h.prio NULLS LAST, 2;
END;
$function$;

REVOKE ALL ON FUNCTION public.list_calendar_host_candidates(uuid) FROM public;
GRANT EXECUTE ON FUNCTION public.list_calendar_host_candidates(uuid) TO authenticated;
