-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260714180518 (marketplace_bundle_refcount_1_schema)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260714180518 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Wave 1 chunk 1/5: schema extension (held_directly + bundle-links table)
ALTER TABLE public.marketplace_installs
  ADD COLUMN IF NOT EXISTS held_directly boolean NOT NULL DEFAULT true;
COMMENT ON COLUMN public.marketplace_installs.held_directly IS
  'Reference-count model (Wave 1): TRUE when the tenant installed this item standalone (a direct hold). A child pulled in ONLY by a bundle fan-out is FALSE. Effects are reversed only when held_directly is false AND no active bundle link references this install. Existing rows backfill TRUE (all prior installs were direct).';

CREATE TABLE IF NOT EXISTS public.marketplace_install_bundle_links (
  bundle_install_id uuid NOT NULL REFERENCES public.marketplace_installs(id) ON DELETE CASCADE,
  child_install_id  uuid NOT NULL REFERENCES public.marketplace_installs(id) ON DELETE CASCADE,
  tenant_id         uuid NOT NULL,
  child_item_slug   text NOT NULL,
  linked_at         timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (bundle_install_id, child_install_id),
  CONSTRAINT mp_bundle_link_no_self CHECK (bundle_install_id <> child_install_id)
);
COMMENT ON TABLE public.marketplace_install_bundle_links IS
  'Wave 1 bundle fan-out edges: one row per (active bundle install -> child install it pulled in). refcount(child) = held_directly + COUNT(rows here whose bundle install is still active). Written only by the SECURITY DEFINER install/uninstall RPCs; readable (RLS) by the owning tenant + platform owner (section 10).';

CREATE INDEX IF NOT EXISTS idx_mp_bundle_links_child
  ON public.marketplace_install_bundle_links (child_install_id);
CREATE INDEX IF NOT EXISTS idx_mp_bundle_links_tenant
  ON public.marketplace_install_bundle_links (tenant_id);

ALTER TABLE public.marketplace_install_bundle_links ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS mp_bundle_links_read ON public.marketplace_install_bundle_links;
CREATE POLICY mp_bundle_links_read ON public.marketplace_install_bundle_links
  FOR SELECT TO authenticated
  USING (public.is_platform_owner() OR public.is_tenant_admin(tenant_id));
GRANT SELECT ON public.marketplace_install_bundle_links TO authenticated, service_role;
