-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712135910 (cron_token_to_vault)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712135910 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM vault.secrets WHERE name = 'cron_token') THEN
    PERFORM vault.create_secret(
      encode(gen_random_bytes(24), 'hex'),
      'cron_token',
      'Shared bearer that authorizes pg_cron -> edge-function trigger calls (process-booking-notifications, plan-reminder-cron).'
    );
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.verify_cron_token(_token text)
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = public, vault AS $$
  SELECT _token IS NOT NULL
     AND _token = (SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'cron_token');
$$;
REVOKE ALL ON FUNCTION public.verify_cron_token(text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verify_cron_token(text) TO service_role;

CREATE OR REPLACE FUNCTION public.cron_token_header()
RETURNS text LANGUAGE sql SECURITY DEFINER SET search_path = public, vault AS $$
  SELECT decrypted_secret FROM vault.decrypted_secrets WHERE name = 'cron_token';
$$;
REVOKE ALL ON FUNCTION public.cron_token_header() FROM PUBLIC, anon, authenticated;

SELECT cron.schedule(
  'booking-notifications', '*/5 * * * *',
  $cron$
  select net.http_post(
    url     := 'https://xygzykjyynhzqytbqnzu.supabase.co/functions/v1/process-booking-notifications',
    headers := jsonb_build_object('Content-Type','application/json','x-cron-token', public.cron_token_header()),
    body    := '{}'::jsonb
  );
  $cron$
);
SELECT cron.schedule(
  'plan-reminder-runner', '* * * * *',
  $cron$
  select net.http_post(
    url     := 'https://xygzykjyynhzqytbqnzu.supabase.co/functions/v1/plan-reminder-cron',
    headers := jsonb_build_object('Content-Type','application/json','x-cron-token', public.cron_token_header()),
    body    := '{}'::jsonb
  );
  $cron$
);
