-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712010206 (avatars_hardening)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712010206 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Audit hardening for the avatars bucket.
-- 1) Enforce size + type server-side so the client checks are defense-in-depth,
--    not the only gate (a direct API upload can't drop a 500MB file or an
--    HTML/SVG payload onto the platform's public storage origin).
update storage.buckets
set file_size_limit = 3145728,  -- 3 MB
    allowed_mime_types = array['image/png','image/jpeg','image/webp']
where id = 'avatars';

-- 2) Close cross-tenant enumeration. Public serving of an avatar goes through
--    the public object path (/object/public/avatars/…) which does NOT consult
--    RLS, so <img src> keeps working. The permissive SELECT policy only enabled
--    the authenticated .list()/.download() API — which let any user enumerate
--    every user's uid folder across every tenant. Restrict it to own folder.
drop policy if exists "avatars public read" on storage.objects;
create policy "avatars owner list" on storage.objects
  for select to authenticated using (
    bucket_id = 'avatars' and (storage.foldername(name))[1] = auth.uid()::text
  );
