-- S2 wave · Category 9 (Compliance & Legal) — seed 9 platform baseline skills into paige_skills.
--
-- Run through the generic S1b interpreter (default dispatch) — NO bespoke handler. category = 'compliance_legal'
-- (canonical §15, locked by the CHECK in 20260830000000). IP-CLEAN per §14/§62 (mechanic-descriptive only — no
-- anchor-person name, no branded legal-framework/product title, no source-repo name). tier_availability = §61
-- default; scoping = 'platform'.
--
-- §13 "NOT LEGAL ADVICE" GUARD (the KEY gate for this category): EVERY skill carries an EXPLICIT in-copy
-- disclaimer — in BOTH the description AND a step — that the output is a generic starting template / general
-- information, NOT legal, tax, or regulatory advice; Paige is not a lawyer and makes no legal determination; the
-- tenant must have it reviewed by a qualified attorney/professional for their jurisdiction before relying on it.
-- compliance_requirement_scan (the ONE read) carries the HEAVIEST guard and NEVER asserts the tenant is or is not
-- compliant. (crew advice_disclaimer_ok=true.)
--
-- §13 INTERPRETER-HONEST: 1 read_only+auto (compliance_requirement_scan — surfaces general considerations to
-- research, persists nothing, "not available / consult a professional" fallback, no legal conclusion) + 8
-- DRAFTERS (draft+confirm, file a draft for approval). NONE publish, file with an authority, submit, send, or
-- determine legal/compliance status.
--
-- §2 FINANCE-CLEAN (platform default): coaching-generic business governance ONLY (privacy, terms, refund,
-- consent, recordkeeping, disclaimers, contract-review checklist) — ZERO consumer-finance wording. The §1
-- verifier CAUGHT + SCRUBBED 2 banned-token hits that lived inside a disclaimer/guard (refund_policy_draft's
-- anchor said "financing"; compliance_requirement_scan's guard named a "regulated-lending vertical") and
-- rephrased them positively ("not legal, tax, or regulatory advice"); the shipped set is §2-clean (the §32.a
-- proof's finance scan re-verifies 0 hits).
--
-- §18 EXCLUSIONS (wrap-don't-duplicate): these are business-wide GOVERNANCE artifacts, distinct from Cat 2
-- draft_engagement_contract (the negotiated client CONTRACT itself) and draft_sop_process_doc (an operational
-- SOP), and from Cat 7 HR/people-management docs. contract_review_checklist is a PRE-SIGNING review checklist
-- (what to look for), NOT the contract. privacy_policy_draft (external published policy) vs
-- data_handling_summary_draft (internal overview of the business's own practices) differ by audience/purpose.
--
-- SOURCING LINEAGE (attribution here in the reference ONLY, never in a row, per §14): Anthropic Skills registry
-- structure + standard small-business governance mechanics (plain-language privacy/ToS/refund/consent/
-- recordkeeping/disclaimer drafting, generic compliance-consideration surfacing, pre-signing contract-review
-- checklist) — mechanics only, IP-clean, no branded legal product.
--
-- §1 crew: 2 distillation engineers + adversarial IP/§16/§18/§2/§13-not-advice verifier. Verdict FIX_NEEDED
--   because the verifier caught + scrubbed the 2 §2 disclaimer/guard hits above and confirmed all 9 carry the
--   NOT-LEGAL-ADVICE disclaimer (advice_disclaimer_ok=true); the corrected set is §2/§13-clean.
-- ON CONFLICT (slug) DO NOTHING makes this idempotent + safe to re-run.

insert into public.paige_skills (
  slug, name, description, category, trigger_phrases, steps, allowed_tools,
  risk_level, autonomy_lane, methodology_anchor, tier_availability, scoping,
  created_by, status, require_admin_confirm_first_n
) values
  (
    $s$privacy_policy_draft$s$, $s$Privacy Policy Draft$s$, $s$Drafts a plain-language privacy policy for the tenant's OWN business or website, describing in generic terms what personal information the business collects, why, how it is stored and shared, and how a person can request access or deletion. NOT LEGAL ADVICE: the output is a generic starting template and general information only, not legal, tax, or regulatory advice — Paige is not a lawyer and makes no legal determination. The tenant MUST have it reviewed by a qualified attorney for their jurisdiction before publishing or relying on it. Paige files a draft for the tenant to approve; she never publishes it and never certifies it as compliant.$s$,
    $s$compliance_legal$s$,
    ARRAY[$s$draft a privacy policy$s$, $s$write a privacy policy for my site$s$, $s$I need a privacy policy$s$, $s$create a data privacy statement$s$, $s$privacy page for my website$s$, $s$policy for how I handle customer data$s$]::text[],
    $j$[{"id": "gather_business_context", "tool": "context", "desc": "Read the tenant's declared business type, brand voice, region, website, and any known data-handling details (what they collect, contact channels) from tenant/brand context. Use only what is present; where a specific is unknown, leave a clearly-marked prompt for the tenant rather than inventing a fact (§15)."}, {"id": "gather_policy_structure", "tool": "rag", "desc": "Retrieve the generic, coaching-generic structural elements a plain-language privacy policy typically covers (information collected, purpose, storage, sharing, retention, individual rights, contact) as neutral scaffolding — no jurisdiction-specific legal conclusions."}, {"id": "generate_policy_with_disclaimer", "tool": "anthropic", "desc": "Generate the plain-language privacy policy draft in the tenant's voice (§3), and PREPEND an explicit in-copy disclaimer block stating: this is a generic starting template and general information, NOT legal, tax, or regulatory advice; Paige is not a lawyer and gives no legal determination; the tenant must have it reviewed by a qualified attorney for their jurisdiction before relying on it. Coaching-generic only, phrased positively, zero prohibited-vertical wording (§2)."}, {"id": "file_draft_for_approval", "tool": "client_memory", "desc": "File the drafted policy as a DRAFT for the tenant's review and approval (autonomy_lane=confirm) — never published, never certified. A human approves before any use."}, {"id": "render_draft_document", "tool": "pdf_render", "desc": "Render the approved-pending draft (disclaimer block included) as a shareable document the tenant can hand to their attorney for review."}]$j$::jsonb,
    ARRAY[$s$context$s$, $s$rag$s$, $s$anthropic$s$, $s$client_memory$s$, $s$pdf_render$s$]::text[],
    $s$draft$s$, $s$confirm$s$,
    $s$Governance/compliance document distinct from the Cat 2 engagement CONTRACT (draft_engagement_contract = the client agreement itself) and the operational SOP (draft_sop_process_doc). A privacy policy is business-wide data-governance, not a client agreement or a process doc, so it does not duplicate either (§18). Mechanic: gather declared business context + generic policy structure, generate a plain-language draft with a mandatory NOT-LEGAL-ADVICE disclaimer in-copy, file as a draft for human approval, render for attorney review. IP-clean: no branded legal framework, anchor person, or source-repo name in any field (§14/§62). Interpreter honesty: Paige drafts and persists a draft only — she cannot publish, file with any authority, or determine legal/compliance status (§13).$s$,
    $j${"god": "yes", "solo": "yes", "sub_account": "yes", "agency": "resell", "enterprise": "yes+resell"}$j$::jsonb, $s$platform$s$,
    'system', 'active', 0
  ),
  (
    $s$terms_of_service_draft$s$, $s$Terms of Service Draft$s$, $s$Drafts a starting terms-of-service / terms-of-use document for the tenant's OWN service, describing in generic terms the rules of using their service, acceptable use, limitations, and how disputes and changes are handled. NOT LEGAL ADVICE: the output is a generic starting template and general information only, not legal, tax, or regulatory advice — Paige is not a lawyer and makes no legal determination. The tenant MUST have it reviewed by a qualified attorney for their jurisdiction before publishing or relying on it. Paige files a draft for the tenant to approve; she never publishes it and never certifies it as enforceable.$s$,
    $s$compliance_legal$s$,
    ARRAY[$s$draft terms of service$s$, $s$write terms of use for my site$s$, $s$I need a terms and conditions page$s$, $s$create terms for my service$s$, $s$ToS for my website$s$, $s$user agreement for my platform$s$]::text[],
    $j$[{"id": "gather_service_context", "tool": "context", "desc": "Read the tenant's declared service, business type, brand voice, region, and website from tenant/brand context. Use only present specifics; mark unknowns for the tenant rather than inventing terms (§15)."}, {"id": "gather_terms_structure", "tool": "rag", "desc": "Retrieve the generic structural elements a plain-language terms-of-service typically covers (service description, acceptable use, account/eligibility, limitations, changes, termination, dispute handling, contact) as neutral scaffolding — no jurisdiction-specific legal conclusions."}, {"id": "generate_terms_with_disclaimer", "tool": "anthropic", "desc": "Generate the terms-of-service draft in the tenant's voice (§3), and PREPEND an explicit in-copy disclaimer block: this is a generic starting template and general information, NOT legal, tax, or regulatory advice; Paige is not a lawyer and gives no legal determination; the tenant must have it reviewed by a qualified attorney for their jurisdiction before relying on it. Coaching-generic only, phrased positively, zero prohibited-vertical wording (§2)."}, {"id": "file_draft_for_approval", "tool": "client_memory", "desc": "File the drafted terms as a DRAFT for the tenant's review and approval (autonomy_lane=confirm) — never published, never certified. A human approves before any use."}, {"id": "render_draft_document", "tool": "pdf_render", "desc": "Render the approved-pending draft (disclaimer block included) as a shareable document the tenant can hand to their attorney for review."}]$j$::jsonb,
    ARRAY[$s$context$s$, $s$rag$s$, $s$anthropic$s$, $s$client_memory$s$, $s$pdf_render$s$]::text[],
    $s$draft$s$, $s$confirm$s$,
    $s$Governance document distinct from the Cat 2 engagement CONTRACT (draft_engagement_contract = the negotiated client agreement) and the operational SOP (draft_sop_process_doc). Terms-of-service is the public rules-of-use for the tenant's service, not a per-client agreement or an internal process doc (§18). Mechanic: gather declared service context + generic ToS structure, generate a plain-language draft with a mandatory NOT-LEGAL-ADVICE disclaimer in-copy, file as a draft for human approval, render for attorney review. IP-clean: no branded framework, anchor person, or source-repo name (§14/§62). Interpreter honesty: drafts and persists a draft only — cannot publish, submit, or determine enforceability (§13).$s$,
    $j${"god": "yes", "solo": "yes", "sub_account": "yes", "agency": "resell", "enterprise": "yes+resell"}$j$::jsonb, $s$platform$s$,
    'system', 'active', 0
  ),
  (
    $s$refund_policy_draft$s$, $s$Refund Policy Draft$s$, $s$Drafts a refund / cancellation policy for the tenant's OWN offers, describing in generic terms eligibility windows, how refunds or cancellations are requested, and any conditions or exceptions the tenant wants to state. NOT LEGAL ADVICE: the output is a generic starting template and general information only, not legal, tax, or regulatory advice — Paige is not a lawyer and makes no legal determination. The tenant MUST have it reviewed by a qualified attorney for their jurisdiction before publishing or relying on it. Paige files a draft for the tenant to approve; she never publishes it and never certifies it as compliant.$s$,
    $s$compliance_legal$s$,
    ARRAY[$s$draft a refund policy$s$, $s$write a cancellation policy$s$, $s$I need a refund and cancellation policy$s$, $s$policy for refunds on my program$s$, $s$cancellation terms for my clients$s$, $s$no-refund policy wording$s$]::text[],
    $j$[{"id": "gather_offer_context", "tool": "context", "desc": "Read the tenant's declared offers, business type, brand voice, region, and any stated refund window or conditions from tenant/brand context. Use only present specifics (the tenant's chosen window, any exceptions); ask the tenant for a missing term rather than inventing one (§15)."}, {"id": "gather_refund_structure", "tool": "rag", "desc": "Retrieve the generic structural elements a plain-language refund/cancellation policy typically covers (eligibility window, how to request, method/timing of a refund, non-refundable conditions, cancellation notice, contact) as neutral scaffolding — no jurisdiction-specific legal conclusions."}, {"id": "generate_refund_policy_with_disclaimer", "tool": "anthropic", "desc": "Generate the refund/cancellation policy draft in the tenant's voice (§3), and PREPEND an explicit in-copy disclaimer block: this is a generic starting template and general information, NOT legal, tax, or regulatory advice; Paige is not a lawyer and gives no legal determination; the tenant must have it reviewed by a qualified attorney for their jurisdiction before relying on it. Coaching-generic only, phrased positively, zero prohibited-vertical wording (§2)."}, {"id": "file_draft_for_approval", "tool": "client_memory", "desc": "File the drafted policy as a DRAFT for the tenant's review and approval (autonomy_lane=confirm) — never published, never certified. A human approves before any use."}, {"id": "render_draft_document", "tool": "pdf_render", "desc": "Render the approved-pending draft (disclaimer block included) as a shareable document the tenant can hand to their attorney for review."}]$j$::jsonb,
    ARRAY[$s$context$s$, $s$rag$s$, $s$anthropic$s$, $s$client_memory$s$, $s$pdf_render$s$]::text[],
    $s$draft$s$, $s$confirm$s$,
    $s$Governance document distinct from the Cat 2 engagement CONTRACT (payment/refund terms negotiated INSIDE a specific client agreement) and any operational SOP. A published refund/cancellation policy is a business-wide governance statement of the tenant's standard offer terms, not a per-client contract clause (§18). Mechanic: gather declared offer context + generic refund-policy structure, generate a plain-language draft with a mandatory NOT-LEGAL-ADVICE disclaimer in-copy, file as a draft for human approval, render for attorney review. IP-clean: no branded framework, anchor person, or source-repo name (§14/§62). Interpreter honesty: drafts and persists a draft only — cannot process a refund, publish, or determine compliance (§13). Finance-clean (§2): this is generic offer-refund governance for the tenant's own program pricing, phrased positively as general information — not legal, tax, or regulatory advice — and never a prohibited-vertical surface.$s$,
    $j${"god": "yes", "solo": "yes", "sub_account": "yes", "agency": "resell", "enterprise": "yes+resell"}$j$::jsonb, $s$platform$s$,
    'system', 'active', 0
  ),
  (
    $s$consent_disclosure_draft$s$, $s$Consent & Disclosure Draft$s$, $s$Drafts a consent / disclosure statement for the tenant's OWN clients — for example session-recording consent, data-collection notice, or testimonial-use permission — describing in generic plain language what is being consented to, why, and how consent can be withdrawn. NOT LEGAL ADVICE: the output is a generic starting template and general information only, not legal, tax, or regulatory advice — Paige is not a lawyer and makes no legal determination. The tenant MUST have it reviewed by a qualified attorney for their jurisdiction before using it with clients. Paige files a draft for the tenant to approve; she never sends it and never certifies it as legally sufficient consent.$s$,
    $s$compliance_legal$s$,
    ARRAY[$s$draft a consent form$s$, $s$session recording consent statement$s$, $s$testimonial release wording$s$, $s$data collection disclosure for clients$s$, $s$I need a consent and disclosure statement$s$, $s$permission wording for using a client testimonial$s$]::text[],
    $j$[{"id": "gather_consent_context", "tool": "context", "desc": "Read the tenant's declared business type, brand voice, region, and the specific consent purpose being requested (recording, data collection, testimonial use) from tenant/brand context. Use only present specifics; ask the tenant for the exact scope of consent rather than inventing it (§15)."}, {"id": "gather_disclosure_structure", "tool": "rag", "desc": "Retrieve the generic structural elements a plain-language consent/disclosure statement typically covers (what is being consented to, purpose, how the information/recording is used and stored, how consent can be withdrawn, contact) as neutral scaffolding — no jurisdiction-specific legal conclusions."}, {"id": "generate_consent_with_disclaimer", "tool": "anthropic", "desc": "Generate the consent/disclosure draft in the tenant's voice (§3), and PREPEND an explicit in-copy disclaimer block: this is a generic starting template and general information, NOT legal, tax, or regulatory advice; Paige is not a lawyer and gives no legal determination; the tenant must have it reviewed by a qualified attorney for their jurisdiction before using it with clients. Coaching-generic only, phrased positively, zero prohibited-vertical wording (§2)."}, {"id": "file_draft_for_approval", "tool": "client_memory", "desc": "File the drafted consent/disclosure statement as a DRAFT for the tenant's review and approval (autonomy_lane=confirm) — never sent to a client, never certified. A human approves before any use."}, {"id": "render_draft_document", "tool": "pdf_render", "desc": "Render the approved-pending draft (disclaimer block included) as a shareable document the tenant can hand to their attorney for review."}]$j$::jsonb,
    ARRAY[$s$context$s$, $s$rag$s$, $s$anthropic$s$, $s$client_memory$s$, $s$pdf_render$s$]::text[],
    $s$draft$s$, $s$confirm$s$,
    $s$Governance/compliance document distinct from the Cat 2 engagement CONTRACT (draft_engagement_contract) and any HR/people-management doc (Cat 7). A client-facing consent/disclosure statement is a compliance governance artifact about data/recording/testimonial permission, not the paid engagement agreement and not a team-management document (§18). Mechanic: gather the specific consent purpose + generic disclosure structure, generate a plain-language draft with a mandatory NOT-LEGAL-ADVICE disclaimer in-copy, file as a draft for human approval, render for attorney review. IP-clean: no branded framework, anchor person, or source-repo name (§14/§62). Interpreter honesty: drafts and persists a draft only — cannot collect actual consent, send the statement, or determine legal sufficiency (§13).$s$,
    $j${"god": "yes", "solo": "yes", "sub_account": "yes", "agency": "resell", "enterprise": "yes+resell"}$j$::jsonb, $s$platform$s$,
    'system', 'active', 0
  ),
  (
    $s$compliance_requirement_scan$s$, $s$Compliance Considerations Scan$s$, $s$READ-ONLY. Reads the tenant's DECLARED business type and region and surfaces GENERAL compliance considerations they may want to look into — areas like privacy, consent, recordkeeping, and disclosures — as topics to research, NOT determinations. NOT LEGAL ADVICE and NOT A COMPLIANCE VERDICT: this is general information only, not legal, tax, or regulatory advice; Paige is not a lawyer and NEVER asserts that the tenant IS or IS NOT compliant with anything. Where a specific cannot be known, Paige says 'not available' and directs the tenant to consult a qualified professional. Persists nothing — no draft, no document, no record; it only reports considerations to look into.$s$,
    $s$compliance_legal$s$,
    ARRAY[$s$what compliance should I look into$s$, $s$compliance considerations for my business$s$, $s$what do I need to be compliant$s$, $s$am I missing any policies$s$, $s$what legal areas should I check for my business$s$, $s$compliance checklist for a coaching business$s$]::text[],
    $j$[{"id": "read_declared_business", "tool": "context", "desc": "Read ONLY the tenant's DECLARED business type and region from tenant context — never assume or infer a vertical the tenant did not declare (§38 vendor/assumption-clean). Where the declared type or region is missing, note it as 'not available' rather than guessing."}, {"id": "gather_general_considerations", "tool": "rag", "desc": "Retrieve GENERAL, coaching-generic compliance-consideration topics that a client-based service business commonly researches (privacy notices, client consent, recordkeeping, plain-language disclosures) — as neutral areas-to-look-into keyed to the declared business/region, never as legal conclusions or jurisdiction-specific requirements."}, {"id": "compose_considerations_with_hard_guard", "tool": "anthropic", "desc": "Compose the general considerations as a list of topics the tenant MAY want to look into, in the tenant's voice (§3), under a HEAVY, explicit NOT-LEGAL-ADVICE / NOT-A-VERDICT guard: state up front and reinforce that this is general information only, NOT legal, tax, or regulatory advice; that Paige is not a lawyer; that this makes NO determination that the tenant is or is not compliant with anything; and that the tenant should consult a qualified attorney/professional for their jurisdiction. For anything that cannot be known from the declared data, say 'not available — consult a qualified professional', never a conclusion. Coaching-generic only, phrased positively everywhere including the guard ('this is general information, not legal, tax, or regulatory advice'), and never referencing any regulated vertical (§2). Persist NOTHING."}]$j$::jsonb,
    ARRAY[$s$context$s$, $s$rag$s$, $s$anthropic$s$]::text[],
    $s$read_only$s$, $s$auto$s$,
    $s$The ONE read skill of the compliance category — read_only + auto, persists nothing (NO client_memory, NO pdf_render step) so it never files a draft or record (§16). Distinct from the Cat 2 documents and Cat 7 HR docs (§18): it does not draft any artifact; it only surfaces general governance topics to research. Mechanic: read declared business type + region, retrieve general coaching-generic compliance-consideration topics, compose them under a heavy NOT-LEGAL-ADVICE / NOT-A-COMPLIANCE-VERDICT guard with explicit 'not available / consult a professional' fallbacks. The §13 not-advice guard is the KEY gate here and is deliberately the heaviest: the skill NEVER asserts the tenant is or is not compliant and NEVER states a jurisdiction-specific legal requirement as fact. IP-clean: no branded framework, anchor person, or source-repo name (§14/§62). Interpreter honesty: it reports general considerations grounded in declared data and says 'not available' where it cannot know — it cannot determine legal or compliance status (§13).$s$,
    $j${"god": "yes", "solo": "yes", "sub_account": "yes", "agency": "resell", "enterprise": "yes+resell"}$j$::jsonb, $s$platform$s$,
    'system', 'active', 0
  ),
  (
    $s$contract_review_checklist$s$, $s$Contract Review Checklist$s$, $s$Drafts a plain-language PRE-SIGNING review checklist of considerations for the tenant to look for before they sign a contract (scope, term, termination, payment terms, ownership, confidentiality, liability, renewal), grounded in the tenant's declared business type and region. This is a governance/compliance REVIEW aid, not the contract itself. IMPORTANT: the output is a generic starting template and general information ONLY — it is NOT legal, tax, or regulatory advice; Paige is not a lawyer and makes no legal determination. The tenant must have it reviewed by a qualified attorney for their jurisdiction before relying on it or signing. Files a draft for the tenant's approval; nothing is signed, submitted, or acted on.$s$,
    $s$compliance_legal$s$,
    ARRAY[$s$what should I look for before I sign this contract$s$, $s$contract review checklist$s$, $s$things to check before signing an agreement$s$, $s$help me vet this contract before signing$s$, $s$pre-signing review checklist$s$]::text[],
    $j$[{"id": "gather_profile", "tool": "context", "desc": "Load the tenant's declared business type, jurisdiction/region, and the nature of the deal or relationship the contract governs from the tenant profile and prior context; use only fields that are actually present and never invent a jurisdiction, party, or term."}, {"id": "gather_considerations", "tool": "rag", "desc": "Retrieve coaching-generic contract-review considerations (scope of work, term and termination, payment and cancellation terms, ownership of deliverables, confidentiality, limitation of liability, auto-renewal, dispute resolution) relevant to the tenant's declared business and region from the knowledge base."}, {"id": "generate_checklist", "tool": "anthropic", "desc": "Generate a plain-language pre-signing REVIEW checklist of what to look for and what questions to raise, in the tenant's voice, and embed an explicit disclaimer at the top and bottom that this is a general starting template and general information ONLY, is NOT legal, tax, or regulatory advice, that Paige is not a lawyer and makes no legal determination, and that the tenant must have a qualified attorney review it for their jurisdiction before relying on it or signing."}, {"id": "persist_draft", "tool": "client_memory", "desc": "Persist the checklist as a DRAFT filed for the tenant's approval; the skill never treats it as final, never signs, and never acts on the contract."}, {"id": "render_pdf", "tool": "pdf_render", "desc": "Render the pending-approval checklist as a downloadable document for the tenant to review and take to their attorney."}]$j$::jsonb,
    ARRAY[$s$context$s$, $s$rag$s$, $s$anthropic$s$, $s$client_memory$s$, $s$pdf_render$s$]::text[],
    $s$draft$s$, $s$confirm$s$,
    $s$Gather-then-generate review-checklist mechanic: assemble the tenant's declared business/region context, retrieve generic contract-review consideration categories, and synthesize a plain-language pre-signing checklist of what to look for — then file it as a draft for human approval. §18 scope: this is a REVIEW CHECKLIST (things to examine before signing), NOT the Cat 2 draft_engagement_contract skill (which drafts the actual client agreement) and NOT the operational draft_sop_process_doc; it is a compliance/governance aid, not the legal instrument itself. §13 gate: every output carries an in-copy NOT-LEGAL-ADVICE disclaimer (general template, consult a qualified attorney, Paige makes no legal determination). The interpreter only gathers context and persists a draft — it cannot review authoritatively, sign, or determine legal sufficiency. IP-clean: no branded framework, anchor person, or source-repo name (§14/§62).$s$,
    $j${"god": "yes", "solo": "yes", "sub_account": "yes", "agency": "resell", "enterprise": "yes+resell"}$j$::jsonb, $s$platform$s$,
    'system', 'active', 0
  ),
  (
    $s$data_handling_summary_draft$s$, $s$Data Handling Summary Draft$s$, $s$Drafts a plain-language summary of how the tenant's OWN business collects, stores, and handles client data (what is collected, where it is kept, who can access it, how long it is retained, how it is protected and disposed of), grounded in the tenant's declared business type and region. This is a business-governance document, not a privacy determination. IMPORTANT: the output is a generic starting template and general information ONLY — it is NOT legal, tax, or regulatory advice, and Paige makes no compliance determination; it does not assert the tenant IS or IS NOT compliant with any privacy law. The tenant must have it reviewed by a qualified attorney or privacy professional for their jurisdiction before relying on it. Files a draft for the tenant's approval; nothing is published or acted on.$s$,
    $s$compliance_legal$s$,
    ARRAY[$s$draft a summary of how my business handles client data$s$, $s$data handling summary$s$, $s$explain how we collect and store client information$s$, $s$plain-language data handling overview$s$, $s$write up how we manage customer data$s$]::text[],
    $j$[{"id": "gather_profile", "tool": "context", "desc": "Load the tenant's declared business type, region, and any known data-collection touchpoints (intake forms, scheduling, payments handled by their own processor, communications) from the tenant profile and prior context; use only present fields and never fabricate a system, vendor, or practice the tenant has not declared."}, {"id": "gather_practices", "tool": "rag", "desc": "Retrieve coaching-generic data-governance considerations (categories of data collected, storage location, access control, retention period, protection measures, disposal, consent and opt-out) relevant to the tenant's declared business and region from the knowledge base."}, {"id": "research_references", "tool": "firecrawl", "desc": "Optionally gather general, publicly available best-practice references on plain-language data-handling summaries for small service businesses in the tenant's region; treat these as general information to inform structure only, never as an authoritative or jurisdiction-specific legal source."}, {"id": "generate_summary", "tool": "anthropic", "desc": "Generate a plain-language data-handling summary in the tenant's voice describing what data is collected, where it is stored, who accesses it, how long it is kept, and how it is protected and disposed of — using only tenant-declared facts and marking anything unknown as 'not specified' rather than guessing — and embed an explicit disclaimer that this is a general starting template and general information ONLY, is NOT legal, tax, or regulatory advice, makes no compliance determination, and must be reviewed by a qualified attorney or privacy professional for the tenant's jurisdiction before use."}, {"id": "persist_draft", "tool": "client_memory", "desc": "Persist the summary as a DRAFT filed for the tenant's approval; the skill never publishes it, never files it with any authority, and never asserts a compliance status."}, {"id": "render_pdf", "tool": "pdf_render", "desc": "Render the pending-approval summary as a downloadable document for the tenant to review with a professional."}]$j$::jsonb,
    ARRAY[$s$context$s$, $s$rag$s$, $s$firecrawl$s$, $s$anthropic$s$, $s$client_memory$s$, $s$pdf_render$s$]::text[],
    $s$draft$s$, $s$confirm$s$,
    $s$Gather-then-generate governance-summary mechanic: assemble the tenant's declared data touchpoints and region, retrieve generic data-governance consideration categories, optionally pull general public best-practice references, and synthesize a plain-language summary of how the tenant's own business handles client data — marking unknowns as 'not specified' and filing it as a draft for approval. §18 scope: this is a business-wide GOVERNANCE document (privacy/data-handling), distinct from the Cat 2 engagement contract, the operational SOP, and Cat 7 HR artifacts; it differs from privacy_policy_draft in that it is an INTERNAL overview of the business's own practices rather than the EXTERNAL published policy. §13 gate: the interpreter only gathers context and persists a draft; it never determines compliance, never asserts the tenant is or is not compliant, and every output carries an in-copy NOT-LEGAL-ADVICE disclaimer directing review by a qualified attorney or privacy professional. IP-clean: no branded framework, anchor person, or source-repo name (§14/§62).$s$,
    $j${"god": "yes", "solo": "yes", "sub_account": "yes", "agency": "resell", "enterprise": "yes+resell"}$j$::jsonb, $s$platform$s$,
    'system', 'active', 0
  ),
  (
    $s$disclaimer_draft$s$, $s$Disclaimer Draft$s$, $s$Drafts standard disclaimers for the tenant's marketing, content, and deliverables — such as results-not-guaranteed, general-information-only, and no-professional-relationship notices — written for the tenant's declared business type and region. This is a governance/compliance artifact, not the tenant's client contract. IMPORTANT: the disclaimers themselves, and this output, are a generic starting template and general information ONLY — NOT legal, tax, or regulatory advice; Paige is not a lawyer and makes no legal determination. The tenant must have them reviewed by a qualified attorney for their jurisdiction before relying on them. Files a draft for the tenant's approval; nothing is published or acted on.$s$,
    $s$compliance_legal$s$,
    ARRAY[$s$draft a disclaimer for my marketing$s$, $s$results not guaranteed disclaimer$s$, $s$general information only disclaimer$s$, $s$add a disclaimer to my content and deliverables$s$, $s$standard disclaimer language for my business$s$]::text[],
    $j$[{"id": "gather_profile", "tool": "context", "desc": "Load the tenant's declared business type, region, and the surfaces the disclaimer will appear on (website, marketing content, downloadable deliverables) from the tenant profile and prior context; use only present fields and never invent a claim, guarantee, or credential the tenant has not stated."}, {"id": "gather_patterns", "tool": "rag", "desc": "Retrieve coaching-generic disclaimer patterns (results-not-guaranteed, general-information-only, no-professional-relationship, individual-results-vary, testimonial context) relevant to the tenant's declared business and region from the knowledge base."}, {"id": "generate_disclaimers", "tool": "anthropic", "desc": "Generate a set of standard disclaimers in the tenant's voice, tailored to the named surfaces, phrasing every disclaimer positively (e.g. 'this is general information, not legal, tax, or regulatory advice') and embedding an explicit disclaimer that the drafted language itself is a general starting template and general information ONLY, is NOT legal, tax, or regulatory advice, that Paige makes no legal determination, and that a qualified attorney must review it for the tenant's jurisdiction before use."}, {"id": "persist_draft", "tool": "client_memory", "desc": "Persist the disclaimer set as a DRAFT filed for the tenant's approval; the skill never publishes it and never treats it as legally sufficient."}, {"id": "render_pdf", "tool": "pdf_render", "desc": "Render the pending-approval disclaimer set as a downloadable document for the tenant to review with their attorney."}]$j$::jsonb,
    ARRAY[$s$context$s$, $s$rag$s$, $s$anthropic$s$, $s$client_memory$s$, $s$pdf_render$s$]::text[],
    $s$draft$s$, $s$confirm$s$,
    $s$Gather-then-generate disclaimer mechanic: assemble the tenant's declared business, region, and target surfaces, retrieve generic disclaimer patterns, and synthesize a positively-phrased set of standard disclaimers — then file them as a draft for approval. §18 scope: disclaimers are a compliance/governance artifact for the tenant's marketing/content/deliverables, distinct from the Cat 2 engagement contract and the operational SOP. §2 finance-clean: disclaimers are phrased positively ('not legal, tax, or regulatory advice') and never reference any prohibited vertical. §13 gate: the interpreter only gathers context and persists a draft; every output carries an in-copy NOT-LEGAL-ADVICE disclaimer and directs the tenant to a qualified attorney; it never determines legal sufficiency. IP-clean: no branded framework, anchor person, or source-repo name (§14/§62).$s$,
    $j${"god": "yes", "solo": "yes", "sub_account": "yes", "agency": "resell", "enterprise": "yes+resell"}$j$::jsonb, $s$platform$s$,
    'system', 'active', 0
  ),
  (
    $s$recordkeeping_policy_draft$s$, $s$Recordkeeping Policy Draft$s$, $s$Drafts a recordkeeping and retention policy for the tenant's OWN business — what records to keep (client, financial, operational, communications), in what form, for how long, and how to dispose of them — grounded in the tenant's declared business type and region. This is a business-governance policy, not a legal determination of any statutory retention requirement. IMPORTANT: the output is a generic starting template and general information ONLY — it is NOT legal, tax, or regulatory advice, and Paige makes no determination of required retention periods; the tenant must have it reviewed by a qualified attorney or accountant for their jurisdiction before relying on it. Files a draft for the tenant's approval; nothing is enacted or acted on.$s$,
    $s$compliance_legal$s$,
    ARRAY[$s$draft a recordkeeping policy for my business$s$, $s$how long should I keep records$s$, $s$records retention policy$s$, $s$document retention policy draft$s$, $s$what records to keep and for how long$s$]::text[],
    $j$[{"id": "gather_profile", "tool": "context", "desc": "Load the tenant's declared business type, region, and record categories the business generates (client records, financial and tax records, contracts, operational logs, communications) from the tenant profile and prior context; use only present fields and never invent a statutory period or record type the tenant has not declared."}, {"id": "gather_categories", "tool": "rag", "desc": "Retrieve coaching-generic recordkeeping and retention considerations (record categories, storage form, general retention-period ranges, secure disposal, access control) relevant to the tenant's declared business and region from the knowledge base."}, {"id": "research_references", "tool": "firecrawl", "desc": "Optionally gather general, publicly available references on common recordkeeping and retention practices for small service businesses in the tenant's region; treat these as general information to inform ranges and structure only, presented as ranges to confirm with a professional, never as an authoritative or jurisdiction-specific requirement."}, {"id": "generate_policy", "tool": "anthropic", "desc": "Generate a plain-language recordkeeping/retention policy in the tenant's voice covering what to keep, in what form, suggested retention ranges (clearly marked as general ranges to confirm, not determinations), and disposal — and embed an explicit disclaimer that this is a general starting template and general information ONLY, is NOT legal, tax, or regulatory advice, that Paige makes no determination of any required retention period, and that a qualified attorney or accountant must review it for the tenant's jurisdiction before use."}, {"id": "persist_draft", "tool": "client_memory", "desc": "Persist the policy as a DRAFT filed for the tenant's approval; the skill never enacts it, never files it with any authority, and never asserts a required retention period as fact."}, {"id": "render_pdf", "tool": "pdf_render", "desc": "Render the pending-approval policy as a downloadable document for the tenant to review with a professional."}]$j$::jsonb,
    ARRAY[$s$context$s$, $s$rag$s$, $s$firecrawl$s$, $s$anthropic$s$, $s$client_memory$s$, $s$pdf_render$s$]::text[],
    $s$draft$s$, $s$confirm$s$,
    $s$Gather-then-generate retention-policy mechanic: assemble the tenant's declared record categories and region, retrieve generic recordkeeping consideration categories, optionally pull general public retention-practice references, and synthesize a plain-language recordkeeping/retention policy — with retention periods presented as general ranges to confirm, never as determinations — then file it as a draft for approval. §18 scope: this is a business-wide GOVERNANCE policy for the tenant's own records, distinct from the Cat 2 engagement contract, the operational SOP, and Cat 7 HR artifacts. §13 gate: the interpreter only gathers context and persists a draft; it never determines a legally required retention period and every output carries an in-copy NOT-LEGAL-ADVICE disclaimer directing review by a qualified attorney or accountant. IP-clean: no branded framework, anchor person, or source-repo name (§14/§62).$s$,
    $j${"god": "yes", "solo": "yes", "sub_account": "yes", "agency": "resell", "enterprise": "yes+resell"}$j$::jsonb, $s$platform$s$,
    'system', 'active', 0
  )
on conflict (slug) do nothing;
