-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712180708 (tenant_sender_identity_tenant_guard)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712180708 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Harden tenant_sender_identity (audit finding): it was SECURITY DEFINER and
-- returned ANY tenant's from-name/address to ANY authenticated caller. Safe as
-- used (callers pass their own tenant) but a latent cross-tenant leak. Pin JWT
-- callers to their own tenant; the platform owner (God) and service role keep
-- full cross-tenant access (send-transactional-email runs service-role).
CREATE OR REPLACE FUNCTION public.tenant_sender_identity(_tenant_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE r jsonb; t public.tenants%ROWTYPE;
BEGIN
  -- Tenant guard: an authenticated (JWT) caller may only resolve their OWN
  -- tenant's identity. auth.uid() IS NULL => service role (trusted). Platform
  -- owner (God) may resolve any tenant (§ God cross-tenant read invariant).
  IF auth.uid() IS NOT NULL
     AND NOT public.is_platform_owner()
     AND _tenant_id IS DISTINCT FROM public.current_user_tenant_id() THEN
    RETURN NULL;
  END IF;

  r := public.resolve_tenant_sender(_tenant_id);
  SELECT * INTO t FROM public.tenants WHERE id = _tenant_id;
  RETURN jsonb_build_object(
    'tenant_id',     _tenant_id,
    'tenant_name',   t.name,
    'tenant_slug',   t.slug,
    'from_name',     r ->> 'from_name',
    'support_email', t.brand ->> 'support_email',
    'from_address',  r ->> 'from_address',
    'reply_to',      r ->> 'reply_to'
  );
END; $$;
