-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260710011525 (peek_tenant_portal_brand_drop_tenant_id)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260710011525 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Reduce anon surface: drop tenant_id from the anon gateway brand peek.
DROP FUNCTION IF EXISTS public.peek_tenant_portal_brand(text);
CREATE FUNCTION public.peek_tenant_portal_brand(_slug text)
RETURNS TABLE (
  tenant_name text,
  tenant_slug text,
  logo_url text,
  primary_color text
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT
    t.name,
    t.slug,
    COALESCE(NULLIF(t.brand->>'logo_url', ''), p.brand_logo_url) AS logo_url,
    NULLIF(t.brand->>'primary_color', '') AS primary_color
  FROM public.tenants t
  LEFT JOIN public.tenant_legal_profile p ON p.tenant_id = t.id
  WHERE lower(t.slug) = lower(trim(_slug))
  LIMIT 1;
$$;
REVOKE EXECUTE ON FUNCTION public.peek_tenant_portal_brand(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.peek_tenant_portal_brand(text) TO anon, authenticated;
