-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712214735 (zoom_connection)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712214735 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

ALTER TABLE public.staff_calendar_settings
  ADD COLUMN IF NOT EXISTS zoom_connected boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS zoom_user_id text,
  ADD COLUMN IF NOT EXISTS zoom_email text,
  ADD COLUMN IF NOT EXISTS zoom_refresh_token_encrypted text,
  ADD COLUMN IF NOT EXISTS zoom_access_token_encrypted text,
  ADD COLUMN IF NOT EXISTS zoom_token_expires_at timestamptz;

COMMENT ON COLUMN public.staff_calendar_settings.zoom_connected IS 'True when this host has connected their own Zoom account (User-managed OAuth).';
COMMENT ON COLUMN public.staff_calendar_settings.zoom_user_id IS 'Zoom user id (from GET /v2/users/me) for the connected host account.';
COMMENT ON COLUMN public.staff_calendar_settings.zoom_email IS 'Email of the connected Zoom account, shown in the Connectors panel.';
COMMENT ON COLUMN public.staff_calendar_settings.zoom_refresh_token_encrypted IS 'AES-GCM ciphertext (calendarCrypto.encryptSecret) of the Zoom refresh token. Rotates on refresh.';
COMMENT ON COLUMN public.staff_calendar_settings.zoom_access_token_encrypted IS 'AES-GCM ciphertext (calendarCrypto.encryptSecret) of the current Zoom access token (~1h).';
COMMENT ON COLUMN public.staff_calendar_settings.zoom_token_expires_at IS 'When the stored Zoom access token expires; getFreshZoomToken refreshes past this.';

REVOKE SELECT (zoom_refresh_token_encrypted, zoom_access_token_encrypted)
  ON public.staff_calendar_settings FROM anon, authenticated;

ALTER TABLE public.internal_bookings
  ADD COLUMN IF NOT EXISTS meeting_url text,
  ADD COLUMN IF NOT EXISTS zoom_meeting_id text;

COMMENT ON COLUMN public.internal_bookings.meeting_url IS 'Resolved video meeting join URL (e.g. the host-account Zoom link minted at booking).';
COMMENT ON COLUMN public.internal_bookings.zoom_meeting_id IS 'Zoom meeting id for the meeting minted on the host account, so it can be moved on reschedule / deleted on cancel.';
