-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712190439 (rail_step4_client_emitters_hardened)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712190439 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.record_rail_event(
  p_contact_id       uuid,
  p_event_kind       text,
  p_surface          text,
  p_actor_type       text,
  p_title            text,
  p_summary          text DEFAULT NULL,
  p_payload          jsonb DEFAULT '{}'::jsonb,
  p_ref_table        text DEFAULT NULL,
  p_ref_id           uuid DEFAULT NULL,
  p_from_department  text DEFAULT NULL,
  p_to_department    text DEFAULT NULL,
  p_occurred_at      timestamptz DEFAULT NULL,
  p_narrow_to_owner  boolean DEFAULT false,
  p_tenant_id        uuid DEFAULT NULL
) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid       uuid := auth.uid();
  v_tenant    uuid;
  v_kind      public.paige_event_kinds%ROWTYPE;
  v_audience  text;
  v_visibility text;
  v_actor     uuid;
  v_id        uuid;
  v_occurred  timestamptz;
  v_from_dept text;
BEGIN
  IF v_uid IS NOT NULL THEN
    v_tenant := public.current_user_tenant_id();
    IF v_tenant IS NULL AND p_actor_type = 'client' THEN
      SELECT c.tenant_id INTO v_tenant
        FROM public.clients c
       WHERE c.id = p_contact_id AND c.linked_user_id = v_uid;
    END IF;
    IF p_tenant_id IS NOT NULL AND v_tenant IS NOT NULL AND p_tenant_id <> v_tenant THEN
      RAISE EXCEPTION 'tenant mismatch' USING errcode = '42501';
    END IF;
  ELSE
    IF p_tenant_id IS NULL THEN RAISE EXCEPTION 'p_tenant_id required for service caller'; END IF;
    v_tenant := p_tenant_id;
  END IF;
  IF v_tenant IS NULL THEN RAISE EXCEPTION 'no tenant resolved' USING errcode = '42501'; END IF;

  SELECT * INTO v_kind FROM public.paige_event_kinds
    WHERE slug = p_event_kind AND enabled AND (tenant_id IS NULL OR tenant_id = v_tenant);
  IF NOT FOUND THEN RAISE EXCEPTION 'unknown or unavailable event kind: %', p_event_kind; END IF;

  PERFORM 1 FROM public.clients c WHERE c.id = p_contact_id AND c.tenant_id = v_tenant;
  IF NOT FOUND THEN RAISE EXCEPTION 'contact not in tenant' USING errcode = '42501'; END IF;

  -- WRITER AUTH (§13 least-privilege, §9 seam): staff may file any kind; a subject
  -- client may file ONLY their own client-visible, non-narrowed kind — this blocks
  -- a client injecting an owner_internal event under actor_type='client'.
  IF v_uid IS NOT NULL THEN
    IF public.has_any_role(v_uid, ARRAY['admin','super_admin','coach']) THEN
      NULL;
    ELSIF p_actor_type = 'client'
          AND EXISTS (SELECT 1 FROM public.clients c
                       WHERE c.id = p_contact_id AND c.linked_user_id = v_uid) THEN
      IF p_narrow_to_owner OR v_kind.default_visibility <> 'client_visible' THEN
        RAISE EXCEPTION 'client may only file client-visible events' USING errcode = '42501';
      END IF;
    ELSE
      RAISE EXCEPTION 'not authorized to write rail event' USING errcode = '42501';
    END IF;
  END IF;

  v_audience   := CASE WHEN p_narrow_to_owner THEN 'owner' ELSE v_kind.default_audience END;
  v_visibility := CASE WHEN v_audience = 'owner' THEN 'owner_internal' ELSE v_kind.default_visibility END;
  v_actor      := CASE WHEN p_actor_type IN ('owner_staff','client') THEN v_uid ELSE NULL END;
  v_from_dept  := COALESCE(p_from_department, v_kind.department);

  INSERT INTO public.paige_client_events (
    tenant_id, contact_id, event_kind, surface, actor_type, actor_user_id,
    audience, visibility, from_department, to_department,
    title, summary, payload, ref_table, ref_id, occurred_at
  ) VALUES (
    v_tenant, p_contact_id, p_event_kind, p_surface, p_actor_type, v_actor,
    v_audience, v_visibility,
    v_from_dept, p_to_department,
    p_title, p_summary, COALESCE(p_payload, '{}'::jsonb), p_ref_table, p_ref_id,
    COALESCE(p_occurred_at, now())
  ) RETURNING id, occurred_at INTO v_id, v_occurred;

  INSERT INTO public.audit_logs (user_id, action, entity, entity_id, data)
  VALUES (v_uid, 'paige_rail_event', 'paige_client_events', v_id,
          jsonb_build_object('kind', p_event_kind, 'surface', p_surface, 'contact_id', p_contact_id, 'audience', v_audience));

  BEGIN
    PERFORM realtime.send(
      jsonb_build_object(
        'id', v_id, 'tenant_id', v_tenant, 'contact_id', p_contact_id,
        'event_kind', p_event_kind, 'surface', p_surface, 'actor_type', p_actor_type,
        'audience', v_audience, 'visibility', v_visibility,
        'from_department', v_from_dept, 'to_department', p_to_department,
        'title', p_title, 'summary', p_summary, 'payload', COALESCE(p_payload, '{}'::jsonb),
        'occurred_at', v_occurred
      ),
      'rail_event', 'rail:tenant:' || v_tenant::text, true
    );

    IF v_audience IN ('client','both') AND v_visibility = 'client_visible' THEN
      PERFORM realtime.send(
        jsonb_build_object(
          'id', v_id, 'contact_id', p_contact_id, 'event_kind', p_event_kind,
          'surface', p_surface, 'actor_type', p_actor_type, 'audience', v_audience,
          'visibility', v_visibility, 'title', p_title, 'summary', p_summary,
          'occurred_at', v_occurred
        ),
        'rail_event', 'rail:client:' || p_contact_id::text, true
      );
    END IF;
  EXCEPTION WHEN others THEN
    RAISE WARNING 'rail broadcast failed for event %: %', v_id, SQLERRM;
  END;

  RETURN v_id;
END $$;
REVOKE ALL ON FUNCTION public.record_rail_event(uuid,text,text,text,text,text,jsonb,text,uuid,text,text,timestamptz,boolean,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.record_rail_event(uuid,text,text,text,text,text,jsonb,text,uuid,text,text,timestamptz,boolean,uuid) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.customer_respond_to_action(p_action_id uuid, p_response_type text, p_response_text text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_action public.paige_customer_actions%ROWTYPE;
  v_owner uuid;
  v_new_status text;
BEGIN
  IF v_uid IS NULL THEN RETURN jsonb_build_object('ok', false, 'error', 'UNAUTHENTICATED'); END IF;
  IF p_response_type NOT IN ('accepted','declined','question','completed') THEN
    RETURN jsonb_build_object('ok', false, 'error', 'INVALID_RESPONSE_TYPE');
  END IF;

  SELECT * INTO v_action FROM public.paige_customer_actions WHERE id = p_action_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('ok', false, 'error', 'ACTION_NOT_FOUND'); END IF;

  SELECT linked_user_id INTO v_owner FROM public.clients WHERE id = v_action.contact_id;
  IF v_owner IS NULL OR v_owner <> v_uid THEN
    RETURN jsonb_build_object('ok', false, 'error', 'FORBIDDEN');
  END IF;

  IF v_action.status = 'expired' OR v_action.expires_at < now() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ACTION_EXPIRED');
  END IF;

  INSERT INTO public.paige_customer_responses(
    action_id, contact_id, responded_by_user_id, response_type, response_text
  ) VALUES (
    p_action_id, v_action.contact_id, v_uid, p_response_type, NULLIF(p_response_text,'')
  );

  v_new_status := CASE p_response_type
    WHEN 'declined' THEN 'customer_declined'
    WHEN 'completed' THEN 'customer_acted'
    WHEN 'accepted' THEN 'customer_acted'
    ELSE v_action.status
  END;

  UPDATE public.paige_customer_actions
     SET status = v_new_status, updated_at = now()
   WHERE id = p_action_id;

  INSERT INTO public.notifications(user_id, type, title, message, action_url, metadata)
  VALUES (
    v_action.initiated_by_admin_id, 'system'::public.notification_type,
    'Client responded to your Paige action',
    COALESCE(v_action.title,'Action') || ' — ' || p_response_type,
    '/admin/contacts/' || v_action.contact_id::text,
    jsonb_build_object('source','paige_customer_response','action_id', p_action_id, 'response_type', p_response_type)
  );

  INSERT INTO public.paige_audit_log(actor_user_id, tenant_id, action, target_type, target_id, payload)
  VALUES (
    v_uid, v_action.tenant_id, 'customer_respond_to_action', 'paige_customer_action', p_action_id,
    jsonb_build_object('response_type', p_response_type, 'contact_id', v_action.contact_id)
  );

  -- (B1) §8 close-the-loop on the linked action-bus row (best-effort).
  BEGIN
    UPDATE public.paige_actions
       SET result = COALESCE(result, '{}'::jsonb) || jsonb_build_object(
                      'client_response',        p_response_type,
                      'client_response_text',   NULLIF(p_response_text, ''),
                      'client_responded_at',    now(),
                      'customer_action_status', v_new_status),
           updated_at = now()
     WHERE customer_action_id = p_action_id
       AND tenant_id = v_action.tenant_id;
  EXCEPTION WHEN others THEN
    RAISE WARNING 'action-bus sync failed for customer action %: %', p_action_id, SQLERRM;
  END;

  -- (B2) file the response onto the Paige Context Rail (best-effort).
  BEGIN
    PERFORM public.record_rail_event(
      p_contact_id      => v_action.contact_id,
      p_event_kind      => 'client.action_response',
      p_surface         => 'client_portal',
      p_actor_type      => 'client',
      p_title           => CASE p_response_type
                             WHEN 'accepted'  THEN 'Accepted: '   || COALESCE(v_action.title, 'a request')
                             WHEN 'completed' THEN 'Completed: '   || COALESCE(v_action.title, 'a request')
                             WHEN 'declined'  THEN 'Declined: '    || COALESCE(v_action.title, 'a request')
                             WHEN 'question'  THEN 'Question on: ' || COALESCE(v_action.title, 'a request')
                             ELSE 'Responded to: ' || COALESCE(v_action.title, 'a request')
                           END,
      p_summary         => NULLIF(p_response_text, ''),
      p_payload         => jsonb_build_object('response_type', p_response_type),
      p_ref_table       => 'paige_customer_actions',
      p_ref_id          => p_action_id,
      p_from_department => 'client_experience',
      p_to_department   => 'owner_ops'
    );
  EXCEPTION WHEN others THEN
    RAISE WARNING 'rail emit failed for customer response on action %: %', p_action_id, SQLERRM;
  END;

  RETURN jsonb_build_object('ok', true, 'status', v_new_status);
END; $function$;
REVOKE ALL ON FUNCTION public.customer_respond_to_action(uuid, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.customer_respond_to_action(uuid, text, text) TO authenticated, service_role;
