-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260714180550 (marketplace_bundle_refcount_2_finance_guard)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260714180550 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Wave 1 chunk 2/5: shared finance lexicon + recursive default guard + after-the-fact recheck
CREATE OR REPLACE FUNCTION public._marketplace_finance_re()
 RETURNS text LANGUAGE sql IMMUTABLE AS $function$
  SELECT '(credit|funding|lending|lender|loan|financ|capital[- ]rais|tradeline|underwrit|\mdebt\M|merchant cash|cash advance|\mfico\M|collections|business credit|net[- ]?30|grant writ)'::text;
$function$;

CREATE OR REPLACE FUNCTION public.marketplace_item_guard()
 RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public' AS $function$
DECLARE
  _hay text; _manifest jsonb; _bad text;
  _fin_re text := public._marketplace_finance_re();
BEGIN
  IF NEW.default_for_new_tenants THEN
    IF NEW.is_finance THEN
      RAISE EXCEPTION 'A finance/credit marketplace item cannot be a default for new tenants (section 2). It may be listed as an opt-in item only.'
        USING ERRCODE = '22023';
    END IF;

    SELECT install_manifest INTO _manifest
      FROM public.marketplace_item_versions WHERE id = NEW.current_version_id;

    _hay := lower(concat_ws(' ',
      NEW.slug, NEW.name, NEW.tagline, NEW.description, NEW.category,
      coalesce(_manifest::text, '')));
    IF _hay ~ _fin_re THEN
      RAISE EXCEPTION 'This item ships finance/credit content and cannot be a default for new tenants (section 2). List it as an opt-in item, or set is_finance and keep it opt-in.'
        USING ERRCODE = '22023';
    END IF;

    IF _manifest ? 'bundle_items' THEN
      WITH RECURSIVE tree(slug, depth, path) AS (
        SELECT c.slug, 1, ARRAY[NEW.slug]
          FROM jsonb_array_elements_text(_manifest->'bundle_items') AS c(slug)
        UNION ALL
        SELECT gc.slug, t.depth + 1, t.path || t.slug
          FROM tree t
          JOIN public.marketplace_items ci ON ci.slug = t.slug
          JOIN public.marketplace_item_versions cv ON cv.id = ci.current_version_id
          CROSS JOIN LATERAL jsonb_array_elements_text(
                 COALESCE(cv.install_manifest->'bundle_items','[]'::jsonb)) AS gc(slug)
         WHERE t.depth < 8 AND NOT (gc.slug = ANY (t.path))
      )
      SELECT string_agg(DISTINCT ci.slug, ', ') INTO _bad
        FROM tree t
        JOIN public.marketplace_items ci ON ci.slug = t.slug
        LEFT JOIN public.marketplace_item_versions cv ON cv.id = ci.current_version_id
       WHERE ci.is_finance
          OR lower(concat_ws(' ', ci.slug, ci.name, ci.tagline, ci.description,
                             ci.category, coalesce(cv.install_manifest::text,''))) ~ _fin_re;
      IF _bad IS NOT NULL THEN
        RAISE EXCEPTION 'This bundle includes finance/credit content via child item(s) [%] and cannot be a default for new tenants (section 2). Keep the bundle opt-in.', _bad
          USING ERRCODE = '22023';
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END $function$;

CREATE OR REPLACE FUNCTION public._marketplace_default_bundle_finance_violation()
 RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$
  WITH RECURSIVE dt(root, descend, depth, path) AS (
    SELECT i.slug, c.slug, 1, ARRAY[i.slug]
      FROM public.marketplace_items i
      JOIN public.marketplace_item_versions v ON v.id = i.current_version_id
      CROSS JOIN LATERAL jsonb_array_elements_text(
             COALESCE(v.install_manifest->'bundle_items','[]'::jsonb)) AS c(slug)
     WHERE i.default_for_new_tenants AND i.item_type = 'bundle'
    UNION ALL
    SELECT dt.root, gc.slug, dt.depth + 1, dt.path || dt.descend
      FROM dt
      JOIN public.marketplace_items ci ON ci.slug = dt.descend
      JOIN public.marketplace_item_versions cv ON cv.id = ci.current_version_id
      CROSS JOIN LATERAL jsonb_array_elements_text(
             COALESCE(cv.install_manifest->'bundle_items','[]'::jsonb)) AS gc(slug)
     WHERE dt.depth < 8 AND NOT (gc.slug = ANY (dt.path))
  )
  SELECT string_agg(DISTINCT dt.root, ', ')
    FROM dt
    JOIN public.marketplace_items ci ON ci.slug = dt.descend
    LEFT JOIN public.marketplace_item_versions cv ON cv.id = ci.current_version_id
   WHERE ci.is_finance
      OR lower(concat_ws(' ', ci.slug, ci.name, ci.tagline, ci.description,
                         ci.category, coalesce(cv.install_manifest::text,'')))
         ~ public._marketplace_finance_re();
$function$;
REVOKE ALL ON FUNCTION public._marketplace_default_bundle_finance_violation() FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.marketplace_finance_default_recheck()
 RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public' AS $function$
DECLARE _bad text;
BEGIN
  _bad := public._marketplace_default_bundle_finance_violation();
  IF _bad IS NOT NULL THEN
    RAISE EXCEPTION 'This change would make default bundle(s) [%] ship finance/credit content to every new tenant (section 2). Un-default the bundle(s) first, or keep this item opt-in.', _bad
      USING ERRCODE = '22023';
  END IF;
  RETURN NULL;
END $function$;

DROP TRIGGER IF EXISTS trg_mp_items_finance_recheck ON public.marketplace_items;
CREATE TRIGGER trg_mp_items_finance_recheck
  AFTER UPDATE OF is_finance, current_version_id ON public.marketplace_items
  FOR EACH ROW WHEN (
    NEW.is_finance IS DISTINCT FROM OLD.is_finance
    OR NEW.current_version_id IS DISTINCT FROM OLD.current_version_id)
  EXECUTE FUNCTION public.marketplace_finance_default_recheck();

DROP TRIGGER IF EXISTS trg_mp_versions_finance_recheck ON public.marketplace_item_versions;
CREATE TRIGGER trg_mp_versions_finance_recheck
  AFTER INSERT OR UPDATE OF install_manifest, status ON public.marketplace_item_versions
  FOR EACH ROW EXECUTE FUNCTION public.marketplace_finance_default_recheck();
