-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260709162710 (calendars_collective_class_support)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260709162710 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

ALTER TABLE public.calendars
  ADD COLUMN IF NOT EXISTS capacity integer NOT NULL DEFAULT 8;

ALTER TABLE public.calendars
  ADD CONSTRAINT calendars_capacity_chk CHECK (capacity > 0);

ALTER TABLE public.calendars
  ADD CONSTRAINT calendars_type_chk
  CHECK (type IN ('personal', 'round_robin', 'collective', 'event'));
