-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260714192450 (marketplace_operator_seam_1_freeze_and_auth)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260714192450 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Wave 3 chunk 1/6: featured column + corrected freeze (SECURITY INVOKER, INSERT+UPDATE) + operator-auth helpers
ALTER TABLE public.marketplace_items
  ADD COLUMN IF NOT EXISTS featured boolean NOT NULL DEFAULT false;
COMMENT ON COLUMN public.marketplace_items.featured IS
  'Operator curation flag for the marketplace console hero/spotlight. Operator-managed only: frozen against non-privileged callers by marketplace_items_freeze_privileged() on BOTH insert and update, so a tenant vendor can neither self-feature an existing listing nor be born featured.';

CREATE OR REPLACE FUNCTION public.marketplace_items_freeze_privileged()
 RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public' AS $function$
BEGIN
  -- Privileged callers pass untouched. current_user is the CALLER (INVOKER):
  -- the definer RPCs run as the migration/owner role; service_role writes raw.
  IF current_user IN ('postgres','supabase_admin','service_role') OR public.is_platform_owner() THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    -- Non-privileged births: stat/curation/version columns must be at defaults.
    IF NEW.featured IS DISTINCT FROM false
       OR NEW.install_count IS DISTINCT FROM 0
       OR NEW.rating_avg IS NOT NULL
       OR NEW.rating_count IS DISTINCT FROM 0
       OR NEW.current_version_id IS NOT NULL THEN
      RAISE EXCEPTION 'these marketplace_items columns are platform-managed and cannot be set on insert (featured, install_count, rating_avg, rating_count, current_version_id)'
        USING ERRCODE = '42501';
    END IF;
    RETURN NEW;
  END IF;

  -- Non-privileged UPDATE: none of the platform-managed columns may change.
  IF NEW.install_count      IS DISTINCT FROM OLD.install_count
     OR NEW.rating_avg      IS DISTINCT FROM OLD.rating_avg
     OR NEW.rating_count    IS DISTINCT FROM OLD.rating_count
     OR NEW.origin          IS DISTINCT FROM OLD.origin
     OR NEW.default_for_new_tenants IS DISTINCT FROM OLD.default_for_new_tenants
     OR NEW.is_finance      IS DISTINCT FROM OLD.is_finance
     OR NEW.featured        IS DISTINCT FROM OLD.featured
     OR NEW.current_version_id IS DISTINCT FROM OLD.current_version_id THEN
    RAISE EXCEPTION 'these marketplace_items columns are managed by the platform and cannot be changed directly'
      USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END $function$;
REVOKE ALL ON FUNCTION public.marketplace_items_freeze_privileged() FROM PUBLIC;

DROP TRIGGER IF EXISTS trg_marketplace_items_freeze ON public.marketplace_items;
CREATE TRIGGER trg_marketplace_items_freeze
  BEFORE INSERT OR UPDATE ON public.marketplace_items
  FOR EACH ROW EXECUTE FUNCTION public.marketplace_items_freeze_privileged();

CREATE OR REPLACE FUNCTION public._marketplace_is_service_role()
 RETURNS boolean LANGUAGE sql STABLE AS $function$
  SELECT coalesce(
           (current_setting('request.jwt.claims', true)::jsonb ->> 'role') = 'service_role',
           false)
      OR session_user = 'service_role';  -- covers a direct service_role DB session
$function$;
REVOKE ALL ON FUNCTION public._marketplace_is_service_role() FROM PUBLIC;

CREATE OR REPLACE FUNCTION public._marketplace_operator_authorized()
 RETURNS boolean LANGUAGE sql STABLE AS $function$
  SELECT public.is_platform_owner() OR public._marketplace_is_service_role();
$function$;
REVOKE ALL ON FUNCTION public._marketplace_operator_authorized() FROM PUBLIC;
