-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260711185151 (forge_tenant_scope)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260711185151 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

alter table public.paige_subagents
  add column if not exists tenant_id uuid references public.tenants(id) on delete cascade;
alter table public.paige_subagent_proposals
  add column if not exists tenant_id uuid references public.tenants(id) on delete cascade;

create index if not exists idx_paige_subagents_tenant on public.paige_subagents(tenant_id);
create index if not exists idx_paige_subagent_proposals_tenant on public.paige_subagent_proposals(tenant_id);

alter table public.paige_subagent_factory_quota
  add column if not exists tenant_id uuid references public.tenants(id) on delete cascade;

create unique index if not exists uq_factory_quota_tenant_date
  on public.paige_subagent_factory_quota
  (coalesce(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), quota_date);

create or replace function public.bump_subagent_quota(_tenant_id uuid, _field text)
returns public.paige_subagent_factory_quota
language plpgsql
security definer
set search_path = public
as $$
declare
  _today date := (now() at time zone 'utc')::date;
  _row public.paige_subagent_factory_quota;
begin
  if _field not in ('proposals_count', 'soft_shipped', 'hard_shipped') then
    raise exception 'invalid quota field: %', _field;
  end if;
  -- migration-lint-ignore: pattern-1 -- reconciled prod transcript per #421; the hard-coded UUID is a COALESCE sentinel in the ON CONFLICT target, NOT a seeded FK row — the INSERT uses the plpgsql var _tenant_id and seeds no auth.users reference.
  insert into public.paige_subagent_factory_quota (tenant_id, quota_date, proposals_count, soft_shipped, hard_shipped)
    values (_tenant_id, _today, 0, 0, 0)
    on conflict (coalesce(tenant_id, '00000000-0000-0000-0000-000000000000'::uuid), quota_date) do nothing;
  execute format(
    'update public.paige_subagent_factory_quota set %I = %I + 1
       where coalesce(tenant_id, ''00000000-0000-0000-0000-000000000000''::uuid) = coalesce($1, ''00000000-0000-0000-0000-000000000000''::uuid)
         and quota_date = $2
     returning *', _field, _field)
    into _row using _tenant_id, _today;
  return _row;
end;
$$;

revoke all on function public.bump_subagent_quota(uuid, text) from public, anon, authenticated;
grant execute on function public.bump_subagent_quota(uuid, text) to service_role;

alter table public.paige_subagents enable row level security;

drop policy if exists paige_subagents_tenant_read on public.paige_subagents;
create policy paige_subagents_tenant_read on public.paige_subagents
  for select to authenticated
  using (tenant_id is null or tenant_id = public.current_user_tenant_id());
