-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260708215724 (grant_calendars_authenticated)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260708215724 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- The calendars/calendar_hosts migration enabled RLS + policies but never
-- granted base table privileges to `authenticated`. RLS filters rows; it does
-- not grant table access — so PostgREST rejected every request with
-- "permission denied for table calendars" before a policy was ever evaluated.
-- Public booking reads go through the service role (edge function), so anon
-- needs nothing here; authenticated management needs the standard DML grants.
GRANT SELECT, INSERT, UPDATE, DELETE ON public.calendars TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.calendar_hosts TO authenticated;
