-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260711232610 (paige_planning)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260711232610 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================


CREATE TABLE IF NOT EXISTS public.plans (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  created_by    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  owner_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  scope         text NOT NULL DEFAULT 'individual' CHECK (scope IN ('individual','team')),
  horizon       text NOT NULL CHECK (horizon IN ('week','month','quarter','year')),
  title         text NOT NULL,
  summary       text,
  starts_on     date NOT NULL,
  ends_on       date NOT NULL,
  status        text NOT NULL DEFAULT 'active' CHECK (status IN ('draft','active','completed','archived')),
  campaign_ref  jsonb,
  metadata      jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT plans_dates_ck CHECK (ends_on >= starts_on)
);
CREATE INDEX IF NOT EXISTS idx_plans_tenant  ON public.plans(tenant_id, status, starts_on DESC);
CREATE INDEX IF NOT EXISTS idx_plans_owner   ON public.plans(owner_user_id) WHERE owner_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_plans_horizon ON public.plans(tenant_id, horizon, starts_on);

CREATE TABLE IF NOT EXISTS public.plan_items (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  plan_id             uuid REFERENCES public.plans(id) ON DELETE CASCADE,
  parent_item_id      uuid REFERENCES public.plan_items(id) ON DELETE SET NULL,
  item_type           text NOT NULL CHECK (item_type IN ('milestone','task','reminder')),
  created_by          uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  assigned_to_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  contact_id          uuid REFERENCES public.clients(id) ON DELETE SET NULL,
  title               text NOT NULL,
  summary             text,
  status              text NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','done','cancelled','blocked')),
  priority            text NOT NULL DEFAULT 'normal' CHECK (priority IN ('low','normal','high','urgent')),
  due_at              timestamptz,
  remind_at           timestamptz,
  remind_channel      text NOT NULL DEFAULT 'in_app' CHECK (remind_channel IN ('in_app','email','sms')),
  remind_target       text NOT NULL DEFAULT 'user'  CHECK (remind_target IN ('user','team')),
  reminded_at         timestamptz,
  linked_booking_id   uuid REFERENCES public.internal_bookings(id) ON DELETE SET NULL,
  linked_action_id    uuid REFERENCES public.paige_actions(id) ON DELETE SET NULL,
  campaign_ref        jsonb,
  metadata            jsonb NOT NULL DEFAULT '{}'::jsonb,
  completed_at        timestamptz,
  resolved_at         timestamptz,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT plan_items_reminder_ck CHECK (item_type <> 'reminder' OR remind_at IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_pi_tenant_type ON public.plan_items(tenant_id, item_type, status, due_at);
CREATE INDEX IF NOT EXISTS idx_pi_assignee    ON public.plan_items(assigned_to_user_id, status) WHERE assigned_to_user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pi_plan        ON public.plan_items(plan_id) WHERE plan_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pi_parent      ON public.plan_items(parent_item_id) WHERE parent_item_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_pi_reminder_due ON public.plan_items(remind_at)
  WHERE item_type = 'reminder' AND reminded_at IS NULL AND status <> 'cancelled';

GRANT SELECT ON public.plans, public.plan_items TO authenticated;
GRANT ALL    ON public.plans, public.plan_items TO service_role;
ALTER TABLE public.plans      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plan_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS plans_read ON public.plans;
CREATE POLICY plans_read ON public.plans FOR SELECT TO authenticated USING (
  is_platform_owner()
  OR (tenant_id = public.current_user_tenant_id() AND (
        public.has_any_role(auth.uid(), ARRAY['admin','super_admin','coach'])
        OR owner_user_id = auth.uid() OR created_by = auth.uid()))
);
DROP POLICY IF EXISTS plans_no_write ON public.plans;
CREATE POLICY plans_no_write ON public.plans FOR ALL TO authenticated USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS plan_items_read ON public.plan_items;
CREATE POLICY plan_items_read ON public.plan_items FOR SELECT TO authenticated USING (
  is_platform_owner()
  OR (tenant_id = public.current_user_tenant_id() AND (
        public.has_any_role(auth.uid(), ARRAY['admin','super_admin','coach'])
        OR assigned_to_user_id = auth.uid() OR created_by = auth.uid()))
);
DROP POLICY IF EXISTS plan_items_no_write ON public.plan_items;
CREATE POLICY plan_items_no_write ON public.plan_items FOR ALL TO authenticated USING (false) WITH CHECK (false);

DROP TRIGGER IF EXISTS trg_plans_stamp ON public.plans;
CREATE TRIGGER trg_plans_stamp BEFORE INSERT ON public.plans FOR EACH ROW EXECUTE FUNCTION public.stamp_tenant_id();
DROP TRIGGER IF EXISTS trg_plan_items_stamp ON public.plan_items;
CREATE TRIGGER trg_plan_items_stamp BEFORE INSERT ON public.plan_items FOR EACH ROW EXECUTE FUNCTION public.stamp_tenant_id();
DROP TRIGGER IF EXISTS trg_plans_touch ON public.plans;
CREATE TRIGGER trg_plans_touch BEFORE UPDATE ON public.plans FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
DROP TRIGGER IF EXISTS trg_plan_items_touch ON public.plan_items;
CREATE TRIGGER trg_plan_items_touch BEFORE UPDATE ON public.plan_items FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE OR REPLACE FUNCTION public.notify_plan_item_assigned()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.assigned_to_user_id IS NOT NULL
     AND (TG_OP = 'INSERT' OR NEW.assigned_to_user_id IS DISTINCT FROM OLD.assigned_to_user_id) THEN
    PERFORM public.fire_team_event(jsonb_build_object(
      'event','plan_item_assigned','tenant_id',NEW.tenant_id,'user_id',NEW.assigned_to_user_id,
      'item_id',NEW.id,'item_type',NEW.item_type,'title',NEW.title));
  END IF;
  RETURN NEW;
END $$;
REVOKE EXECUTE ON FUNCTION public.notify_plan_item_assigned() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS trg_notify_plan_item_assigned ON public.plan_items;
CREATE TRIGGER trg_notify_plan_item_assigned
  AFTER INSERT OR UPDATE OF assigned_to_user_id ON public.plan_items
  FOR EACH ROW EXECUTE FUNCTION public.notify_plan_item_assigned();

INSERT INTO public.paige_action_kinds
 (slug, tenant_id, label, description, default_from_department, default_to_department,
  executor, requires_approval, approval_type, draft_subagent_slug, default_autonomy_lane, default_priority, enabled)
VALUES
 ('owner.planning_milestone', NULL, 'Planning milestone', 'A milestone for the admin team, filed from a plan.',
   'owner_ops','owner_ops','record_only', false, 'other', NULL, 'auto','normal', true),
 ('owner.planning_task', NULL, 'Planning task', 'A task assigned to a teammate (e.g. a campaign-rollout step).',
   'owner_ops','owner_ops','record_only', false, 'other', NULL, 'auto','normal', true),
 ('owner.team_reminder', NULL, 'Team reminder', 'A scheduled reminder for a person or the team, filed from a plan.',
   'owner_ops','owner_ops','record_only', false, 'other', NULL, 'auto','low', true)
ON CONFLICT (slug) DO NOTHING;

CREATE OR REPLACE FUNCTION public.plan_create(
  p_title text, p_horizon text, p_starts_on date, p_ends_on date,
  p_scope text DEFAULT 'individual', p_owner_user_id uuid DEFAULT NULL,
  p_summary text DEFAULT NULL, p_campaign_ref jsonb DEFAULT NULL, p_tenant_id uuid DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _caller uuid := auth.uid(); _tenant uuid; _owner uuid := p_owner_user_id; _staff boolean := false; _id uuid;
BEGIN
  IF _caller IS NOT NULL THEN
    _tenant := public.current_user_tenant_id();
    IF p_tenant_id IS NOT NULL AND p_tenant_id <> _tenant THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: tenant mismatch' USING ERRCODE='42501'; END IF;
    IF NOT public.is_tenant_member(_tenant) THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: not a member' USING ERRCODE='42501'; END IF;
    _staff := public.has_any_role(_caller, ARRAY['admin','super_admin','coach']);
  ELSE
    _tenant := p_tenant_id;
    IF _tenant IS NULL THEN RAISE EXCEPTION 'PLAN_NO_TENANT' USING ERRCODE='22023'; END IF;
    _staff := true;
  END IF;
  _owner := COALESCE(_owner, _caller);
  IF NOT _staff AND (COALESCE(p_scope,'individual') <> 'individual' OR _owner IS DISTINCT FROM _caller) THEN
    RAISE EXCEPTION 'PLAN_FORBIDDEN: team planning needs admin or coach' USING ERRCODE='42501';
  END IF;
  IF COALESCE(btrim(p_title),'') = '' THEN RAISE EXCEPTION 'PLAN_TITLE_REQUIRED' USING ERRCODE='22023'; END IF;
  IF p_horizon NOT IN ('week','month','quarter','year') THEN RAISE EXCEPTION 'PLAN_BAD_HORIZON' USING ERRCODE='22023'; END IF;
  IF p_ends_on < p_starts_on THEN RAISE EXCEPTION 'PLAN_BAD_WINDOW' USING ERRCODE='22023'; END IF;
  IF _owner IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.tenant_members WHERE user_id=_owner AND tenant_id=_tenant AND status='active') THEN
    RAISE EXCEPTION 'PLAN_OWNER_NOT_IN_TENANT' USING ERRCODE='42501'; END IF;
  INSERT INTO public.plans(tenant_id, created_by, owner_user_id, scope, horizon, title, summary, starts_on, ends_on, campaign_ref)
  VALUES (_tenant, _caller, _owner, COALESCE(p_scope,'individual'), p_horizon, btrim(p_title), p_summary, p_starts_on, p_ends_on, p_campaign_ref)
  RETURNING id INTO _id;
  INSERT INTO public.audit_logs(user_id, entity, action, entity_id, data)
  VALUES (_caller,'plan','plan_create',_id, jsonb_build_object('tenant_id',_tenant,'horizon',p_horizon,'scope',p_scope));
  RETURN jsonb_build_object('ok',true,'plan_id',_id);
END $$;

CREATE OR REPLACE FUNCTION public.plan_add_milestone(
  p_plan_id uuid, p_title text, p_summary text DEFAULT NULL, p_due_at timestamptz DEFAULT NULL,
  p_assigned_to_user_id uuid DEFAULT NULL, p_priority text DEFAULT 'normal', p_tenant_id uuid DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _caller uuid := auth.uid(); _tenant uuid; _id uuid;
BEGIN
  IF _caller IS NOT NULL THEN
    _tenant := public.current_user_tenant_id();
    IF p_tenant_id IS NOT NULL AND p_tenant_id <> _tenant THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: tenant mismatch' USING ERRCODE='42501'; END IF;
    IF NOT (public.is_tenant_member(_tenant) AND public.has_any_role(_caller, ARRAY['admin','super_admin','coach'])) THEN
      RAISE EXCEPTION 'PLAN_FORBIDDEN: admin or coach required' USING ERRCODE='42501'; END IF;
  ELSE _tenant := p_tenant_id; IF _tenant IS NULL THEN RAISE EXCEPTION 'PLAN_NO_TENANT' USING ERRCODE='22023'; END IF; END IF;
  IF p_plan_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.plans WHERE id=p_plan_id AND tenant_id=_tenant) THEN
    RAISE EXCEPTION 'PLAN_NOT_IN_TENANT' USING ERRCODE='42501'; END IF;
  IF p_assigned_to_user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.tenant_members WHERE user_id=p_assigned_to_user_id AND tenant_id=_tenant AND status='active') THEN
    RAISE EXCEPTION 'PLAN_ASSIGNEE_NOT_IN_TENANT' USING ERRCODE='42501'; END IF;
  INSERT INTO public.plan_items(tenant_id, plan_id, item_type, title, summary, due_at, assigned_to_user_id, priority, created_by)
  VALUES (_tenant, p_plan_id, 'milestone', btrim(p_title), p_summary, p_due_at, p_assigned_to_user_id, COALESCE(p_priority,'normal'), _caller)
  RETURNING id INTO _id;
  INSERT INTO public.audit_logs(user_id, entity, action, entity_id, data)
  VALUES (_caller,'plan_item','plan_add_milestone',_id, jsonb_build_object('tenant_id',_tenant,'plan_id',p_plan_id,'assignee',p_assigned_to_user_id));
  RETURN jsonb_build_object('ok',true,'item_id',_id,'item_type','milestone');
END $$;

CREATE OR REPLACE FUNCTION public.plan_assign_task(
  p_title text, p_assigned_to_user_id uuid, p_plan_id uuid DEFAULT NULL, p_milestone_id uuid DEFAULT NULL,
  p_due_at timestamptz DEFAULT NULL, p_priority text DEFAULT 'normal', p_summary text DEFAULT NULL,
  p_contact_id uuid DEFAULT NULL, p_campaign_ref jsonb DEFAULT NULL, p_file_to_bus boolean DEFAULT true, p_tenant_id uuid DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _caller uuid := auth.uid(); _tenant uuid; _staff boolean := false; _id uuid; _filed jsonb; _aid uuid;
BEGIN
  IF _caller IS NOT NULL THEN
    _tenant := public.current_user_tenant_id();
    IF p_tenant_id IS NOT NULL AND p_tenant_id <> _tenant THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: tenant mismatch' USING ERRCODE='42501'; END IF;
    IF NOT public.is_tenant_member(_tenant) THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: not a member' USING ERRCODE='42501'; END IF;
    _staff := public.has_any_role(_caller, ARRAY['admin','super_admin','coach']);
  ELSE _tenant := p_tenant_id; IF _tenant IS NULL THEN RAISE EXCEPTION 'PLAN_NO_TENANT' USING ERRCODE='22023'; END IF; _staff := true; END IF;
  IF p_assigned_to_user_id IS NULL OR NOT EXISTS (SELECT 1 FROM public.tenant_members WHERE user_id=p_assigned_to_user_id AND tenant_id=_tenant AND status='active') THEN
    RAISE EXCEPTION 'PLAN_ASSIGNEE_NOT_IN_TENANT' USING ERRCODE='42501'; END IF;
  IF NOT _staff AND p_assigned_to_user_id IS DISTINCT FROM _caller THEN
    RAISE EXCEPTION 'PLAN_FORBIDDEN: assigning to a teammate needs admin or coach' USING ERRCODE='42501'; END IF;
  IF p_plan_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.plans WHERE id=p_plan_id AND tenant_id=_tenant) THEN
    RAISE EXCEPTION 'PLAN_NOT_IN_TENANT' USING ERRCODE='42501'; END IF;
  IF p_milestone_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.plan_items WHERE id=p_milestone_id AND tenant_id=_tenant AND item_type='milestone') THEN
    RAISE EXCEPTION 'PLAN_MILESTONE_NOT_IN_TENANT' USING ERRCODE='42501'; END IF;
  IF p_contact_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.clients WHERE id=p_contact_id AND tenant_id=_tenant) THEN
    RAISE EXCEPTION 'PLAN_CONTACT_NOT_IN_TENANT' USING ERRCODE='42501'; END IF;
  INSERT INTO public.plan_items(tenant_id, plan_id, parent_item_id, item_type, title, summary, due_at, assigned_to_user_id, priority, contact_id, campaign_ref, created_by)
  VALUES (_tenant, p_plan_id, p_milestone_id, 'task', btrim(p_title), p_summary, p_due_at, p_assigned_to_user_id, COALESCE(p_priority,'normal'), p_contact_id, p_campaign_ref, _caller)
  RETURNING id INTO _id;
  IF p_file_to_bus THEN
    _filed := public.file_action(
      p_action_kind := 'owner.planning_task', p_title := btrim(p_title), p_summary := p_summary,
      p_contact_id := p_contact_id, p_payload := jsonb_build_object('plan_item_id',_id,'plan_id',p_plan_id,'campaign_ref',p_campaign_ref),
      p_priority := COALESCE(p_priority,'normal'), p_due_at := p_due_at, p_tenant_id := _tenant);
    _aid := COALESCE(NULLIF(_filed->>'action_id',''), NULLIF(_filed->>'id',''))::uuid;
    IF _aid IS NOT NULL THEN
      PERFORM public.advance_action(p_action_id := _aid, p_to_status := 'assigned', p_assigned_to_user_id := p_assigned_to_user_id, p_tenant_id := _tenant);
      UPDATE public.plan_items SET linked_action_id = _aid WHERE id = _id;
    END IF;
  END IF;
  INSERT INTO public.audit_logs(user_id, entity, action, entity_id, data)
  VALUES (_caller,'plan_item','plan_assign_task',_id, jsonb_build_object('tenant_id',_tenant,'assignee',p_assigned_to_user_id,'filed_action',_aid));
  RETURN jsonb_build_object('ok',true,'item_id',_id,'item_type','task','assignee',p_assigned_to_user_id,'action_id',_aid);
END $$;

CREATE OR REPLACE FUNCTION public.plan_set_reminder(
  p_title text, p_remind_at timestamptz, p_target text DEFAULT 'user', p_target_user_id uuid DEFAULT NULL,
  p_channel text DEFAULT 'in_app', p_plan_id uuid DEFAULT NULL, p_summary text DEFAULT NULL, p_tenant_id uuid DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _caller uuid := auth.uid(); _tenant uuid; _staff boolean := false; _assignee uuid; _id uuid;
BEGIN
  IF _caller IS NOT NULL THEN
    _tenant := public.current_user_tenant_id();
    IF p_tenant_id IS NOT NULL AND p_tenant_id <> _tenant THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: tenant mismatch' USING ERRCODE='42501'; END IF;
    IF NOT public.is_tenant_member(_tenant) THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: not a member' USING ERRCODE='42501'; END IF;
    _staff := public.has_any_role(_caller, ARRAY['admin','super_admin','coach']);
  ELSE _tenant := p_tenant_id; IF _tenant IS NULL THEN RAISE EXCEPTION 'PLAN_NO_TENANT' USING ERRCODE='22023'; END IF; _staff := true; END IF;
  IF p_remind_at IS NULL THEN RAISE EXCEPTION 'PLAN_REMINDER_TIME_REQUIRED' USING ERRCODE='22023'; END IF;
  _assignee := CASE WHEN COALESCE(p_target,'user')='team' THEN NULL ELSE COALESCE(p_target_user_id, _caller) END;
  IF NOT _staff AND (COALESCE(p_target,'user')='team' OR _assignee IS DISTINCT FROM _caller) THEN
    RAISE EXCEPTION 'PLAN_FORBIDDEN: team/other reminders need admin or coach' USING ERRCODE='42501'; END IF;
  IF _assignee IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.tenant_members WHERE user_id=_assignee AND tenant_id=_tenant AND status='active') THEN
    RAISE EXCEPTION 'PLAN_ASSIGNEE_NOT_IN_TENANT' USING ERRCODE='42501'; END IF;
  IF p_plan_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.plans WHERE id=p_plan_id AND tenant_id=_tenant) THEN
    RAISE EXCEPTION 'PLAN_NOT_IN_TENANT' USING ERRCODE='42501'; END IF;
  INSERT INTO public.plan_items(tenant_id, plan_id, item_type, title, summary, remind_at, remind_channel, remind_target, assigned_to_user_id, created_by)
  VALUES (_tenant, p_plan_id, 'reminder', btrim(p_title), p_summary, p_remind_at, COALESCE(p_channel,'in_app'), COALESCE(p_target,'user'), _assignee, _caller)
  RETURNING id INTO _id;
  INSERT INTO public.audit_logs(user_id, entity, action, entity_id, data)
  VALUES (_caller,'plan_item','plan_set_reminder',_id, jsonb_build_object('tenant_id',_tenant,'target',p_target,'remind_at',p_remind_at));
  RETURN jsonb_build_object('ok',true,'item_id',_id,'item_type','reminder','remind_at',p_remind_at);
END $$;

CREATE OR REPLACE FUNCTION public.plan_update_item(
  p_item_id uuid, p_status text DEFAULT NULL, p_title text DEFAULT NULL, p_summary text DEFAULT NULL,
  p_due_at timestamptz DEFAULT NULL, p_remind_at timestamptz DEFAULT NULL, p_priority text DEFAULT NULL,
  p_assigned_to_user_id uuid DEFAULT NULL, p_tenant_id uuid DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _caller uuid := auth.uid(); _row public.plan_items%ROWTYPE; _staff boolean := false;
BEGIN
  SELECT * INTO _row FROM public.plan_items WHERE id=p_item_id FOR UPDATE;
  IF _row.id IS NULL THEN RAISE EXCEPTION 'PLAN_ITEM_NOT_FOUND' USING ERRCODE='P0002'; END IF;
  IF _caller IS NOT NULL THEN
    IF NOT (_row.tenant_id = public.current_user_tenant_id() OR public.is_platform_owner()) THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: wrong tenant' USING ERRCODE='42501'; END IF;
    _staff := public.has_any_role(_caller, ARRAY['admin','super_admin','coach']);
    IF NOT (_staff OR _row.assigned_to_user_id = _caller OR _row.created_by = _caller) THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: not your item' USING ERRCODE='42501'; END IF;
  ELSE
    IF p_tenant_id IS NOT NULL AND p_tenant_id <> _row.tenant_id THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: tenant mismatch' USING ERRCODE='42501'; END IF;
    _staff := true;
  END IF;
  IF NOT _staff AND _row.created_by IS DISTINCT FROM _caller
     AND (p_title IS NOT NULL OR p_summary IS NOT NULL OR p_due_at IS NOT NULL OR p_remind_at IS NOT NULL OR p_priority IS NOT NULL OR p_assigned_to_user_id IS NOT NULL) THEN
    RAISE EXCEPTION 'PLAN_FORBIDDEN: assignee may only change status' USING ERRCODE='42501'; END IF;
  IF p_assigned_to_user_id IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.tenant_members WHERE user_id=p_assigned_to_user_id AND tenant_id=_row.tenant_id AND status='active') THEN
    RAISE EXCEPTION 'PLAN_ASSIGNEE_NOT_IN_TENANT' USING ERRCODE='42501'; END IF;
  IF p_status IS NOT NULL AND p_status NOT IN ('open','in_progress','done','cancelled','blocked') THEN RAISE EXCEPTION 'PLAN_BAD_STATUS' USING ERRCODE='22023'; END IF;
  UPDATE public.plan_items SET
    status = COALESCE(p_status, status),
    title = COALESCE(NULLIF(btrim(p_title),''), title),
    summary = COALESCE(p_summary, summary),
    due_at = COALESCE(p_due_at, due_at),
    remind_at = COALESCE(p_remind_at, remind_at),
    priority = COALESCE(p_priority, priority),
    assigned_to_user_id = COALESCE(p_assigned_to_user_id, assigned_to_user_id),
    completed_at = CASE WHEN p_status='done' THEN now() ELSE completed_at END,
    resolved_at  = CASE WHEN p_status IN ('done','cancelled') THEN now() ELSE resolved_at END
  WHERE id=p_item_id;
  INSERT INTO public.audit_logs(user_id, entity, action, entity_id, data)
  VALUES (_caller,'plan_item','plan_update_item',p_item_id, jsonb_build_object('status',p_status,'staff',_staff));
  RETURN jsonb_build_object('ok',true,'item_id',p_item_id,'status',COALESCE(p_status,_row.status));
END $$;

CREATE OR REPLACE FUNCTION public.plan_remove_item(p_item_id uuid, p_tenant_id uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _caller uuid := auth.uid(); _row public.plan_items%ROWTYPE;
BEGIN
  SELECT * INTO _row FROM public.plan_items WHERE id=p_item_id FOR UPDATE;
  IF _row.id IS NULL THEN RAISE EXCEPTION 'PLAN_ITEM_NOT_FOUND' USING ERRCODE='P0002'; END IF;
  IF _caller IS NOT NULL THEN
    IF NOT (_row.tenant_id = public.current_user_tenant_id() OR public.is_platform_owner()) THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: wrong tenant' USING ERRCODE='42501'; END IF;
    IF NOT (public.has_any_role(_caller, ARRAY['admin','super_admin','coach']) OR _row.created_by = _caller) THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: admin, coach, or creator required' USING ERRCODE='42501'; END IF;
  ELSIF p_tenant_id IS NOT NULL AND p_tenant_id <> _row.tenant_id THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: tenant mismatch' USING ERRCODE='42501'; END IF;
  UPDATE public.plan_items SET status='cancelled', resolved_at=now() WHERE id=p_item_id;
  IF _row.linked_action_id IS NOT NULL THEN
    PERFORM public.advance_action(p_action_id := _row.linked_action_id, p_to_status := 'dismissed', p_decision_rationale := 'planning item removed', p_tenant_id := _row.tenant_id);
  END IF;
  INSERT INTO public.audit_logs(user_id, entity, action, entity_id, data)
  VALUES (_caller,'plan_item','plan_remove_item',p_item_id, jsonb_build_object('tenant_id',_row.tenant_id));
  RETURN jsonb_build_object('ok',true,'item_id',p_item_id,'status','cancelled');
END $$;

CREATE OR REPLACE FUNCTION public.plan_list(
  p_horizon text DEFAULT NULL, p_plan_id uuid DEFAULT NULL, p_status text DEFAULT NULL,
  p_assigned_to_user_id uuid DEFAULT NULL, p_from date DEFAULT NULL, p_to date DEFAULT NULL,
  p_limit int DEFAULT 50, p_tenant_id uuid DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _caller uuid := auth.uid(); _tenant uuid; _out jsonb;
BEGIN
  IF _caller IS NOT NULL THEN
    _tenant := public.current_user_tenant_id();
    IF NOT public.is_tenant_member(_tenant) THEN RAISE EXCEPTION 'PLAN_FORBIDDEN' USING ERRCODE='42501'; END IF;
  ELSE _tenant := p_tenant_id; IF _tenant IS NULL THEN RAISE EXCEPTION 'PLAN_NO_TENANT' USING ERRCODE='22023'; END IF; END IF;
  SELECT jsonb_agg(row_to_json(p)::jsonb || jsonb_build_object('items', COALESCE(it.items,'[]'::jsonb)) ORDER BY p.starts_on DESC) INTO _out
  FROM (
    SELECT * FROM public.plans
     WHERE tenant_id=_tenant
       AND (p_plan_id IS NULL OR id=p_plan_id)
       AND (p_horizon IS NULL OR horizon=p_horizon)
       AND (p_status IS NULL OR status=p_status)
       AND (p_from IS NULL OR ends_on >= p_from)
       AND (p_to IS NULL OR starts_on <= p_to)
     ORDER BY starts_on DESC LIMIT GREATEST(1, LEAST(COALESCE(p_limit,50),200))
  ) p
  LEFT JOIN LATERAL (
    SELECT jsonb_agg(row_to_json(i)::jsonb ORDER BY i.due_at NULLS LAST, i.remind_at NULLS LAST, i.created_at) AS items
      FROM public.plan_items i
     WHERE i.plan_id = p.id
       AND (p_assigned_to_user_id IS NULL OR i.assigned_to_user_id = p_assigned_to_user_id)
       AND i.status <> 'cancelled'
  ) it ON true;
  RETURN COALESCE(_out, '[]'::jsonb);
END $$;

CREATE OR REPLACE FUNCTION public.cancel_internal_booking(_booking_id uuid, _reason text DEFAULT NULL, _tenant_id uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _caller uuid := auth.uid(); _row public.internal_bookings%ROWTYPE;
BEGIN
  SELECT * INTO _row FROM public.internal_bookings WHERE id=_booking_id FOR UPDATE;
  IF _row.id IS NULL THEN RAISE EXCEPTION 'BOOKING_NOT_FOUND' USING ERRCODE='P0002'; END IF;
  IF _caller IS NOT NULL THEN
    IF NOT (_row.tenant_id = public.current_user_tenant_id() OR public.is_platform_owner()) THEN RAISE EXCEPTION 'BOOKING_FORBIDDEN: wrong tenant' USING ERRCODE='42501'; END IF;
    IF NOT (public.has_any_role(_caller, ARRAY['admin','super_admin','coach']) OR _row.host_user_id = _caller) THEN RAISE EXCEPTION 'BOOKING_FORBIDDEN: admin, coach, or host required' USING ERRCODE='42501'; END IF;
  ELSIF _tenant_id IS NOT NULL AND _tenant_id <> _row.tenant_id THEN RAISE EXCEPTION 'BOOKING_FORBIDDEN: tenant mismatch' USING ERRCODE='42501'; END IF;
  UPDATE public.internal_bookings SET status='cancelled', cancelled_at=now(), cancelled_by=_caller, cancellation_reason=_reason WHERE id=_booking_id;
  INSERT INTO public.audit_logs(user_id, entity, action, entity_id, data)
  VALUES (_caller,'internal_booking','cancel_internal_booking',_booking_id, jsonb_build_object('tenant_id',_row.tenant_id,'reason',_reason));
  RETURN jsonb_build_object('ok',true,'booking_id',_booking_id,'status','cancelled');
END $$;

CREATE OR REPLACE FUNCTION public.reschedule_internal_booking(_booking_id uuid, _start_at timestamptz, _end_at timestamptz, _tenant_id uuid DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _caller uuid := auth.uid(); _row public.internal_bookings%ROWTYPE;
BEGIN
  SELECT * INTO _row FROM public.internal_bookings WHERE id=_booking_id FOR UPDATE;
  IF _row.id IS NULL THEN RAISE EXCEPTION 'BOOKING_NOT_FOUND' USING ERRCODE='P0002'; END IF;
  IF _caller IS NOT NULL THEN
    IF NOT (_row.tenant_id = public.current_user_tenant_id() OR public.is_platform_owner()) THEN RAISE EXCEPTION 'BOOKING_FORBIDDEN: wrong tenant' USING ERRCODE='42501'; END IF;
    IF NOT (public.has_any_role(_caller, ARRAY['admin','super_admin','coach']) OR _row.host_user_id = _caller) THEN RAISE EXCEPTION 'BOOKING_FORBIDDEN: admin, coach, or host required' USING ERRCODE='42501'; END IF;
  ELSIF _tenant_id IS NOT NULL AND _tenant_id <> _row.tenant_id THEN RAISE EXCEPTION 'BOOKING_FORBIDDEN: tenant mismatch' USING ERRCODE='42501'; END IF;
  IF _end_at <= _start_at THEN RAISE EXCEPTION 'BOOKING_BAD_TIME: end must be after start' USING ERRCODE='22023'; END IF;
  UPDATE public.internal_bookings SET start_at=_start_at, end_at=_end_at WHERE id=_booking_id;
  INSERT INTO public.audit_logs(user_id, entity, action, entity_id, data)
  VALUES (_caller,'internal_booking','reschedule_internal_booking',_booking_id, jsonb_build_object('tenant_id',_row.tenant_id,'start_at',_start_at));
  RETURN jsonb_build_object('ok',true,'booking_id',_booking_id,'start_at',_start_at,'end_at',_end_at);
END $$;

REVOKE ALL ON FUNCTION public.plan_create(text,text,date,date,text,uuid,text,jsonb,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.plan_create(text,text,date,date,text,uuid,text,jsonb,uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.plan_add_milestone(uuid,text,text,timestamptz,uuid,text,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.plan_add_milestone(uuid,text,text,timestamptz,uuid,text,uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.plan_assign_task(text,uuid,uuid,uuid,timestamptz,text,text,uuid,jsonb,boolean,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.plan_assign_task(text,uuid,uuid,uuid,timestamptz,text,text,uuid,jsonb,boolean,uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.plan_set_reminder(text,timestamptz,text,uuid,text,uuid,text,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.plan_set_reminder(text,timestamptz,text,uuid,text,uuid,text,uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.plan_update_item(uuid,text,text,text,timestamptz,timestamptz,text,uuid,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.plan_update_item(uuid,text,text,text,timestamptz,timestamptz,text,uuid,uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.plan_remove_item(uuid,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.plan_remove_item(uuid,uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.plan_list(text,uuid,text,uuid,date,date,int,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.plan_list(text,uuid,text,uuid,date,date,int,uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.cancel_internal_booking(uuid,text,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.cancel_internal_booking(uuid,text,uuid) TO authenticated, service_role;
REVOKE ALL ON FUNCTION public.reschedule_internal_booking(uuid,timestamptz,timestamptz,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.reschedule_internal_booking(uuid,timestamptz,timestamptz,uuid) TO authenticated, service_role;

