-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260714180743 (marketplace_bundle_refcount_5_public_rpcs)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260714180743 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Wave 1 chunk 5/5: public install/uninstall RPCs (signature preserved) + refcount read seam
CREATE OR REPLACE FUNCTION public.install_marketplace_item(
  _tenant_id uuid,
  _item_slug text,
  _seeded_kb_doc_ids uuid[] DEFAULT '{}'::uuid[],
  _installed_by_agent text DEFAULT NULL
) RETURNS jsonb
 LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  _is_owner boolean := public.is_platform_owner();
  _res      jsonb;
  _deferred jsonb;
BEGIN
  IF NOT (_is_owner OR public.is_tenant_admin(_tenant_id)) THEN
    RAISE EXCEPTION 'not authorized to install for this tenant' USING ERRCODE = '42501';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended('mp_install:' || _tenant_id::text, 0));

  _res := public._marketplace_install_node(
    _tenant_id, _item_slug, _is_owner,
    COALESCE(_seeded_kb_doc_ids, '{}'::uuid[]), _installed_by_agent,
    NULL, ARRAY[]::text[]);

  -- Present ONE flat, complete children_deferred_embedding for the edge function:
  -- every embedding-pending node at any depth (nested aggregated by the node; the
  -- TOP node itself added here when IT is a pending kb-carrying item — LOW-2).
  _deferred := COALESCE(_res->'children_deferred_embedding', '[]'::jsonb);
  IF COALESCE((_res->>'needs_embedding')::boolean, false) THEN
    _deferred := jsonb_build_array(jsonb_build_object(
      'item_slug', _res->>'item_slug',
      'install_id', _res->>'install_id',
      'via_bundle_install_id', NULL))
      || _deferred;
  END IF;

  RETURN jsonb_set(_res, '{children_deferred_embedding}', _deferred);
END $function$;
REVOKE ALL ON FUNCTION public.install_marketplace_item(uuid, text, uuid[], text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.install_marketplace_item(uuid, text, uuid[], text) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.uninstall_marketplace_item(
  _tenant_id uuid,
  _item_slug text
) RETURNS jsonb
 LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  _item    public.marketplace_items%ROWTYPE;
  _install public.marketplace_installs%ROWTYPE;
  _holds   integer;
  _td      jsonb;
BEGIN
  IF NOT (public.is_platform_owner() OR public.is_tenant_admin(_tenant_id)) THEN
    RAISE EXCEPTION 'not authorized to uninstall for this tenant' USING ERRCODE = '42501';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended('mp_install:' || _tenant_id::text, 0));

  SELECT * INTO _item FROM public.marketplace_items WHERE slug = _item_slug;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'marketplace item % not found', _item_slug USING ERRCODE = 'no_data_found';
  END IF;

  SELECT * INTO _install FROM public.marketplace_installs
   WHERE tenant_id = _tenant_id AND item_id = _item.id;
  IF NOT FOUND OR _install.status = 'uninstalled' THEN
    RETURN jsonb_build_object('ok', true, 'was_installed', false, 'item_slug', _item.slug);
  END IF;

  -- Release the tenant's DIRECT hold. If any active bundle still holds this item,
  -- retain its effects (reference count in action).
  UPDATE public.marketplace_installs SET held_directly = false WHERE id = _install.id;
  _holds := public._marketplace_active_bundle_holds(_install.id);

  IF _holds > 0 THEN
    RETURN jsonb_build_object(
      'ok', true, 'was_installed', true, 'item_slug', _item.slug,
      'retained', true, 'bundle_holds', _holds,
      'retained_reason', format('effects retained: still held by %s active bundle(s)', _holds),
      'skills_disabled', '[]'::jsonb, 'kb_docs_removed', 0);
  END IF;

  _td := public._marketplace_teardown_install(_tenant_id, _install.id);
  RETURN jsonb_build_object(
    'ok', true, 'was_installed', true, 'item_slug', _item.slug,
    'retained', false,
    'skills_disabled', COALESCE(_td->'skills_disabled','[]'::jsonb),
    'kb_docs_removed', COALESCE((_td->>'kb_docs_removed')::int, 0),
    'children_torn_down', COALESCE(_td->'children','[]'::jsonb));
END $function$;
REVOKE ALL ON FUNCTION public.uninstall_marketplace_item(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.uninstall_marketplace_item(uuid, text) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.marketplace_install_refcount(
  _tenant_id uuid, _item_slug text
) RETURNS jsonb
 LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE _install public.marketplace_installs%ROWTYPE; _holds int; _bundles jsonb;
BEGIN
  IF NOT (public.is_platform_owner() OR public.is_tenant_admin(_tenant_id)) THEN
    RAISE EXCEPTION 'not authorized to read this tenant''s installs' USING ERRCODE = '42501';
  END IF;
  SELECT mi.* INTO _install FROM public.marketplace_installs mi
    JOIN public.marketplace_items i ON i.id = mi.item_id
   WHERE mi.tenant_id = _tenant_id AND i.slug = _item_slug;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('installed', false, 'item_slug', _item_slug);
  END IF;
  _holds := public._marketplace_active_bundle_holds(_install.id);
  SELECT COALESCE(jsonb_agg(jsonb_build_object(
           'bundle_install_id', l.bundle_install_id, 'bundle_slug', bi_item.slug)), '[]'::jsonb)
    INTO _bundles
    FROM public.marketplace_install_bundle_links l
    JOIN public.marketplace_installs bi ON bi.id = l.bundle_install_id AND bi.status = 'active'
    JOIN public.marketplace_items bi_item ON bi_item.id = bi.item_id
   WHERE l.child_install_id = _install.id;
  RETURN jsonb_build_object(
    'installed', _install.status = 'active',
    'item_slug', _item_slug,
    'status', _install.status,
    'held_directly', _install.held_directly,
    'active_bundle_holds', _holds,
    'refcount', (CASE WHEN _install.held_directly THEN 1 ELSE 0 END) + _holds,
    'held_by_bundles', _bundles,
    'embedding_pending', COALESCE((_install.seeded_refs->>'embedding_pending')::boolean, false));
END $function$;
REVOKE ALL ON FUNCTION public.marketplace_install_refcount(uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.marketplace_install_refcount(uuid, text) TO authenticated, service_role;
