-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260710002222 (intake_playbook_section)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260710002222 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

ALTER TABLE public.paige_client_intake_submissions
  DROP CONSTRAINT IF EXISTS paige_client_intake_submissions_section_check;
ALTER TABLE public.paige_client_intake_submissions
  ADD CONSTRAINT paige_client_intake_submissions_section_check
  CHECK (section IN ('about_you', 'business', 'current_state', 'docs_checklist', 'playbook_intake'));
