-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260713030834 (invite_brand_cascade)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260713030834 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.peek_tenant_invite(_token text)
RETURNS TABLE (
  tenant_id uuid,
  tenant_name text,
  tenant_slug text,
  brand jsonb,
  kind text,
  default_role public.tenant_role,
  expires_at timestamptz,
  is_valid boolean,
  invited_email text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _tok public.tenant_invite_tokens;
  _ten public.tenants;
  _rb  record;
BEGIN
  SELECT * INTO _tok FROM public.tenant_invite_tokens WHERE token = _token;
  IF NOT FOUND THEN
    RETURN;
  END IF;
  SELECT * INTO _ten FROM public.tenants WHERE id = _tok.tenant_id;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  SELECT * INTO _rb FROM public.resolve_tenant_brand(_ten.id);

  tenant_id     := _ten.id;
  tenant_name   := _ten.name;
  tenant_slug   := _ten.slug;
  brand         := jsonb_build_object(
                     'logo_url',      _rb.logo_url,
                     'logo_dark_url', _rb.logo_dark_url,
                     'primary_color', _rb.primary_color,
                     'accent_color',  _rb.accent_color
                   );
  kind          := _tok.kind;
  default_role  := _tok.default_role;
  expires_at    := _tok.expires_at;
  invited_email := _tok.email;
  is_valid      := (_tok.revoked_at IS NULL)
                   AND (_tok.expires_at > now())
                   AND (_tok.max_uses IS NULL OR _tok.uses < _tok.max_uses);
  RETURN NEXT;
END $$;

REVOKE ALL ON FUNCTION public.peek_tenant_invite(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.peek_tenant_invite(text) TO anon, authenticated;
