-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712211049 (public_rate_limits)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712211049 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.public_rate_limits (
  bucket        text        NOT NULL,
  window_start  timestamptz NOT NULL,
  request_count int         NOT NULL DEFAULT 0,
  PRIMARY KEY (bucket, window_start)
);
CREATE INDEX IF NOT EXISTS idx_public_rate_limits_window
  ON public.public_rate_limits (window_start);
ALTER TABLE public.public_rate_limits ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "public_rate_limits service role only" ON public.public_rate_limits;
CREATE POLICY "public_rate_limits service role only"
  ON public.public_rate_limits FOR ALL TO service_role
  USING (true) WITH CHECK (true);
CREATE OR REPLACE FUNCTION public.check_public_rate_limit(
  _bucket text, _max int DEFAULT 60, _window_seconds int DEFAULT 60
) RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _win timestamptz; _count int;
BEGIN
  IF _bucket IS NULL OR _bucket = '' THEN RETURN true; END IF;
  IF _window_seconds < 1 THEN _window_seconds := 60; END IF;
  _win := to_timestamp(floor(extract(epoch FROM now()) / _window_seconds) * _window_seconds);
  INSERT INTO public.public_rate_limits (bucket, window_start, request_count)
  VALUES (_bucket, _win, 1)
  ON CONFLICT (bucket, window_start)
  DO UPDATE SET request_count = public.public_rate_limits.request_count + 1
  RETURNING request_count INTO _count;
  RETURN _count <= _max;
END; $$;
GRANT EXECUTE ON FUNCTION public.check_public_rate_limit(text, int, int) TO service_role;
