-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260714180712 (marketplace_bundle_refcount_4_install_node)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260714180712 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Wave 1 chunk 4/5: recursive install-node (leaf or bundle) with fan-out + refcount provenance
CREATE OR REPLACE FUNCTION public._marketplace_install_node(
  _tenant_id uuid, _item_slug text, _is_owner boolean, _seeded_kb_doc_ids uuid[],
  _installed_by_agent text, _parent_install_id uuid, _path text[]
) RETURNS jsonb
 LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
DECLARE
  _item        public.marketplace_items%ROWTYPE;
  _ver         public.marketplace_item_versions%ROWTYPE;
  _existing    public.marketplace_installs%ROWTYPE;
  _install     public.marketplace_installs%ROWTYPE;
  _had_row     boolean := false;
  _was_active  boolean := false;
  _pending     boolean := false;
  _needs_embed boolean := false;
  _fn          jsonb;
  _kind        text;
  _skill_slugs text[] := '{}';
  _skipped     jsonb := '[]'::jsonb;
  _seeded_refs jsonb;
  _held        boolean := (_parent_install_id IS NULL);
  _child_slug  text;
  _child_res   jsonb;
  _children    jsonb := '[]'::jsonb;
  _deferred    jsonb := '[]'::jsonb;
  _reconciled  integer := 0;
  _gross integer := 0; _fee integer := 0; _net integer := 0;
BEGIN
  IF _item_slug = ANY (_path) THEN
    RAISE EXCEPTION 'bundle cycle detected: % already on install path %', _item_slug, _path
      USING ERRCODE = '22023';
  END IF;
  IF COALESCE(array_length(_path,1),0) >= 8 THEN
    RAISE EXCEPTION 'bundle nesting exceeds max depth (8) at %', _item_slug USING ERRCODE = '22023';
  END IF;

  SELECT * INTO _item FROM public.marketplace_items WHERE slug = _item_slug;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'marketplace item % not found', _item_slug USING ERRCODE = 'no_data_found';
  END IF;

  IF NOT _is_owner AND _item.status <> 'listed' THEN
    RAISE EXCEPTION 'marketplace item % is not available', _item_slug USING ERRCODE = '42501';
  END IF;
  IF _item.scope = 'tenant' AND _item.visible_to_tenant_id IS DISTINCT FROM _tenant_id THEN
    RAISE EXCEPTION 'marketplace item % is scoped to another tenant and cannot be installed here', _item_slug
      USING ERRCODE = '42501';
  ELSIF _item.scope = 'agency'
        AND NOT (_is_owner OR public.agency_team_role(_item.visible_to_agency_id, auth.uid()) IS NOT NULL) THEN
    RAISE EXCEPTION 'marketplace item % is not visible to this tenant', _item_slug USING ERRCODE = '42501';
  END IF;

  IF _item.current_version_id IS NULL THEN
    RAISE EXCEPTION 'marketplace item % has no published version', _item_slug USING ERRCODE = 'no_data_found';
  END IF;
  SELECT * INTO _ver FROM public.marketplace_item_versions WHERE id = _item.current_version_id;

  SELECT * INTO _existing FROM public.marketplace_installs
   WHERE tenant_id = _tenant_id AND item_id = _item.id;
  _had_row := FOUND;
  _was_active := FOUND AND _existing.status = 'active';
  _needs_embed := (_ver.install_manifest ? 'kb_pack')
                  AND COALESCE(array_length(_seeded_kb_doc_ids,1),0) = 0;

  IF _was_active THEN
    _pending := COALESCE((_existing.seeded_refs->>'embedding_pending')::boolean, false);

    -- Edge-function finalize (held_directly deliberately preserved: the only caller
    -- supplying doc ids is the edge fn completing a bundle child; the genuine
    -- tenant-standalone-of-pending case arrives with NO doc ids and takes the
    -- already_active branch below, which upgrades held_directly).
    IF _pending AND COALESCE(array_length(_seeded_kb_doc_ids,1),0) > 0 THEN
      DELETE FROM public.tenant_knowledge_docs
       WHERE tenant_id = _tenant_id
         AND tags @> ARRAY['marketplace:' || _item.slug]
         AND NOT (id = ANY (_seeded_kb_doc_ids));
      GET DIAGNOSTICS _reconciled = ROW_COUNT;
      UPDATE public.marketplace_installs
         SET seeded_refs = jsonb_set(
               jsonb_set(seeded_refs, '{kb_doc_ids}', to_jsonb(_seeded_kb_doc_ids)),
               '{embedding_pending}', 'false'::jsonb),
             version_id = _ver.id
       WHERE id = _existing.id
       RETURNING * INTO _install;
      RETURN jsonb_build_object(
        'ok', true, 'already_installed', true, 'status', 'finalized',
        'item_slug', _item.slug, 'item_type', _item.item_type, 'version', _ver.semver,
        'skills_enabled', COALESCE(_existing.seeded_refs->'skill_slugs','[]'::jsonb),
        'kb_docs_seeded', COALESCE(array_length(_seeded_kb_doc_ids,1),0),
        'needs_embedding', false, 'reconciled_orphans', _reconciled,
        'skipped_functions', '[]'::jsonb, 'warning', NULL,
        'seeded_refs', _install.seeded_refs, 'install_id', _install.id, 'children', '[]'::jsonb);
    END IF;

    -- Genuine idempotent no-op (bundle re-install does NOT re-walk manifest; version
    -- changes route through the update_available path). Two provenance touch-ups:
    IF _parent_install_id IS NULL AND NOT _existing.held_directly THEN
      UPDATE public.marketplace_installs SET held_directly = true WHERE id = _existing.id;
    END IF;
    IF _parent_install_id IS NOT NULL THEN
      INSERT INTO public.marketplace_install_bundle_links
        (bundle_install_id, child_install_id, tenant_id, child_item_slug)
      VALUES (_parent_install_id, _existing.id, _tenant_id, _item.slug)
      ON CONFLICT (bundle_install_id, child_install_id) DO NOTHING;
    END IF;

    RETURN jsonb_build_object(
      'ok', true, 'already_installed', true, 'status', 'already_active',
      'item_slug', _item.slug, 'item_type', _item.item_type, 'version', _ver.semver,
      'needs_embedding', _pending, 'seeded_refs', _existing.seeded_refs,
      'install_id', _existing.id, 'children', '[]'::jsonb);
  END IF;

  FOR _fn IN SELECT * FROM jsonb_array_elements(COALESCE(_ver.install_manifest->'functions','[]'::jsonb))
  LOOP
    _kind := _fn->>'kind';
    IF _kind = 'skill_flag' AND (_fn->>'slug') IS NOT NULL THEN
      PERFORM public.set_tenant_skill(_tenant_id, _fn->>'slug', true);
      _skill_slugs := array_append(_skill_slugs, _fn->>'slug');
    ELSE
      _skipped := _skipped || jsonb_build_array(_fn);
    END IF;
  END LOOP;

  -- Reconcile ONLY when a winning doc set is supplied (empty set = deferred fan-out
  -- child; reconcile is done later in the finalize branch, never wiping embedded docs).
  IF array_length(_seeded_kb_doc_ids, 1) IS NOT NULL THEN
    DELETE FROM public.tenant_knowledge_docs
     WHERE tenant_id = _tenant_id
       AND tags @> ARRAY['marketplace:' || _item.slug]
       AND NOT (id = ANY (_seeded_kb_doc_ids));
    GET DIAGNOSTICS _reconciled = ROW_COUNT;
  END IF;

  _seeded_refs := jsonb_build_object(
    'skill_slugs', to_jsonb(_skill_slugs),
    'kb_doc_ids', to_jsonb(COALESCE(_seeded_kb_doc_ids, '{}'::uuid[])),
    'portal_surface_slugs', '[]'::jsonb,
    'features_keys', '[]'::jsonb,
    'embedding_pending', _needs_embed
  );

  INSERT INTO public.marketplace_installs
    (tenant_id, item_id, version_id, status, seeded_refs, held_directly,
     installed_by, installed_by_agent, installed_at, uninstalled_at)
  VALUES
    (_tenant_id, _item.id, _ver.id, 'active', _seeded_refs, _held,
     auth.uid(), _installed_by_agent, now(), NULL)
  ON CONFLICT (tenant_id, item_id) DO UPDATE
    SET version_id = EXCLUDED.version_id,
        status = 'active',
        seeded_refs = EXCLUDED.seeded_refs,
        held_directly = CASE WHEN _parent_install_id IS NULL
                             THEN true ELSE public.marketplace_installs.held_directly END,
        installed_by = EXCLUDED.installed_by,
        installed_by_agent = EXCLUDED.installed_by_agent,
        installed_at = now(),
        uninstalled_at = NULL
  RETURNING * INTO _install;

  IF (NOT _had_row) OR _existing.status = 'uninstalled' THEN
    UPDATE public.marketplace_items SET install_count = install_count + 1 WHERE id = _item.id;
  END IF;

  -- §17 ledger: direct install captures the sale; a fan-out child is billed ZERO
  -- (the purchased bundle captured the money — no GMV double-count / vendor over-credit).
  IF _parent_install_id IS NULL THEN
    _gross := COALESCE(_item.price_cents, 0);
  ELSE
    _gross := 0;
  END IF;
  _fee := (_gross * COALESCE(_item.take_rate_bps, 0)) / 10000;
  _net := _gross - _fee;
  INSERT INTO public.marketplace_install_ledger
    (install_id, item_id, vendor_id, tenant_id, event_type, gross_cents, take_rate_bps, platform_fee_cents, vendor_net_cents)
  VALUES
    (_install.id, _item.id, _item.vendor_id, _tenant_id, 'install', _gross,
     CASE WHEN _gross = 0 THEN 0 ELSE COALESCE(_item.take_rate_bps,0) END, _fee, _net);

  IF _parent_install_id IS NOT NULL THEN
    INSERT INTO public.marketplace_install_bundle_links
      (bundle_install_id, child_install_id, tenant_id, child_item_slug)
    VALUES (_parent_install_id, _install.id, _tenant_id, _item.slug)
    ON CONFLICT (bundle_install_id, child_install_id) DO NOTHING;
  END IF;

  IF _item.item_type = 'bundle' THEN
    FOR _child_slug IN
      SELECT jsonb_array_elements_text(COALESCE(_ver.install_manifest->'bundle_items','[]'::jsonb))
    LOOP
      _child_res := public._marketplace_install_node(
        _tenant_id, _child_slug, _is_owner, '{}'::uuid[], _installed_by_agent,
        _install.id, _path || _item.slug);
      _children := _children || jsonb_build_array(_child_res);
      IF COALESCE((_child_res->>'needs_embedding')::boolean, false) THEN
        _deferred := _deferred || jsonb_build_array(jsonb_build_object(
          'item_slug', _child_res->>'item_slug',
          'install_id', _child_res->>'install_id',
          'via_bundle_install_id', _install.id));
      END IF;
      -- Bubble up a nested (grandchild) deferral so the top-level flat list is complete.
      _deferred := _deferred || COALESCE(_child_res->'children_deferred_embedding', '[]'::jsonb);
    END LOOP;
  END IF;

  RETURN jsonb_build_object(
    'ok', true,
    'already_installed', false,
    'status', CASE WHEN _needs_embed THEN 'deferred_embedding' ELSE 'installed' END,
    'item_slug', _item.slug,
    'item_type', _item.item_type,
    'version', _ver.semver,
    'skills_enabled', to_jsonb(_skill_slugs),
    'kb_docs_seeded', COALESCE(array_length(_seeded_kb_doc_ids,1),0),
    'needs_embedding', _needs_embed,
    'reconciled_orphans', _reconciled,
    'skipped_functions', _skipped,
    'warning', CASE WHEN _needs_embed THEN
        'Knowledge pack must be embedded by the marketplace-install edge function; skills were enabled and the install is recorded as embedding_pending.'
      ELSE NULL END,
    'seeded_refs', _install.seeded_refs,
    'install_id', _install.id,
    'children', _children,
    'children_deferred_embedding', _deferred);
END $function$;
REVOKE ALL ON FUNCTION public._marketplace_install_node(uuid, text, boolean, uuid[], text, uuid, text[]) FROM PUBLIC;
