-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260708174151 (platform_staff_foundation)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260708174151 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Platform staff foundation (God tier) — scoped Platform Admin + invite flow.
DROP POLICY IF EXISTS "Platform staff read all tenants" ON public.tenants;
CREATE POLICY "Platform staff read all tenants" ON public.tenants
  FOR SELECT TO authenticated USING (public.is_platform_admin());

DROP POLICY IF EXISTS "Platform staff update tenants" ON public.tenants;
CREATE POLICY "Platform staff update tenants" ON public.tenants
  FOR UPDATE TO authenticated
  USING (public.is_platform_admin())
  WITH CHECK (public.is_platform_admin());

CREATE OR REPLACE FUNCTION public.guard_tenant_owner_only_columns()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
BEGIN
  IF auth.uid() IS NULL OR public.is_platform_owner() THEN
    RETURN NEW;
  END IF;
  IF NEW.owner_user_id       IS DISTINCT FROM OLD.owner_user_id
     OR NEW.platform_fee_bps IS DISTINCT FROM OLD.platform_fee_bps
     OR NEW.parent_tenant_id IS DISTINCT FROM OLD.parent_tenant_id
     OR NEW.stripe_customer_id     IS DISTINCT FROM OLD.stripe_customer_id
     OR NEW.stripe_subscription_id IS DISTINCT FROM OLD.stripe_subscription_id THEN
    RAISE EXCEPTION 'Only the platform owner may change tenant ownership, billing, or hierarchy';
  END IF;
  RETURN NEW;
END; $$;

DROP TRIGGER IF EXISTS trg_guard_tenant_owner_cols ON public.tenants;
CREATE TRIGGER trg_guard_tenant_owner_cols
  BEFORE UPDATE ON public.tenants
  FOR EACH ROW EXECUTE FUNCTION public.guard_tenant_owner_only_columns();

CREATE TABLE IF NOT EXISTS public.platform_invites (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email            text NOT NULL,
  role             public.app_role NOT NULL DEFAULT 'platform_admin',
  token            text NOT NULL UNIQUE,
  status           text NOT NULL DEFAULT 'pending',
  invited_by       uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  accepted_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at       timestamptz NOT NULL DEFAULT now(),
  expires_at       timestamptz NOT NULL DEFAULT (now() + interval '14 days'),
  accepted_at      timestamptz
);
CREATE INDEX IF NOT EXISTS platform_invites_email_idx ON public.platform_invites (lower(email));
ALTER TABLE public.platform_invites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Owner manages platform invites" ON public.platform_invites;
CREATE POLICY "Owner manages platform invites" ON public.platform_invites
  FOR ALL TO authenticated
  USING (public.is_platform_owner())
  WITH CHECK (public.is_platform_owner());

CREATE OR REPLACE FUNCTION public.create_platform_invite(
  _email text,
  _role  public.app_role DEFAULT 'platform_admin'
)
RETURNS public.platform_invites
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE _row public.platform_invites; _token text;
BEGIN
  IF NOT public.is_platform_owner() THEN RAISE EXCEPTION 'Owner privileges required'; END IF;
  IF _role <> 'platform_admin' THEN RAISE EXCEPTION 'Only platform_admin may be invited'; END IF;
  IF _email IS NULL OR position('@' in _email) = 0 THEN RAISE EXCEPTION 'Valid email required'; END IF;

  _token := replace(gen_random_uuid()::text, '-', '') || replace(gen_random_uuid()::text, '-', '');

  UPDATE public.platform_invites SET status = 'revoked'
   WHERE lower(email) = lower(_email) AND status = 'pending';

  INSERT INTO public.platform_invites (email, role, token, invited_by)
       VALUES (lower(_email), _role, _token, auth.uid())
    RETURNING * INTO _row;

  INSERT INTO public.audit_logs (user_id, entity, action, entity_id, data)
       VALUES (auth.uid(), 'platform_invite', 'create', _row.id,
               jsonb_build_object('email', lower(_email), 'role', _role));
  RETURN _row;
END; $$;

CREATE OR REPLACE FUNCTION public.accept_platform_invite(_token text)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE _inv public.platform_invites; _uid uuid := auth.uid(); _email text;
BEGIN
  IF _uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  SELECT email INTO _email FROM auth.users WHERE id = _uid;

  SELECT * INTO _inv FROM public.platform_invites WHERE token = _token FOR UPDATE;
  IF _inv.id IS NULL THEN RAISE EXCEPTION 'Invite not found'; END IF;
  IF _inv.status <> 'pending' THEN RAISE EXCEPTION 'Invite is %', _inv.status; END IF;
  IF _inv.expires_at < now() THEN
    UPDATE public.platform_invites SET status = 'expired' WHERE id = _inv.id;
    RAISE EXCEPTION 'Invite expired';
  END IF;
  IF _email IS NULL OR lower(_inv.email) <> lower(_email) THEN
    RAISE EXCEPTION 'Invite is for a different email';
  END IF;
  IF _inv.role <> 'platform_admin' THEN RAISE EXCEPTION 'Unsupported invite role'; END IF;

  INSERT INTO public.user_roles (user_id, role)
       VALUES (_uid, _inv.role)
  ON CONFLICT (user_id, role) DO NOTHING;

  UPDATE public.platform_invites
     SET status = 'accepted', accepted_user_id = _uid, accepted_at = now()
   WHERE id = _inv.id;

  INSERT INTO public.audit_logs (user_id, entity, action, entity_id, data)
       VALUES (_uid, 'platform_invite', 'accept', _inv.id, jsonb_build_object('role', _inv.role));
  RETURN jsonb_build_object('ok', true, 'role', _inv.role);
END; $$;

CREATE OR REPLACE FUNCTION public.revoke_platform_admin(_user_id uuid)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
BEGIN
  IF NOT public.is_platform_owner() THEN RAISE EXCEPTION 'Owner privileges required'; END IF;
  IF public.is_super_admin(_user_id) THEN RAISE EXCEPTION 'Cannot revoke an owner'; END IF;
  DELETE FROM public.user_roles WHERE user_id = _user_id AND role = 'platform_admin';
  INSERT INTO public.audit_logs (user_id, entity, action, entity_id, data)
       VALUES (auth.uid(), 'user', 'revoke_platform_admin', _user_id,
               jsonb_build_object('revoked_by', auth.uid()));
END; $$;

CREATE OR REPLACE FUNCTION public.list_platform_staff()
RETURNS TABLE(user_id uuid, email text, full_name text, role text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
BEGIN
  IF NOT public.is_platform_admin() THEN RAISE EXCEPTION 'Platform access required'; END IF;
  RETURN QUERY
    SELECT ur.user_id, u.email::text,
           (u.raw_user_meta_data->>'full_name')::text, ur.role::text
      FROM public.user_roles ur
      JOIN auth.users u ON u.id = ur.user_id
     WHERE ur.role IN ('super_admin', 'platform_admin')
     ORDER BY ur.role, u.email;
END; $$;

GRANT EXECUTE ON FUNCTION public.create_platform_invite(text, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.accept_platform_invite(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.revoke_platform_admin(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.list_platform_staff() TO authenticated;
