-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712211043 (per_host_availability)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712211043 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

ALTER TABLE public.calendar_hosts
  ADD COLUMN IF NOT EXISTS availability_json jsonb,
  ADD COLUMN IF NOT EXISTS timezone text;

COMMENT ON COLUMN public.calendar_hosts.availability_json IS
  'Per-host weekly windows [{day,start,end}]. NULL = inherit calendars.availability_json. An empty array means the host keeps no hours on this calendar (offered no slots), which is distinct from NULL/inherit.';
COMMENT ON COLUMN public.calendar_hosts.timezone IS
  'Per-host IANA timezone for interpreting availability_json. NULL = inherit calendars.timezone.';

CREATE OR REPLACE FUNCTION public.set_calendar_hosts(_cal uuid, _hosts jsonb)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _tenant uuid; _bad int;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'CALENDAR_FORBIDDEN: auth required' USING ERRCODE='42501'; END IF;
  IF NOT public.can_manage_calendar(_cal) THEN RAISE EXCEPTION 'CALENDAR_FORBIDDEN' USING ERRCODE='42501'; END IF;
  IF _hosts IS NULL OR jsonb_typeof(_hosts) <> 'array' OR jsonb_array_length(_hosts) < 1 THEN
    RAISE EXCEPTION 'HOSTS_REQUIRED: at least one host' USING ERRCODE='22023';
  END IF;

  SELECT tenant_id INTO _tenant FROM public.calendars WHERE id = _cal;

  IF _tenant IS NOT NULL THEN
    SELECT count(*) INTO _bad
      FROM jsonb_array_elements(_hosts) h
     WHERE NOT EXISTS (
       SELECT 1 FROM public.tenant_members tm
        WHERE tm.tenant_id = _tenant
          AND tm.user_id = (h->>'user_id')::uuid
          AND tm.status = 'active'
     );
    IF _bad > 0 THEN
      RAISE EXCEPTION 'HOST_NOT_ELIGIBLE: % host(s) are not active members of this tenant', _bad USING ERRCODE='22023';
    END IF;
  END IF;

  DELETE FROM public.calendar_hosts WHERE calendar_id = _cal;
  INSERT INTO public.calendar_hosts (calendar_id, user_id, priority, availability_json, timezone)
  SELECT DISTINCT ON ((h->>'user_id')::uuid)
         _cal,
         (h->>'user_id')::uuid,
         (ord - 1)::int,
         CASE WHEN jsonb_typeof(h->'availability_json') = 'array' THEN h->'availability_json' ELSE NULL END,
         NULLIF(btrim(h->>'timezone'), '')
    FROM jsonb_array_elements(_hosts) WITH ORDINALITY AS t(h, ord)
   ORDER BY (h->>'user_id')::uuid, ord;
END $$;

REVOKE ALL ON FUNCTION public.set_calendar_hosts(uuid, jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_calendar_hosts(uuid, jsonb) TO authenticated, service_role;
