-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712231157 (paige_deep_research)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712231157 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================


CREATE TABLE IF NOT EXISTS public.research_runs (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid NOT NULL,
  client_user_id uuid,
  question       text NOT NULL,
  domain         text NOT NULL DEFAULT 'general',
  caller         text NOT NULL DEFAULT 'chat',
  findings       jsonb NOT NULL DEFAULT '[]'::jsonb,
  coverage       jsonb NOT NULL DEFAULT '{}'::jsonb,
  stop_reason    text,
  configured     boolean NOT NULL DEFAULT true,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.research_sources (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id            uuid NOT NULL REFERENCES public.research_runs(id) ON DELETE CASCADE,
  user_id           uuid NOT NULL,
  source_index      int  NOT NULL,
  url               text NOT NULL,
  title             text,
  snippet           text,
  reliability_score numeric(4,3) NOT NULL DEFAULT 0,
  tier              text,
  reliability       text,
  published_at      timestamptz,
  fetched_at        timestamptz NOT NULL DEFAULT now(),
  excluded          boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS research_runs_user_idx   ON public.research_runs(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS research_sources_run_idx ON public.research_sources(run_id, source_index);

ALTER TABLE public.research_runs    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.research_sources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage all research runs" ON public.research_runs
  FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Coaches can manage own research runs" ON public.research_runs
  FOR ALL USING ((auth.uid() = user_id) AND has_role(auth.uid(), 'coach'::app_role));
CREATE POLICY "Users can view runs saved to their profile" ON public.research_runs
  FOR SELECT USING (auth.uid() = client_user_id);
CREATE POLICY "Service role can manage all research runs" ON public.research_runs
  FOR ALL USING (auth.role() = 'service_role'::text) WITH CHECK (auth.role() = 'service_role'::text);

CREATE POLICY "Admins can manage all research sources" ON public.research_sources
  FOR ALL USING (has_role(auth.uid(), 'admin'::app_role));
CREATE POLICY "Coaches can manage own research sources" ON public.research_sources
  FOR ALL USING ((auth.uid() = user_id) AND has_role(auth.uid(), 'coach'::app_role));
CREATE POLICY "Users can view sources saved to their profile" ON public.research_sources
  FOR SELECT USING (EXISTS (
    SELECT 1 FROM public.research_runs r
    WHERE r.id = research_sources.run_id AND r.client_user_id = auth.uid()
  ));
CREATE POLICY "Service role can manage all research sources" ON public.research_sources
  FOR ALL USING (auth.role() = 'service_role'::text) WITH CHECK (auth.role() = 'service_role'::text);

ALTER TABLE public.lender_research_results
  ADD COLUMN IF NOT EXISTS sources    jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS provenance text  NOT NULL DEFAULT 'unverified_legacy';

UPDATE public.lender_research_results
   SET provenance = 'unverified_legacy'
 WHERE provenance IS NULL OR provenance = '';

