-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260714161507 (marketplace_seam_hardening)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260714161507 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Marketplace Registry Spine — hardening pass (§1/§5 review findings)

ALTER TABLE public.marketplace_items
  ADD COLUMN IF NOT EXISTS is_finance boolean NOT NULL DEFAULT false;
COMMENT ON COLUMN public.marketplace_items.is_finance IS
  'Structural section-2 marker: a finance/credit item. May be LISTED as opt-in but can NEVER be default_for_new_tenants, regardless of display copy.';

UPDATE public.marketplace_items SET is_finance = true WHERE slug = 'funding';

CREATE OR REPLACE FUNCTION public.marketplace_item_guard()
 RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public' AS $function$
DECLARE _hay text; _manifest jsonb;
BEGIN
  IF NEW.default_for_new_tenants THEN
    IF NEW.is_finance THEN
      RAISE EXCEPTION 'A finance/credit marketplace item cannot be a default for new tenants (section 2). It may be listed as an opt-in item only.'
        USING ERRCODE = '22023';
    END IF;
    SELECT install_manifest INTO _manifest
      FROM public.marketplace_item_versions WHERE id = NEW.current_version_id;
    _hay := lower(concat_ws(' ',
      NEW.slug, NEW.name, NEW.tagline, NEW.description, NEW.category,
      coalesce(_manifest::text, '')));
    IF _hay ~ '(credit|funding|lending|lender|loan|financ|capital[- ]rais|tradeline|underwrit|\mdebt\M|merchant cash|cash advance|\mfico\M|collections|business credit|net[- ]?30|grant writ)' THEN
      RAISE EXCEPTION 'This item ships finance/credit content and cannot be a default for new tenants (section 2). List it as an opt-in item, or set is_finance and keep it opt-in.'
        USING ERRCODE = '22023';
    END IF;
  END IF;
  RETURN NEW;
END $function$;

DROP POLICY IF EXISTS mp_items_write ON public.marketplace_items;
CREATE POLICY mp_items_write ON public.marketplace_items FOR ALL TO authenticated
  USING (
    public.is_platform_owner()
    OR EXISTS (SELECT 1 FROM public.marketplace_vendors v
                WHERE v.id = marketplace_items.vendor_id
                  AND v.owner_tenant_id IS NOT NULL
                  AND public.is_tenant_admin(v.owner_tenant_id))
  )
  WITH CHECK (
    public.is_platform_owner()
    OR (
      EXISTS (SELECT 1 FROM public.marketplace_vendors v
               WHERE v.id = marketplace_items.vendor_id
                 AND v.owner_tenant_id IS NOT NULL
                 AND public.is_tenant_admin(v.owner_tenant_id))
      AND origin = 'vendor'
      AND default_for_new_tenants = false
      AND scope IN ('tenant','agency')
    )
  );

CREATE OR REPLACE FUNCTION public.marketplace_items_freeze_privileged()
 RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
BEGIN
  IF current_user IN ('postgres','supabase_admin','service_role') OR public.is_platform_owner() THEN
    RETURN NEW;
  END IF;
  IF NEW.install_count IS DISTINCT FROM OLD.install_count
     OR NEW.rating_avg   IS DISTINCT FROM OLD.rating_avg
     OR NEW.rating_count IS DISTINCT FROM OLD.rating_count
     OR NEW.origin       IS DISTINCT FROM OLD.origin
     OR NEW.default_for_new_tenants IS DISTINCT FROM OLD.default_for_new_tenants
     OR NEW.is_finance   IS DISTINCT FROM OLD.is_finance THEN
    RAISE EXCEPTION 'these marketplace_items columns are managed by the platform and cannot be changed directly'
      USING ERRCODE = '42501';
  END IF;
  RETURN NEW;
END $function$;
DROP TRIGGER IF EXISTS trg_marketplace_items_freeze ON public.marketplace_items;
CREATE TRIGGER trg_marketplace_items_freeze
  BEFORE UPDATE ON public.marketplace_items
  FOR EACH ROW EXECUTE FUNCTION public.marketplace_items_freeze_privileged();

CREATE OR REPLACE FUNCTION public.marketplace_ledger_immutable()
 RETURNS trigger LANGUAGE plpgsql SET search_path TO 'public' AS $function$
BEGIN
  RAISE EXCEPTION 'marketplace_install_ledger is append-only; correct with a compensating row (refund), never UPDATE/DELETE'
    USING ERRCODE = '42501';
END $function$;
DROP TRIGGER IF EXISTS trg_marketplace_ledger_immutable ON public.marketplace_install_ledger;
CREATE TRIGGER trg_marketplace_ledger_immutable
  BEFORE UPDATE OR DELETE ON public.marketplace_install_ledger
  FOR EACH ROW EXECUTE FUNCTION public.marketplace_ledger_immutable();

UPDATE public.marketplace_items
   SET description = 'Adds funding-readiness, lender matching, and a funding knowledge base to Paige. Opt-in; layers on top of any practice — coach, consultant, agency, or advisor.'
 WHERE slug = 'funding';
UPDATE public.marketplace_items
   SET description = 'Seeds your knowledge base with a proven client-onboarding framework Paige uses to welcome, orient, and set expectations with every new client — for any practice.'
 WHERE slug = 'client_onboarding_essentials';

CREATE OR REPLACE FUNCTION public.install_marketplace_item(
  _tenant_id uuid,
  _item_slug text,
  _seeded_kb_doc_ids uuid[] DEFAULT '{}'::uuid[],
  _installed_by_agent text DEFAULT NULL
) RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  _item        public.marketplace_items%ROWTYPE;
  _ver         public.marketplace_item_versions%ROWTYPE;
  _is_owner    boolean := public.is_platform_owner();
  _fn          jsonb;
  _kind        text;
  _skill_slugs text[] := '{}';
  _skipped     jsonb := '[]'::jsonb;
  _seeded_refs jsonb;
  _install     public.marketplace_installs%ROWTYPE;
  _existing    public.marketplace_installs%ROWTYPE;
  _had_row     boolean := false;
  _was_active  boolean := false;
  _needs_embed boolean := false;
  _warning     text := NULL;
  _reconciled  integer := 0;
  _gross       integer := 0;
  _fee         integer := 0;
  _net         integer := 0;
BEGIN
  IF NOT (_is_owner OR public.is_tenant_admin(_tenant_id)) THEN
    RAISE EXCEPTION 'not authorized to install for this tenant' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO _item FROM public.marketplace_items WHERE slug = _item_slug;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'marketplace item % not found', _item_slug USING ERRCODE = 'no_data_found';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(_tenant_id::text || ':' || _item.id::text, 0));

  IF NOT _is_owner THEN
    IF _item.status <> 'listed' THEN
      RAISE EXCEPTION 'marketplace item % is not available', _item_slug USING ERRCODE = '42501';
    END IF;
    IF NOT (
      _item.scope = 'public'
      OR (_item.scope = 'tenant' AND _item.visible_to_tenant_id = _tenant_id)
      OR (_item.scope = 'agency' AND public.agency_team_role(_item.visible_to_agency_id, auth.uid()) IS NOT NULL)
    ) THEN
      RAISE EXCEPTION 'marketplace item % is not visible to this tenant', _item_slug USING ERRCODE = '42501';
    END IF;
  END IF;

  IF _item.current_version_id IS NULL THEN
    RAISE EXCEPTION 'marketplace item % has no published version', _item_slug USING ERRCODE = 'no_data_found';
  END IF;
  SELECT * INTO _ver FROM public.marketplace_item_versions WHERE id = _item.current_version_id;

  SELECT * INTO _existing FROM public.marketplace_installs
   WHERE tenant_id = _tenant_id AND item_id = _item.id;
  _had_row := FOUND;
  _was_active := FOUND AND _existing.status = 'active';
  IF _was_active THEN
    RETURN jsonb_build_object(
      'ok', true, 'already_installed', true,
      'item_slug', _item.slug, 'item_type', _item.item_type, 'version', _ver.semver,
      'seeded_refs', _existing.seeded_refs
    );
  END IF;

  _needs_embed := (_ver.install_manifest ? 'kb_pack')
                  AND COALESCE(array_length(_seeded_kb_doc_ids, 1), 0) = 0;
  IF _needs_embed THEN
    _warning := 'This item includes a knowledge pack that must be embedded — install it via the marketplace-install function so the knowledge base is actually seeded. Skills (if any) were still enabled.';
  END IF;

  FOR _fn IN SELECT * FROM jsonb_array_elements(COALESCE(_ver.install_manifest->'functions','[]'::jsonb))
  LOOP
    _kind := _fn->>'kind';
    IF _kind = 'skill_flag' AND (_fn->>'slug') IS NOT NULL THEN
      PERFORM public.set_tenant_skill(_tenant_id, _fn->>'slug', true);
      _skill_slugs := array_append(_skill_slugs, _fn->>'slug');
    ELSE
      _skipped := _skipped || jsonb_build_array(_fn);
    END IF;
  END LOOP;

  DELETE FROM public.tenant_knowledge_docs
   WHERE tenant_id = _tenant_id
     AND tags @> ARRAY['marketplace:' || _item.slug]
     AND NOT (id = ANY (COALESCE(_seeded_kb_doc_ids, '{}'::uuid[])));
  GET DIAGNOSTICS _reconciled = ROW_COUNT;

  _seeded_refs := jsonb_build_object(
    'skill_slugs', to_jsonb(_skill_slugs),
    'kb_doc_ids', to_jsonb(COALESCE(_seeded_kb_doc_ids, '{}'::uuid[])),
    'portal_surface_slugs', '[]'::jsonb,
    'features_keys', '[]'::jsonb
  );

  INSERT INTO public.marketplace_installs
    (tenant_id, item_id, version_id, status, seeded_refs, installed_by, installed_by_agent, installed_at, uninstalled_at)
  VALUES
    (_tenant_id, _item.id, _ver.id, 'active', _seeded_refs, auth.uid(), _installed_by_agent, now(), NULL)
  ON CONFLICT (tenant_id, item_id) DO UPDATE
    SET version_id = EXCLUDED.version_id,
        status = 'active',
        seeded_refs = EXCLUDED.seeded_refs,
        installed_by = EXCLUDED.installed_by,
        installed_by_agent = EXCLUDED.installed_by_agent,
        installed_at = now(),
        uninstalled_at = NULL
  RETURNING * INTO _install;

  IF (NOT _had_row) OR _existing.status = 'uninstalled' THEN
    UPDATE public.marketplace_items SET install_count = install_count + 1 WHERE id = _item.id;
  END IF;

  _gross := COALESCE(_item.price_cents, 0);
  _fee   := (_gross * COALESCE(_item.take_rate_bps, 0)) / 10000;
  _net   := _gross - _fee;
  INSERT INTO public.marketplace_install_ledger
    (install_id, item_id, vendor_id, tenant_id, event_type, gross_cents, take_rate_bps, platform_fee_cents, vendor_net_cents)
  VALUES
    (_install.id, _item.id, _item.vendor_id, _tenant_id, 'install', _gross, COALESCE(_item.take_rate_bps,0), _fee, _net);

  RETURN jsonb_build_object(
    'ok', true,
    'already_installed', false,
    'item_slug', _item.slug,
    'item_type', _item.item_type,
    'version', _ver.semver,
    'skills_enabled', to_jsonb(_skill_slugs),
    'kb_docs_seeded', COALESCE(array_length(_seeded_kb_doc_ids, 1), 0),
    'needs_embedding', _needs_embed,
    'reconciled_orphans', _reconciled,
    'skipped_functions', _skipped,
    'warning', _warning,
    'install_id', _install.id
  );
END $function$;
REVOKE ALL ON FUNCTION public.install_marketplace_item(uuid, text, uuid[], text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.install_marketplace_item(uuid, text, uuid[], text) TO authenticated, service_role;
