-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260710003656 (tenant_service_agreement_legalname_fix)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260710003656 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.set_tenant_service_agreement(_tenant_id uuid, _title text, _body text)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT (public.is_platform_owner() OR public.is_tenant_admin(_tenant_id)) THEN
    RAISE EXCEPTION 'not authorized to edit this tenant''s agreement';
  END IF;
  INSERT INTO public.tenant_legal_profile (tenant_id, legal_business_name, service_agreement_title, service_agreement_body, service_agreement_updated_at)
  VALUES (_tenant_id, COALESCE((SELECT name FROM public.tenants WHERE id = _tenant_id), 'Business'),
          NULLIF(trim(_title), ''), NULLIF(trim(_body), ''), now())
  ON CONFLICT (tenant_id) DO UPDATE
    SET service_agreement_title = NULLIF(trim(_title), ''),
        service_agreement_body = NULLIF(trim(_body), ''),
        service_agreement_updated_at = now(),
        updated_at = now();
END $$;
