-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712221139 (agency_mcp_guards)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712221139 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================


CREATE OR REPLACE FUNCTION public.agency_can_manage_child(_child uuid, _actor uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.tenants child
    JOIN public.tenants parent    ON parent.id = child.parent_tenant_id
    JOIN public.tenant_members pm ON pm.tenant_id = parent.id AND pm.user_id = _actor
    WHERE child.id = _child
      AND parent.account_type IN ('agency', 'enterprise')
      AND pm.status = 'active'
      AND pm.role IN ('owner', 'admin')
  );
$$;

CREATE OR REPLACE FUNCTION public.agency_can_manage_child(_child uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT public.agency_can_manage_child(_child, auth.uid());
$$;

CREATE OR REPLACE FUNCTION public.list_subaccounts(_actor uuid)
RETURNS TABLE(id uuid, slug text, name text, account_type text, status text, created_at timestamptz)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT c.id, c.slug, c.name, c.account_type, c.status::text, c.created_at
  FROM public.tenants c
  JOIN public.tenants p         ON p.id = c.parent_tenant_id
  JOIN public.tenant_members m  ON m.tenant_id = p.id AND m.user_id = _actor
  WHERE p.account_type IN ('agency', 'enterprise')
    AND m.status = 'active'
    AND m.role IN ('owner', 'admin')
  ORDER BY c.created_at DESC;
$$;

CREATE OR REPLACE FUNCTION public.get_subaccount_metrics(_child uuid, _actor uuid)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  _result jsonb;
BEGIN
  IF NOT public.agency_can_manage_child(_child, _actor) THEN
    RAISE EXCEPTION 'agency_scope_forbidden' USING ERRCODE = '42501';
  END IF;
  SELECT jsonb_build_object(
    'clients',          (SELECT count(*) FROM public.clients                  WHERE tenant_id = _child),
    'active_workflows', (SELECT count(*) FROM public.paige_workflow_registry  WHERE tenant_id = _child AND is_active),
    'members',          (SELECT count(*) FROM public.tenant_members           WHERE tenant_id = _child AND status = 'active')
  ) INTO _result;
  RETURN _result;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_subaccount(
  _name text,
  _industry text,
  _description text,
  _parent_tenant_id uuid,
  _actor uuid
) RETURNS public.tenants
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $$
DECLARE
  _uid uuid := _actor;
  _parent uuid := _parent_tenant_id;
  _parent_type text;
  _tenant public.tenants;
  _base_slug text;
  _slug text;
  _suffix int := 0;
  _child_count int;
BEGIN
  IF _uid IS NULL THEN
    RAISE EXCEPTION 'not authenticated' USING ERRCODE = '28000';
  END IF;
  IF _parent IS NULL THEN
    RAISE EXCEPTION 'no parent tenant in context' USING ERRCODE = '22000';
  END IF;
  IF NOT public.is_tenant_owner(_uid, _parent) THEN
    RAISE EXCEPTION 'only the tenant owner may create a sub-account' USING ERRCODE = '42501';
  END IF;

  SELECT account_type INTO _parent_type FROM public.tenants WHERE id = _parent;
  IF _parent_type NOT IN ('agency', 'enterprise') THEN
    RAISE EXCEPTION 'sub-accounts require an Agency or Enterprise account' USING ERRCODE = '42501';
  END IF;

  IF _name IS NULL OR length(trim(_name)) = 0 THEN
    RAISE EXCEPTION 'sub-account name required' USING ERRCODE = '22000';
  END IF;

  SELECT count(*) INTO _child_count FROM public.tenants WHERE parent_tenant_id = _parent;
  IF _child_count >= 100 THEN
    RAISE EXCEPTION 'sub-account limit (100) reached for this workspace' USING ERRCODE = '54000';
  END IF;

  _base_slug := trim(both '-' from regexp_replace(lower(trim(_name)), '[^a-z0-9]+', '-', 'g'));
  IF _base_slug IS NULL OR length(_base_slug) = 0 THEN _base_slug := 'subaccount'; END IF;
  _base_slug := left(_base_slug, 40);
  _slug := _base_slug;
  WHILE EXISTS (SELECT 1 FROM public.tenants WHERE slug = _slug) LOOP
    _suffix := _suffix + 1;
    _slug := _base_slug || '-' || _suffix::text;
  END LOOP;

  INSERT INTO public.tenants (slug, name, owner_user_id, parent_tenant_id, status, account_type, brand)
  VALUES (
    _slug, trim(_name), _uid, _parent, 'active', 'standalone',
    jsonb_strip_nulls(jsonb_build_object('industry', _industry, 'about', _description))
  )
  RETURNING * INTO _tenant;

  INSERT INTO public.tenant_members (tenant_id, user_id, role, status, joined_at)
  VALUES (_tenant.id, _uid, 'owner', 'active', now());

  RETURN _tenant;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_subaccount(
  _name text,
  _industry text DEFAULT NULL,
  _description text DEFAULT NULL,
  _parent_tenant_id uuid DEFAULT NULL
) RETURNS public.tenants
LANGUAGE sql SECURITY DEFINER SET search_path TO 'public'
AS $$
  SELECT public.create_subaccount(
    _name, _industry, _description,
    COALESCE(_parent_tenant_id, public.current_user_tenant_id()),
    auth.uid()
  );
$$;

REVOKE ALL ON FUNCTION public.agency_can_manage_child(uuid, uuid)      FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.list_subaccounts(uuid)                   FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_subaccount_metrics(uuid, uuid)       FROM public, anon, authenticated;
REVOKE ALL ON FUNCTION public.create_subaccount(text, text, text, uuid, uuid) FROM public, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.agency_can_manage_child(uuid, uuid)   TO service_role;
GRANT EXECUTE ON FUNCTION public.list_subaccounts(uuid)                TO service_role;
GRANT EXECUTE ON FUNCTION public.get_subaccount_metrics(uuid, uuid)    TO service_role;
GRANT EXECUTE ON FUNCTION public.create_subaccount(text, text, text, uuid, uuid) TO service_role;

REVOKE ALL ON FUNCTION public.agency_can_manage_child(uuid)            FROM public, anon;
GRANT EXECUTE ON FUNCTION public.agency_can_manage_child(uuid)         TO authenticated;
REVOKE ALL ON FUNCTION public.create_subaccount(text, text, text, uuid) FROM public, anon;
GRANT EXECUTE ON FUNCTION public.create_subaccount(text, text, text, uuid) TO authenticated;

