-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712033904 (calendar_hosts_management)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712033904 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

ALTER TABLE public.calendars
  ADD COLUMN IF NOT EXISTS assignment_strategy jsonb NOT NULL DEFAULT '{"mode":"balanced"}'::jsonb;

CREATE OR REPLACE FUNCTION public.set_calendar_hosts(_cal uuid, _hosts jsonb)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _tenant uuid; _bad int;
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'CALENDAR_FORBIDDEN: auth required' USING ERRCODE='42501'; END IF;
  IF NOT public.can_manage_calendar(_cal) THEN RAISE EXCEPTION 'CALENDAR_FORBIDDEN' USING ERRCODE='42501'; END IF;
  IF _hosts IS NULL OR jsonb_typeof(_hosts) <> 'array' OR jsonb_array_length(_hosts) < 1 THEN
    RAISE EXCEPTION 'HOSTS_REQUIRED: at least one host' USING ERRCODE='22023';
  END IF;

  SELECT tenant_id INTO _tenant FROM public.calendars WHERE id = _cal;

  IF _tenant IS NOT NULL THEN
    SELECT count(*) INTO _bad
      FROM jsonb_array_elements(_hosts) h
     WHERE NOT EXISTS (
       SELECT 1 FROM public.tenant_members tm
        WHERE tm.tenant_id = _tenant
          AND tm.user_id = (h->>'user_id')::uuid
          AND tm.status = 'active'
     );
    IF _bad > 0 THEN
      RAISE EXCEPTION 'HOST_NOT_ELIGIBLE: % host(s) are not active members of this tenant', _bad USING ERRCODE='22023';
    END IF;
  END IF;

  DELETE FROM public.calendar_hosts WHERE calendar_id = _cal;
  INSERT INTO public.calendar_hosts (calendar_id, user_id, priority)
  SELECT DISTINCT ON ((h->>'user_id')::uuid) _cal, (h->>'user_id')::uuid, (ord - 1)::int
    FROM jsonb_array_elements(_hosts) WITH ORDINALITY AS t(h, ord)
   ORDER BY (h->>'user_id')::uuid, ord;
END $$;

REVOKE ALL ON FUNCTION public.set_calendar_hosts(uuid, jsonb) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_calendar_hosts(uuid, jsonb) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.calendar_host_load(_cal uuid)
RETURNS TABLE (user_id uuid, full_name text, priority integer, upcoming_count bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT public.can_manage_calendar(_cal) THEN RAISE EXCEPTION 'CALENDAR_FORBIDDEN' USING ERRCODE='42501'; END IF;
  RETURN QUERY
    SELECT ch.user_id, p.full_name, ch.priority,
           (SELECT count(*) FROM public.internal_bookings b
             WHERE b.host_user_id = ch.user_id
               AND b.status NOT IN ('cancelled','no_show')
               AND b.start_at >= now()) AS upcoming_count
      FROM public.calendar_hosts ch
      LEFT JOIN public.profiles p ON p.user_id = ch.user_id
     WHERE ch.calendar_id = _cal
     ORDER BY ch.priority ASC;
END $$;

REVOKE ALL ON FUNCTION public.calendar_host_load(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.calendar_host_load(uuid) TO authenticated, service_role;
