
ALTER TABLE public.business_public_presence
  ADD COLUMN IF NOT EXISTS website_name_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS website_address_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS website_phone_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS google_name_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS google_address_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS google_phone_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS yelp_name_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS yelp_address_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS yelp_phone_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS linkedin_name_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS linkedin_address_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS linkedin_phone_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS facebook_name_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS facebook_address_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS facebook_phone_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS other1_url text,
  ADD COLUMN IF NOT EXISTS other1_label text,
  ADD COLUMN IF NOT EXISTS other1_name_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS other1_address_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS other1_phone_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS other2_url text,
  ADD COLUMN IF NOT EXISTS other2_label text,
  ADD COLUMN IF NOT EXISTS other2_name_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS other2_address_match boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS other2_phone_match boolean DEFAULT false;
