-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260708220024 (calendar_groups)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260708220024 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Calendar groups (GHL-style): organize many calendars under a named group
-- (a team, a service line, a campaign family). A calendar belongs to at most
-- one group (nullable FK); ungrouped calendars stand alone.
CREATE TABLE IF NOT EXISTS public.calendar_groups (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id   uuid REFERENCES public.tenants(id) ON DELETE CASCADE,        -- null = operator/platform-owned
  created_by  uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  name        text NOT NULL,
  slug        text NOT NULL UNIQUE,
  description text,
  enabled     boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS calendar_groups_tenant_idx ON public.calendar_groups (tenant_id);

ALTER TABLE public.calendars
  ADD COLUMN IF NOT EXISTS group_id uuid REFERENCES public.calendar_groups(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS calendars_group_idx ON public.calendars (group_id);

ALTER TABLE public.calendar_groups ENABLE ROW LEVEL SECURITY;

-- Same shape as the calendars policy: creator / platform admin / tenant admin
-- manage; WITH CHECK forbids planting a group into a tenant you don't belong to
-- and reserves null-tenant (operator) groups for platform admins.
DROP POLICY IF EXISTS "manage calendar groups" ON public.calendar_groups;
CREATE POLICY "manage calendar groups" ON public.calendar_groups
  FOR ALL TO authenticated
  USING (
    created_by = auth.uid()
    OR public.is_platform_admin()
    OR (tenant_id IS NOT NULL AND public.is_tenant_admin(tenant_id))
  )
  WITH CHECK (
    public.is_platform_admin()
    OR (tenant_id IS NOT NULL AND public.is_tenant_admin(tenant_id))
    OR (created_by = auth.uid() AND tenant_id IS NOT NULL AND public.is_tenant_member(tenant_id))
  );

-- Base grants — RLS filters rows, grants let the request reach the policy
-- (the bug that broke calendars: RLS without a grant = "permission denied").
GRANT SELECT, INSERT, UPDATE, DELETE ON public.calendar_groups TO authenticated;
