-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260708224937 (calendar_booking_page_branding)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260708224937 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Owner-controllable public booking-page presentation (GHL-style widget):
--   theme            — 'light' | 'dark' page
--   subtitle         — the small category line above the title ("One on One Coaching")
--   show_company_name — whether to render the brand/company name next to the logo
-- logo_url, accent, title, description already exist on calendars.
ALTER TABLE public.calendars
  ADD COLUMN IF NOT EXISTS theme text NOT NULL DEFAULT 'light',
  ADD COLUMN IF NOT EXISTS subtitle text,
  ADD COLUMN IF NOT EXISTS show_company_name boolean NOT NULL DEFAULT true;

-- Guard the theme to the two supported values.
ALTER TABLE public.calendars DROP CONSTRAINT IF EXISTS calendars_theme_chk;
ALTER TABLE public.calendars ADD CONSTRAINT calendars_theme_chk CHECK (theme IN ('light','dark'));
