-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260711213649 (brand_schema_and_cascade)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260711213649 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Brand Kit (#143 · §6/§9/§10/§12) — tier-aware white-label cascade.
COMMENT ON COLUMN public.tenants.brand IS
  'Brand kit (#143 §6/§12). Canonical keys: logo_url, logo_dark_url, favicon_url, '
  'primary_color, accent_color, font, tagline, product_name, from_name, '
  'support_email, custom_domain. Legacy keys still honored: sender_name, name, '
  'from_address, industry. All optional — absent/empty means inherit the parent '
  'agency, then the platform token floor (see resolve_tenant_brand).';

CREATE OR REPLACE FUNCTION public.tenants_brand_guard()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE k text;
BEGIN
  IF NEW.brand IS NOT NULL THEN
    FOREACH k IN ARRAY ARRAY['primary_color','accent_color'] LOOP
      IF NEW.brand ? k
         AND NULLIF(NEW.brand->>k,'') IS NOT NULL
         AND NEW.brand->>k !~ '^#[0-9A-Fa-f]{6}$' THEN
        RAISE EXCEPTION 'brand.% must be a #RRGGBB hex color', k USING ERRCODE='22000';
      END IF;
    END LOOP;
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_tenants_brand_guard ON public.tenants;
CREATE TRIGGER trg_tenants_brand_guard
  BEFORE INSERT OR UPDATE OF brand ON public.tenants
  FOR EACH ROW EXECUTE FUNCTION public.tenants_brand_guard();

CREATE OR REPLACE FUNCTION public.can_manage_tenant_brand(_tenant_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  WITH RECURSIVE chain AS (
    SELECT id, parent_tenant_id, 0 AS depth
      FROM public.tenants WHERE id = _tenant_id
    UNION ALL
    SELECT p.id, p.parent_tenant_id, c.depth+1
      FROM public.tenants p JOIN chain c ON p.id = c.parent_tenant_id
     WHERE c.depth < 10
  )
  SELECT public.is_platform_owner() OR EXISTS (
    SELECT 1 FROM chain
    WHERE EXISTS (SELECT 1 FROM public.tenants t
                    WHERE t.id = chain.id AND t.owner_user_id = auth.uid())
       OR EXISTS (SELECT 1 FROM public.tenant_members m
                    WHERE m.tenant_id = chain.id AND m.user_id = auth.uid()
                      AND m.role IN ('owner','admin')
                      AND m.status = 'active')
  );
$$;
REVOKE EXECUTE ON FUNCTION public.can_manage_tenant_brand(uuid) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.can_manage_tenant_brand(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.resolve_tenant_brand(_tenant_id uuid)
RETURNS TABLE (
  tenant_id uuid, tenant_name text, tenant_slug text,
  logo_url text, logo_dark_url text, favicon_url text,
  primary_color text, accent_color text, font text, tagline text,
  product_name text, from_name text, support_email text, custom_domain text
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  WITH RECURSIVE chain AS (
    SELECT t.id, t.parent_tenant_id, t.name, t.slug, t.brand, 0 AS depth
      FROM public.tenants t WHERE t.id = _tenant_id
    UNION ALL
    SELECT p.id, p.parent_tenant_id, p.name, p.slug, p.brand, c.depth+1
      FROM public.tenants p JOIN chain c ON p.id = c.parent_tenant_id
     WHERE c.depth < 10
  ),
  pick AS (
    SELECT
      (SELECT NULLIF(brand->>'logo_url','')      FROM chain WHERE NULLIF(brand->>'logo_url','')      IS NOT NULL ORDER BY depth LIMIT 1) AS logo_url,
      (SELECT NULLIF(brand->>'logo_dark_url','') FROM chain WHERE NULLIF(brand->>'logo_dark_url','') IS NOT NULL ORDER BY depth LIMIT 1) AS logo_dark_url,
      (SELECT NULLIF(brand->>'favicon_url','')   FROM chain WHERE NULLIF(brand->>'favicon_url','')   IS NOT NULL ORDER BY depth LIMIT 1) AS favicon_url,
      (SELECT NULLIF(brand->>'primary_color','') FROM chain WHERE NULLIF(brand->>'primary_color','') IS NOT NULL ORDER BY depth LIMIT 1) AS primary_color,
      (SELECT NULLIF(brand->>'accent_color','')  FROM chain WHERE NULLIF(brand->>'accent_color','')  IS NOT NULL ORDER BY depth LIMIT 1) AS accent_color,
      (SELECT NULLIF(brand->>'font','')          FROM chain WHERE NULLIF(brand->>'font','')          IS NOT NULL ORDER BY depth LIMIT 1) AS font,
      (SELECT NULLIF(brand->>'tagline','')       FROM chain WHERE NULLIF(brand->>'tagline','')       IS NOT NULL ORDER BY depth LIMIT 1) AS tagline,
      (SELECT NULLIF(brand->>'product_name','')  FROM chain WHERE NULLIF(brand->>'product_name','')  IS NOT NULL ORDER BY depth LIMIT 1) AS product_name,
      (SELECT COALESCE(NULLIF(brand->>'from_name',''), NULLIF(brand->>'sender_name',''), NULLIF(brand->>'name',''))
         FROM chain
        WHERE COALESCE(NULLIF(brand->>'from_name',''), NULLIF(brand->>'sender_name',''), NULLIF(brand->>'name','')) IS NOT NULL
        ORDER BY depth LIMIT 1) AS from_name,
      (SELECT NULLIF(brand->>'support_email','') FROM chain WHERE NULLIF(brand->>'support_email','') IS NOT NULL ORDER BY depth LIMIT 1) AS support_email,
      (SELECT NULLIF(brand->>'custom_domain','') FROM chain WHERE NULLIF(brand->>'custom_domain','') IS NOT NULL ORDER BY depth LIMIT 1) AS custom_domain
  ),
  self AS (SELECT id, name, slug FROM chain WHERE depth = 0)
  SELECT
    self.id, self.name, self.slug,
    pick.logo_url,
    pick.logo_dark_url, pick.favicon_url,
    COALESCE(pick.primary_color, '#150C31')  AS primary_color,
    COALESCE(pick.accent_color,  '#EBB94C')  AS accent_color,
    pick.font, pick.tagline,
    COALESCE(pick.product_name, self.name)   AS product_name,
    COALESCE(pick.from_name,    self.name)   AS from_name,
    pick.support_email, pick.custom_domain
  FROM self, pick;
$$;
REVOKE EXECUTE ON FUNCTION public.resolve_tenant_brand(uuid) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.resolve_tenant_brand(uuid) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.set_tenant_brand(_tenant_id uuid, _patch jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _merged jsonb;
BEGIN
  IF _patch IS NULL OR jsonb_typeof(_patch) <> 'object' THEN
    RAISE EXCEPTION 'brand patch must be a JSON object' USING ERRCODE='22023';
  END IF;
  IF NOT public.can_manage_tenant_brand(_tenant_id) THEN
    RAISE EXCEPTION 'not authorized to manage brand for %', _tenant_id USING ERRCODE='42501';
  END IF;
  UPDATE public.tenants
     SET brand = COALESCE(brand,'{}'::jsonb) || _patch
   WHERE id = _tenant_id
  RETURNING brand INTO _merged;
  IF _merged IS NULL THEN
    RAISE EXCEPTION 'tenant % not found', _tenant_id USING ERRCODE='P0002';
  END IF;
  RETURN _merged;
END $$;
REVOKE EXECUTE ON FUNCTION public.set_tenant_brand(uuid, jsonb) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.set_tenant_brand(uuid, jsonb) TO authenticated;

INSERT INTO storage.buckets (id, name, public)
VALUES ('tenant-brand','tenant-brand',true) ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "tenant-brand public read" ON storage.objects;
CREATE POLICY "tenant-brand public read" ON storage.objects
  FOR SELECT USING (bucket_id = 'tenant-brand');
DROP POLICY IF EXISTS "tenant-brand managed insert" ON storage.objects;
CREATE POLICY "tenant-brand managed insert" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id='tenant-brand'
    AND public.can_manage_tenant_brand(((storage.foldername(name))[1])::uuid));
DROP POLICY IF EXISTS "tenant-brand managed update" ON storage.objects;
CREATE POLICY "tenant-brand managed update" ON storage.objects
  FOR UPDATE TO authenticated USING (bucket_id='tenant-brand'
    AND public.can_manage_tenant_brand(((storage.foldername(name))[1])::uuid));
DROP POLICY IF EXISTS "tenant-brand managed delete" ON storage.objects;
CREATE POLICY "tenant-brand managed delete" ON storage.objects
  FOR DELETE TO authenticated USING (bucket_id='tenant-brand'
    AND public.can_manage_tenant_brand(((storage.foldername(name))[1])::uuid));

DROP FUNCTION IF EXISTS public.get_client_portal_brand();
CREATE FUNCTION public.get_client_portal_brand()
RETURNS TABLE(
  tenant_id uuid, tenant_name text, tenant_slug text, logo_url text, primary_color text,
  logo_dark_url text, favicon_url text, accent_color text, font text, tagline text,
  product_name text, from_name text, support_email text
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = 'public' AS $$
  WITH me AS (
    SELECT c.tenant_id AS tid
    FROM public.clients c
    WHERE c.linked_user_id = auth.uid()
    ORDER BY c.created_at ASC
    LIMIT 1
  )
  SELECT
    rb.tenant_id, rb.tenant_name, rb.tenant_slug,
    COALESCE(rb.logo_url, p.brand_logo_url) AS logo_url,
    rb.primary_color,
    rb.logo_dark_url, rb.favicon_url, rb.accent_color, rb.font, rb.tagline,
    rb.product_name, rb.from_name, rb.support_email
  FROM me
  JOIN public.resolve_tenant_brand(me.tid) rb ON TRUE
  LEFT JOIN public.tenant_legal_profile p ON p.tenant_id = me.tid;
$$;

DROP FUNCTION IF EXISTS public.peek_tenant_portal_brand(text);
CREATE FUNCTION public.peek_tenant_portal_brand(_slug text)
RETURNS TABLE(
  tenant_name text, tenant_slug text, logo_url text, primary_color text,
  logo_dark_url text, favicon_url text, accent_color text, font text, tagline text,
  product_name text
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = 'public' AS $$
  WITH me AS (
    SELECT t.id AS tid FROM public.tenants t
    WHERE lower(t.slug) = lower(trim(_slug))
    LIMIT 1
  )
  SELECT
    rb.tenant_name, rb.tenant_slug,
    COALESCE(rb.logo_url, p.brand_logo_url) AS logo_url,
    rb.primary_color,
    rb.logo_dark_url, rb.favicon_url, rb.accent_color, rb.font, rb.tagline,
    rb.product_name
  FROM me
  JOIN public.resolve_tenant_brand(me.tid) rb ON TRUE
  LEFT JOIN public.tenant_legal_profile p ON p.tenant_id = me.tid;
$$;

CREATE OR REPLACE FUNCTION public.provision_tenant_email_identity(_tenant_id uuid)
RETURNS tenant_email_identities
LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public' AS $function$
DECLARE
  v_tenant   public.tenants%ROWTYPE;
  v_existing public.tenant_email_identities%ROWTYPE;
  v_brand    record;
  v_from     text;
  v_base     text;
  v_local    text;
  v_reply    text;
  v_n        int := 1;
  v_attempt  int;
  v_row      public.tenant_email_identities%ROWTYPE;
BEGIN
  IF _tenant_id IS NULL THEN
    RAISE EXCEPTION 'PROVISION_IDENTITY_NO_TENANT' USING ERRCODE = '22023';
  END IF;
  SELECT * INTO v_existing FROM public.tenant_email_identities WHERE tenant_id = _tenant_id;
  IF FOUND THEN RETURN v_existing; END IF;
  SELECT * INTO v_tenant FROM public.tenants WHERE id = _tenant_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'PROVISION_IDENTITY_TENANT_NOT_FOUND: %', _tenant_id USING ERRCODE = 'P0001';
  END IF;
  SELECT from_name, support_email INTO v_brand FROM public.resolve_tenant_brand(_tenant_id);
  v_from := NULLIF(TRIM(COALESCE(v_brand.from_name, v_tenant.name)), '');
  IF v_from IS NULL THEN v_from := 'Paige Agent AI'; END IF;
  v_from := NULLIF(TRIM(regexp_replace(v_from, '[[:cntrl:]]', ' ', 'g')), '');
  IF v_from IS NULL THEN v_from := 'Paige Agent AI'; END IF;
  v_base  := public.sanitize_email_local_part(COALESCE(NULLIF(v_tenant.slug, ''), v_tenant.name, 'client'));
  v_local := v_base;
  WHILE EXISTS (
    SELECT 1 FROM public.tenant_email_identities
    WHERE kind = 'shared' AND lower(local_part) = lower(v_local) AND tenant_id <> _tenant_id
  ) LOOP
    v_n := v_n + 1;
    v_local := left(v_base, 36) || '-' || v_n::text;
  END LOOP;
  v_reply := NULLIF(TRIM(COALESCE(v_brand.support_email, '')), '');
  IF v_reply IS NOT NULL AND v_reply !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' THEN
    v_reply := NULL;
  END IF;
  FOR v_attempt IN 1..64 LOOP
    BEGIN
      INSERT INTO public.tenant_email_identities (tenant_id, from_name, local_part, reply_to, kind, status)
      VALUES (_tenant_id, v_from, v_local, v_reply, 'shared', 'active')
      ON CONFLICT (tenant_id) DO NOTHING
      RETURNING * INTO v_row;
      IF v_row.tenant_id IS NULL THEN
        SELECT * INTO v_row FROM public.tenant_email_identities WHERE tenant_id = _tenant_id;
      END IF;
      RETURN v_row;
    EXCEPTION WHEN unique_violation THEN
      v_n := v_n + 1;
      v_local := left(v_base, 36) || '-' || v_n::text;
    END;
  END LOOP;
  RAISE EXCEPTION 'PROVISION_IDENTITY_LOCAL_PART_EXHAUSTED for tenant %', _tenant_id USING ERRCODE = 'P0001';
END; $function$;

CREATE OR REPLACE FUNCTION public.resolve_tenant_sender(_tenant_id uuid)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public' AS $function$
DECLARE
  v_tenant   public.tenants%ROWTYPE;
  v_cfg      public.platform_email_settings%ROWTYPE;
  v_ident    public.tenant_email_identities%ROWTYPE;
  v_domain   public.tenant_email_domains%ROWTYPE;
  v_brand    record;
  v_shared   text;
  v_from_name text;
  v_from_addr text;
  v_reply    text;
  v_brand_reply text;
  v_source   text;
  v_kind     text;
BEGIN
  SELECT * INTO v_cfg FROM public.platform_email_settings LIMIT 1;
  v_shared := COALESCE(NULLIF(v_cfg.shared_domain, ''), 'paigeagent.ai');
  IF _tenant_id IS NULL THEN
    RETURN jsonb_build_object(
      'tenant_id', NULL,
      'from_name', COALESCE(NULLIF(v_cfg.default_from_name, ''), 'Paige Agent AI'),
      'from_address', 'team@' || v_shared,
      'reply_to', COALESCE(NULLIF(v_cfg.default_reply_to, ''), 'support@' || v_shared),
      'domain', v_shared, 'kind', 'platform', 'source', 'platform_default'
    );
  END IF;
  SELECT * INTO v_tenant FROM public.tenants WHERE id = _tenant_id;
  SELECT * INTO v_ident FROM public.tenant_email_identities
    WHERE tenant_id = _tenant_id AND status = 'active';
  SELECT from_name, support_email INTO v_brand FROM public.resolve_tenant_brand(_tenant_id);
  SELECT * INTO v_domain FROM public.tenant_email_domains
    WHERE tenant_id = _tenant_id AND status = 'verified'
    ORDER BY is_default DESC, verified_at DESC NULLS LAST
    LIMIT 1;
  IF FOUND THEN
    v_from_addr := COALESCE(NULLIF(v_domain.from_email_local, ''), 'no-reply') || '@' || v_domain.domain;
    v_from_name := COALESCE(NULLIF(v_domain.from_name, ''), NULLIF(v_ident.from_name, ''), v_brand.from_name, v_tenant.name, 'Paige Agent AI');
    v_source := 'custom_domain';
    v_kind := 'custom_domain';
  ELSIF v_ident.tenant_id IS NOT NULL THEN
    v_from_addr := v_ident.local_part || '@' || v_shared;
    v_from_name := COALESCE(NULLIF(v_ident.from_name, ''), v_brand.from_name, v_tenant.name, 'Paige Agent AI');
    v_source := 'shared';
    v_kind := 'shared';
  ELSE
    v_from_addr := 'team@' || v_shared;
    v_from_name := COALESCE(v_brand.from_name, v_tenant.name, NULLIF(v_cfg.default_from_name, ''), 'Paige Agent AI');
    v_source := 'platform_default';
    v_kind := 'platform';
  END IF;
  v_brand_reply := NULLIF(v_brand.support_email, '');
  IF v_brand_reply IS NOT NULL AND v_brand_reply !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' THEN
    v_brand_reply := NULL;
  END IF;
  v_reply := COALESCE(
    NULLIF(v_ident.reply_to, ''),
    v_brand_reply,
    NULLIF(v_cfg.default_reply_to, ''),
    'support@' || v_shared
  );
  RETURN jsonb_build_object(
    'tenant_id',    _tenant_id,
    'tenant_slug',  v_tenant.slug,
    'tenant_name',  v_tenant.name,
    'from_name',    v_from_name,
    'from_address', v_from_addr,
    'reply_to',     v_reply,
    'domain',       split_part(v_from_addr, '@', 2),
    'kind',         v_kind,
    'source',       v_source
  );
END; $function$;
