-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260710010040 (tenant_portal_gateway_brand)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260710010040 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Tenant-branded portal gateway (post-signout landing + "log back in").
-- A signed-out customer has no session, so the gateway resolves the tenant's
-- PUBLIC brand by slug (logo + name + primary color only — nothing sensitive).
-- This is the surface a customer returns to; they never see the Paige platform
-- page (§9). Anon-callable by design (they're logged out).
CREATE OR REPLACE FUNCTION public.peek_tenant_portal_brand(_slug text)
RETURNS TABLE (
  tenant_id uuid,
  tenant_name text,
  tenant_slug text,
  logo_url text,
  primary_color text
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT
    t.id,
    t.name,
    t.slug,
    COALESCE(NULLIF(t.brand->>'logo_url', ''), p.brand_logo_url) AS logo_url,
    NULLIF(t.brand->>'primary_color', '') AS primary_color
  FROM public.tenants t
  LEFT JOIN public.tenant_legal_profile p ON p.tenant_id = t.id
  WHERE lower(t.slug) = lower(trim(_slug))
  LIMIT 1;
$$;
REVOKE EXECUTE ON FUNCTION public.peek_tenant_portal_brand(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.peek_tenant_portal_brand(text) TO anon, authenticated;

-- Add tenant_slug to the authed client-brand helper so the portal knows which
-- gateway to send the customer back to on sign-out. Return-type change → DROP+CREATE.
DROP FUNCTION IF EXISTS public.get_client_portal_brand();
CREATE FUNCTION public.get_client_portal_brand()
RETURNS TABLE (
  tenant_id uuid,
  tenant_name text,
  tenant_slug text,
  logo_url text,
  primary_color text
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT
    t.id AS tenant_id,
    t.name AS tenant_name,
    t.slug AS tenant_slug,
    COALESCE(NULLIF(t.brand->>'logo_url', ''), p.brand_logo_url) AS logo_url,
    NULLIF(t.brand->>'primary_color', '') AS primary_color
  FROM public.clients c
  JOIN public.tenants t ON t.id = c.tenant_id
  LEFT JOIN public.tenant_legal_profile p ON p.tenant_id = t.id
  WHERE c.linked_user_id = auth.uid()
  ORDER BY c.created_at ASC
  LIMIT 1;
$$;
REVOKE EXECUTE ON FUNCTION public.get_client_portal_brand() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_client_portal_brand() TO authenticated;
