-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260714192837 (marketplace_operator_seam_5_deprecate_and_catalog)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260714192837 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Wave 3 chunk 5/6: marketplace_deprecate_version + marketplace_operator_catalog (M4/M5)
CREATE OR REPLACE FUNCTION public.marketplace_deprecate_version(
  _item_slug text,
  _semver    text
) RETURNS jsonb
 LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'public'
AS $function$
DECLARE
  _item public.marketplace_items%ROWTYPE;
  _ver  public.marketplace_item_versions%ROWTYPE;
  _actor_role text;
BEGIN
  IF NOT (public._marketplace_operator_authorized()) THEN
    RAISE EXCEPTION 'only the platform owner (or service_role) may deprecate a version' USING ERRCODE = '42501';
  END IF;
  _actor_role := CASE WHEN public.is_platform_owner() THEN 'platform_owner' ELSE 'service_role' END;

  SELECT * INTO _item FROM public.marketplace_items WHERE slug = _item_slug;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'marketplace item % not found', _item_slug USING ERRCODE = 'no_data_found';
  END IF;

  SELECT * INTO _ver FROM public.marketplace_item_versions
   WHERE item_id = _item.id AND semver = _semver;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'item % has no version %', _item_slug, _semver USING ERRCODE = 'no_data_found';
  END IF;
  IF _ver.status <> 'published' THEN
    RAISE EXCEPTION 'version % of % is % — only a published version can be deprecated', _semver, _item_slug, _ver.status
      USING ERRCODE = '22023';
  END IF;
  IF _ver.id = _item.current_version_id THEN
    RAISE EXCEPTION 'version % is the CURRENT version of %; point the item at another published version first (marketplace_set_current_version), then deprecate this one', _semver, _item_slug
      USING ERRCODE = '42501';
  END IF;

  UPDATE public.marketplace_item_versions
     SET status = 'deprecated', deprecated_at = now()
   WHERE id = _ver.id
  RETURNING * INTO _ver;

  INSERT INTO public.paige_audit_log
    (actor_user_id, actor_role, action, target_type, target_id, payload, tenant_id)
  VALUES (
    auth.uid(), _actor_role, 'marketplace.version.deprecate',
    'marketplace_item_version', _ver.id,
    jsonb_build_object('item_slug', _item.slug, 'item_id', _item.id,
                       'semver', _ver.semver, 'to_status', _ver.status),
    NULL
  );

  RETURN jsonb_build_object('ok', true, 'item_slug', _item.slug,
                            'semver', _ver.semver, 'status', _ver.status);
END $function$;
REVOKE ALL ON FUNCTION public.marketplace_deprecate_version(text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.marketplace_deprecate_version(text,text) TO authenticated, service_role;

DROP FUNCTION IF EXISTS public.marketplace_operator_catalog();
CREATE OR REPLACE FUNCTION public.marketplace_operator_catalog()
 RETURNS TABLE (
   id uuid, slug text, item_type public.marketplace_item_type, name text, tagline text,
   category text, icon text, vendor_slug text, origin public.marketplace_origin,
   status public.marketplace_item_status, scope public.marketplace_scope,
   featured boolean, default_for_new_tenants boolean, is_finance boolean,
   pricing_model text, price_cents integer, billing_period text, take_rate_bps integer, serves text,
   install_count integer, rating_avg numeric, rating_count integer,
   current_version_id uuid, current_semver text,
   current_version_status public.marketplace_version_status,
   current_payload_class public.marketplace_payload_class,
   current_version_is_published boolean, version_count integer,
   revenue_gross_cents bigint, platform_fee_cents bigint, vendor_net_cents bigint,
   refunds_cents bigint, revenue_event_count bigint, paid_install_count bigint,
   created_at timestamptz, updated_at timestamptz
 )
 LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT (public._marketplace_operator_authorized()) THEN
    RAISE EXCEPTION 'only the platform owner (or service_role) may read the operator catalog'
      USING ERRCODE = '42501';
  END IF;

  RETURN QUERY
  SELECT
    i.id, i.slug, i.item_type, i.name, i.tagline, i.category, i.icon,
    ve.slug AS vendor_slug, i.origin, i.status, i.scope,
    i.featured, i.default_for_new_tenants, i.is_finance,
    i.pricing_model, i.price_cents, i.billing_period, i.take_rate_bps, i.serves,
    i.install_count, i.rating_avg, i.rating_count,
    i.current_version_id, cv.semver AS current_semver,
    cv.status AS current_version_status, cv.payload_class AS current_payload_class,
    (cv.id IS NOT NULL AND cv.status = 'published') AS current_version_is_published,
    COALESCE(vc.n, 0)::integer AS version_count,
    COALESCE(lg.revenue_gross_cents, 0)::bigint AS revenue_gross_cents,
    COALESCE(lg.platform_fee_cents, 0)::bigint  AS platform_fee_cents,
    COALESCE(lg.vendor_net_cents, 0)::bigint    AS vendor_net_cents,
    COALESCE(lg.refunds_cents, 0)::bigint        AS refunds_cents,
    COALESCE(lg.revenue_events, 0)::bigint       AS revenue_event_count,
    COALESCE(lg.paid_install_events, 0)::bigint  AS paid_install_count,
    i.created_at, i.updated_at
  FROM public.marketplace_items i
  JOIN public.marketplace_vendors ve ON ve.id = i.vendor_id
  LEFT JOIN public.marketplace_item_versions cv ON cv.id = i.current_version_id
  LEFT JOIN LATERAL (
    SELECT count(*) AS n FROM public.marketplace_item_versions v WHERE v.item_id = i.id
  ) vc ON true
  LEFT JOIN LATERAL (
    SELECT
      sum(l.gross_cents)        FILTER (WHERE l.event_type IN ('install','subscription_renewal')) AS revenue_gross_cents,
      sum(l.platform_fee_cents) FILTER (WHERE l.event_type IN ('install','subscription_renewal')) AS platform_fee_cents,
      sum(l.vendor_net_cents)   FILTER (WHERE l.event_type IN ('install','subscription_renewal')) AS vendor_net_cents,
      sum(l.gross_cents)        FILTER (WHERE l.event_type = 'refund')                            AS refunds_cents,
      count(*)                  FILTER (WHERE l.event_type IN ('install','subscription_renewal') AND l.gross_cents > 0) AS revenue_events,
      count(*)                  FILTER (WHERE l.event_type = 'install' AND l.gross_cents > 0)                           AS paid_install_events
    FROM public.marketplace_install_ledger l WHERE l.item_id = i.id
  ) lg ON true
  ORDER BY i.featured DESC, i.category, i.name;
END $function$;
REVOKE ALL ON FUNCTION public.marketplace_operator_catalog() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.marketplace_operator_catalog() TO authenticated, service_role;
