-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260711232719 (paige_planning_horizons_extend)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260711232719 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================


DO $$
DECLARE _cn text;
BEGIN
  SELECT conname INTO _cn FROM pg_constraint
   WHERE conrelid='public.plans'::regclass AND contype='c'
     AND pg_get_constraintdef(oid) ILIKE '%horizon%';
  IF _cn IS NOT NULL THEN EXECUTE format('ALTER TABLE public.plans DROP CONSTRAINT %I', _cn); END IF;
END $$;
ALTER TABLE public.plans ADD CONSTRAINT plans_horizon_check
  CHECK (horizon IN ('week','month','quarter','semiannual','year','custom'));

CREATE OR REPLACE FUNCTION public.plan_create(
  p_title text, p_horizon text, p_starts_on date, p_ends_on date,
  p_scope text DEFAULT 'individual', p_owner_user_id uuid DEFAULT NULL,
  p_summary text DEFAULT NULL, p_campaign_ref jsonb DEFAULT NULL, p_tenant_id uuid DEFAULT NULL
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE _caller uuid := auth.uid(); _tenant uuid; _owner uuid := p_owner_user_id; _staff boolean := false; _id uuid;
BEGIN
  IF _caller IS NOT NULL THEN
    _tenant := public.current_user_tenant_id();
    IF p_tenant_id IS NOT NULL AND p_tenant_id <> _tenant THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: tenant mismatch' USING ERRCODE='42501'; END IF;
    IF NOT public.is_tenant_member(_tenant) THEN RAISE EXCEPTION 'PLAN_FORBIDDEN: not a member' USING ERRCODE='42501'; END IF;
    _staff := public.has_any_role(_caller, ARRAY['admin','super_admin','coach']);
  ELSE
    _tenant := p_tenant_id;
    IF _tenant IS NULL THEN RAISE EXCEPTION 'PLAN_NO_TENANT' USING ERRCODE='22023'; END IF;
    _staff := true;
  END IF;
  _owner := COALESCE(_owner, _caller);
  IF NOT _staff AND (COALESCE(p_scope,'individual') <> 'individual' OR _owner IS DISTINCT FROM _caller) THEN
    RAISE EXCEPTION 'PLAN_FORBIDDEN: team planning needs admin or coach' USING ERRCODE='42501';
  END IF;
  IF COALESCE(btrim(p_title),'') = '' THEN RAISE EXCEPTION 'PLAN_TITLE_REQUIRED' USING ERRCODE='22023'; END IF;
  IF p_horizon NOT IN ('week','month','quarter','semiannual','year','custom') THEN RAISE EXCEPTION 'PLAN_BAD_HORIZON' USING ERRCODE='22023'; END IF;
  IF p_ends_on < p_starts_on THEN RAISE EXCEPTION 'PLAN_BAD_WINDOW' USING ERRCODE='22023'; END IF;
  IF _owner IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.tenant_members WHERE user_id=_owner AND tenant_id=_tenant AND status='active') THEN
    RAISE EXCEPTION 'PLAN_OWNER_NOT_IN_TENANT' USING ERRCODE='42501'; END IF;
  INSERT INTO public.plans(tenant_id, created_by, owner_user_id, scope, horizon, title, summary, starts_on, ends_on, campaign_ref)
  VALUES (_tenant, _caller, _owner, COALESCE(p_scope,'individual'), p_horizon, btrim(p_title), p_summary, p_starts_on, p_ends_on, p_campaign_ref)
  RETURNING id INTO _id;
  INSERT INTO public.audit_logs(user_id, entity, action, entity_id, data)
  VALUES (_caller,'plan','plan_create',_id, jsonb_build_object('tenant_id',_tenant,'horizon',p_horizon,'scope',p_scope));
  RETURN jsonb_build_object('ok',true,'plan_id',_id);
END $$;

