-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712173219 (paige_context_rail_step2_1_hardening)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712173219 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.get_client_rail(
  p_contact_id uuid,
  p_limit      integer DEFAULT 50,
  p_lens       text DEFAULT 'coach'
) RETURNS TABLE (
  id uuid, event_kind text, surface text, actor_type text, actor_user_id uuid,
  audience text, visibility text, from_department text, to_department text,
  title text, summary text, payload jsonb, ref_table text, ref_id uuid, occurred_at timestamptz
)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid     uuid := auth.uid();
  v_tenant  uuid;
  v_is_staff boolean;
  v_is_subject boolean;
  v_lens    text;
  v_limit   integer := LEAST(GREATEST(COALESCE(p_limit, 50), 1), 200);
BEGIN
  IF v_uid IS NULL THEN RETURN; END IF;
  SELECT c.tenant_id INTO v_tenant FROM public.clients c WHERE c.id = p_contact_id;
  IF v_tenant IS NULL THEN RETURN; END IF;

  v_is_staff := public.is_platform_owner()
             OR (v_tenant = public.current_user_tenant_id()
                 AND public.has_any_role(v_uid, ARRAY['admin','super_admin','coach']));
  v_is_subject := EXISTS (SELECT 1 FROM public.clients c WHERE c.id = p_contact_id AND c.linked_user_id = v_uid);

  IF NOT v_is_staff AND NOT v_is_subject THEN RETURN; END IF;
  v_lens := CASE WHEN v_is_staff AND p_lens IN ('coach','owner','staff') THEN 'staff' ELSE 'client' END;

  RETURN QUERY
  SELECT e.id, e.event_kind, e.surface, e.actor_type,
         CASE WHEN v_lens = 'staff' THEN e.actor_user_id   ELSE NULL END,
         e.audience,
         CASE WHEN v_lens = 'staff' THEN e.visibility       ELSE 'client_visible' END,
         CASE WHEN v_lens = 'staff' THEN e.from_department  ELSE NULL END,
         CASE WHEN v_lens = 'staff' THEN e.to_department    ELSE NULL END,
         e.title, e.summary,
         CASE WHEN v_lens = 'staff' THEN e.payload          ELSE '{}'::jsonb END,
         CASE WHEN v_lens = 'staff' THEN e.ref_table        ELSE NULL END,
         CASE WHEN v_lens = 'staff' THEN e.ref_id           ELSE NULL END,
         e.occurred_at
  FROM public.paige_client_events e
  WHERE e.contact_id = p_contact_id
    AND (v_lens = 'staff'
         OR (e.audience IN ('client','both') AND e.visibility = 'client_visible'))
  ORDER BY e.occurred_at DESC
  LIMIT v_limit;
END $$;
REVOKE ALL ON FUNCTION public.get_client_rail(uuid,integer,text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_client_rail(uuid,integer,text) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.resolve_contact_id(
  p_tenant  uuid,
  p_phone   text DEFAULT NULL,
  p_email   text DEFAULT NULL,
  p_user_id uuid DEFAULT NULL
) RETURNS uuid
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid    uuid := auth.uid();
  v_tenant uuid;
  v_id     uuid;
  v_email  text := lower(btrim(p_email));
  v_phone  text := regexp_replace(COALESCE(p_phone,''), '[^0-9]', '', 'g');
BEGIN
  IF v_uid IS NOT NULL THEN
    v_tenant := public.current_user_tenant_id();
    IF p_tenant IS NOT NULL AND p_tenant <> v_tenant THEN RETURN NULL; END IF;
  ELSE
    v_tenant := p_tenant;
  END IF;
  IF v_tenant IS NULL THEN RETURN NULL; END IF;

  SELECT c.id INTO v_id FROM public.clients c
  WHERE c.tenant_id = v_tenant
    AND (
      (p_user_id IS NOT NULL AND c.linked_user_id = p_user_id)
      OR (NULLIF(v_email,'') IS NOT NULL AND lower(btrim(c.email)) = v_email)
      OR (length(v_phone) >= 10
          AND right(regexp_replace(COALESCE(c.phone,''), '[^0-9]', '', 'g'), 10) = right(v_phone, 10))
    )
  ORDER BY (p_user_id IS NOT NULL AND c.linked_user_id = p_user_id) DESC,
           (NULLIF(v_email,'') IS NOT NULL AND lower(btrim(c.email)) = v_email) DESC,
           c.created_at ASC, c.id ASC
  LIMIT 1;
  RETURN v_id;
END $$;
REVOKE ALL ON FUNCTION public.resolve_contact_id(uuid,text,text,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.resolve_contact_id(uuid,text,text,uuid) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.record_rail_event(
  p_contact_id       uuid,
  p_event_kind       text,
  p_surface          text,
  p_actor_type       text,
  p_title            text,
  p_summary          text DEFAULT NULL,
  p_payload          jsonb DEFAULT '{}'::jsonb,
  p_ref_table        text DEFAULT NULL,
  p_ref_id           uuid DEFAULT NULL,
  p_from_department  text DEFAULT NULL,
  p_to_department    text DEFAULT NULL,
  p_occurred_at      timestamptz DEFAULT NULL,
  p_narrow_to_owner  boolean DEFAULT false,
  p_tenant_id        uuid DEFAULT NULL
) RETURNS uuid
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_uid       uuid := auth.uid();
  v_tenant    uuid;
  v_kind      public.paige_event_kinds%ROWTYPE;
  v_audience  text;
  v_visibility text;
  v_actor     uuid;
  v_id        uuid;
  v_occurred  timestamptz;
  v_from_dept text;
BEGIN
  IF v_uid IS NOT NULL THEN
    v_tenant := public.current_user_tenant_id();
    IF p_tenant_id IS NOT NULL AND p_tenant_id <> v_tenant THEN
      RAISE EXCEPTION 'tenant mismatch' USING errcode = '42501';
    END IF;
  ELSE
    IF p_tenant_id IS NULL THEN RAISE EXCEPTION 'p_tenant_id required for service caller'; END IF;
    v_tenant := p_tenant_id;
  END IF;
  IF v_tenant IS NULL THEN RAISE EXCEPTION 'no tenant resolved'; END IF;

  SELECT * INTO v_kind FROM public.paige_event_kinds
    WHERE slug = p_event_kind AND enabled AND (tenant_id IS NULL OR tenant_id = v_tenant);
  IF NOT FOUND THEN RAISE EXCEPTION 'unknown or unavailable event kind: %', p_event_kind; END IF;

  PERFORM 1 FROM public.clients c WHERE c.id = p_contact_id AND c.tenant_id = v_tenant;
  IF NOT FOUND THEN RAISE EXCEPTION 'contact not in tenant' USING errcode = '42501'; END IF;

  IF v_uid IS NOT NULL THEN
    IF NOT (
      public.has_any_role(v_uid, ARRAY['admin','super_admin','coach'])
      OR (p_actor_type = 'client'
          AND EXISTS (SELECT 1 FROM public.clients c WHERE c.id = p_contact_id AND c.linked_user_id = v_uid))
    ) THEN
      RAISE EXCEPTION 'not authorized to write rail event' USING errcode = '42501';
    END IF;
  END IF;

  v_audience   := CASE WHEN p_narrow_to_owner THEN 'owner' ELSE v_kind.default_audience END;
  v_visibility := CASE WHEN v_audience = 'owner' THEN 'owner_internal' ELSE v_kind.default_visibility END;
  v_actor      := CASE WHEN p_actor_type IN ('owner_staff','client') THEN v_uid ELSE NULL END;
  v_from_dept  := COALESCE(p_from_department, v_kind.department);

  INSERT INTO public.paige_client_events (
    tenant_id, contact_id, event_kind, surface, actor_type, actor_user_id,
    audience, visibility, from_department, to_department,
    title, summary, payload, ref_table, ref_id, occurred_at
  ) VALUES (
    v_tenant, p_contact_id, p_event_kind, p_surface, p_actor_type, v_actor,
    v_audience, v_visibility,
    v_from_dept, p_to_department,
    p_title, p_summary, COALESCE(p_payload, '{}'::jsonb), p_ref_table, p_ref_id,
    COALESCE(p_occurred_at, now())
  ) RETURNING id, occurred_at INTO v_id, v_occurred;

  INSERT INTO public.audit_logs (user_id, action, entity, entity_id, data)
  VALUES (v_uid, 'paige_rail_event', 'paige_client_events', v_id,
          jsonb_build_object('kind', p_event_kind, 'surface', p_surface, 'contact_id', p_contact_id, 'audience', v_audience));

  BEGIN
    PERFORM realtime.send(
      jsonb_build_object(
        'id', v_id, 'tenant_id', v_tenant, 'contact_id', p_contact_id,
        'event_kind', p_event_kind, 'surface', p_surface, 'actor_type', p_actor_type,
        'audience', v_audience, 'visibility', v_visibility,
        'from_department', v_from_dept, 'to_department', p_to_department,
        'title', p_title, 'summary', p_summary, 'payload', COALESCE(p_payload, '{}'::jsonb),
        'occurred_at', v_occurred
      ),
      'rail_event', 'rail:tenant:' || v_tenant::text, true
    );
    IF v_audience IN ('client','both') AND v_visibility = 'client_visible' THEN
      PERFORM realtime.send(
        jsonb_build_object(
          'id', v_id, 'contact_id', p_contact_id, 'event_kind', p_event_kind,
          'surface', p_surface, 'actor_type', p_actor_type, 'audience', v_audience,
          'visibility', v_visibility, 'title', p_title, 'summary', p_summary,
          'occurred_at', v_occurred
        ),
        'rail_event', 'rail:client:' || p_contact_id::text, true
      );
    END IF;
  EXCEPTION WHEN others THEN
    RAISE WARNING 'rail broadcast failed for event %: %', v_id, SQLERRM;
  END;

  RETURN v_id;
END $$;
REVOKE ALL ON FUNCTION public.record_rail_event(uuid,text,text,text,text,text,jsonb,text,uuid,text,text,timestamptz,boolean,uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.record_rail_event(uuid,text,text,text,text,text,jsonb,text,uuid,text,text,timestamptz,boolean,uuid) TO authenticated, service_role;
