-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712143931 (harden_paige_chat_threads_own_visibility)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712143931 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Task #149 — a user must ALWAYS be able to see and manage their own Paige chat
-- threads, even if their active tenant diverges from the thread's tenant_id.
--
-- The RESTRICTIVE `threads_tenant_isolation` policy AND-s with the permissive
-- ones, so a thread whose creator's active_tenant_id no longer equals the
-- thread's tenant_id (tenant switch, or a null active_tenant) passed the
-- permissive `caller_user_id = auth.uid()` SELECT but FAILED the restrictive
-- `tenant_id = current_user_tenant_id()` — silently hiding the user's OWN chats.
--
-- Fix: add a strictly self-scoped escape (`caller_user_id = auth.uid()`) to the
-- restrictive wall. This only ever grants a user access to rows THEY created —
-- never another user's — so cross-tenant isolation of everyone else's threads is
-- fully preserved (a user in tenant A still cannot see a thread they don't own in
-- tenant B: not owner, tenant mismatch, not platform owner). The admin client-
-- thread view branch is unaffected: it still self-limits to the admin's own
-- tenant via the permissive policy.

DROP POLICY IF EXISTS threads_tenant_isolation ON public.paige_chat_threads;
CREATE POLICY threads_tenant_isolation ON public.paige_chat_threads
  AS RESTRICTIVE
  FOR ALL
  USING (
    is_platform_owner()
    OR tenant_id = current_user_tenant_id()
    OR caller_user_id = auth.uid()
  )
  WITH CHECK (
    is_platform_owner()
    OR tenant_id = current_user_tenant_id()
    OR caller_user_id = auth.uid()
  );
