-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260710003234 (tenant_service_agreement)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260710003234 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

ALTER TABLE public.tenant_legal_profile
  ADD COLUMN IF NOT EXISTS service_agreement_title text,
  ADD COLUMN IF NOT EXISTS service_agreement_body text,
  ADD COLUMN IF NOT EXISTS service_agreement_updated_at timestamptz;

CREATE OR REPLACE FUNCTION public.get_client_service_agreement()
RETURNS TABLE (tenant_name text, agreement_title text, agreement_body text)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT t.name, p.service_agreement_title, p.service_agreement_body
  FROM public.clients c
  JOIN public.tenants t ON t.id = c.tenant_id
  LEFT JOIN public.tenant_legal_profile p ON p.tenant_id = t.id
  WHERE c.linked_user_id = auth.uid()
  ORDER BY c.created_at ASC
  LIMIT 1;
$$;
REVOKE EXECUTE ON FUNCTION public.get_client_service_agreement() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_client_service_agreement() TO authenticated;

CREATE OR REPLACE FUNCTION public.get_tenant_service_agreement(_tenant_id uuid)
RETURNS TABLE (agreement_title text, agreement_body text, updated_at timestamptz)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT (public.is_platform_owner() OR public.is_tenant_admin(_tenant_id)) THEN
    RAISE EXCEPTION 'not authorized to read this tenant''s agreement';
  END IF;
  RETURN QUERY
    SELECT p.service_agreement_title, p.service_agreement_body, p.service_agreement_updated_at
    FROM public.tenant_legal_profile p WHERE p.tenant_id = _tenant_id;
END $$;
REVOKE EXECUTE ON FUNCTION public.get_tenant_service_agreement(uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.get_tenant_service_agreement(uuid) TO authenticated;

CREATE OR REPLACE FUNCTION public.set_tenant_service_agreement(_tenant_id uuid, _title text, _body text)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT (public.is_platform_owner() OR public.is_tenant_admin(_tenant_id)) THEN
    RAISE EXCEPTION 'not authorized to edit this tenant''s agreement';
  END IF;
  INSERT INTO public.tenant_legal_profile (tenant_id, service_agreement_title, service_agreement_body, service_agreement_updated_at)
  VALUES (_tenant_id, NULLIF(trim(_title), ''), NULLIF(trim(_body), ''), now())
  ON CONFLICT (tenant_id) DO UPDATE
    SET service_agreement_title = NULLIF(trim(_title), ''),
        service_agreement_body = NULLIF(trim(_body), ''),
        service_agreement_updated_at = now(),
        updated_at = now();
END $$;
REVOKE EXECUTE ON FUNCTION public.set_tenant_service_agreement(uuid, text, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.set_tenant_service_agreement(uuid, text, text) TO authenticated;
