-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260708232842 (calendar_multiple_location_options)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260708232842 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

-- Let a calendar offer MULTIPLE meeting methods; the invitee picks one at booking.
-- Source of truth becomes location_options = [{type, value?}, ...]. When it holds
-- one entry the meeting is fixed; more than one → the invitee chooses.
-- location_type/location_value stay for back-compat (and store the CHOSEN method
-- on each booking row).
ALTER TABLE public.calendars ADD COLUMN IF NOT EXISTS location_options jsonb;

-- Backfill from the existing single/ask_invitee setting so nothing breaks.
UPDATE public.calendars SET location_options =
  CASE
    WHEN location_type = 'ask_invitee'
      THEN '[{"type":"google_meet"},{"type":"zoom"},{"type":"phone"}]'::jsonb
    ELSE jsonb_build_array(
      jsonb_build_object('type', coalesce(location_type, 'google_meet'))
      || CASE WHEN location_value IS NOT NULL AND location_value <> ''
              THEN jsonb_build_object('value', location_value) ELSE '{}'::jsonb END
    )
  END
WHERE location_options IS NULL;
