-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260712202034 (booking_rail_emit)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260712202034 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

INSERT INTO public.paige_event_kinds
  (slug, tenant_id, label, description, default_audience, default_visibility, department)
VALUES
  ('booking.created',     NULL, 'Meeting booked',    'A meeting was booked.',   'both', 'client_visible', 'client_experience'),
  ('booking.cancelled',   NULL, 'Meeting cancelled', 'A meeting was cancelled.','both', 'client_visible', 'client_experience'),
  ('booking.rescheduled', NULL, 'Meeting moved',     'A meeting was moved.',    'both', 'client_visible', 'client_experience')
ON CONFLICT (slug) DO NOTHING;

CREATE OR REPLACE FUNCTION public.emit_booking_rail()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_kind text; v_title text; v_verb text; v_rep_id uuid;
BEGIN
  BEGIN
    IF NEW.contact_id IS NULL OR NEW.tenant_id IS NULL THEN
      RETURN NEW;
    END IF;
    IF TG_OP = 'INSERT' THEN
      IF NEW.status IS DISTINCT FROM 'cancelled' THEN
        v_kind := 'booking.created'; v_verb := 'Meeting booked';
      ELSE
        RETURN NEW;
      END IF;
    ELSIF TG_OP = 'UPDATE' THEN
      IF OLD.status IS DISTINCT FROM 'cancelled' AND NEW.status = 'cancelled' THEN
        v_kind := 'booking.cancelled'; v_verb := 'Meeting cancelled';
      ELSIF NEW.start_at IS DISTINCT FROM OLD.start_at AND NEW.status IS DISTINCT FROM 'cancelled' THEN
        v_kind := 'booking.rescheduled'; v_verb := 'Meeting moved';
      ELSE
        RETURN NEW;
      END IF;
    ELSE
      RETURN NEW;
    END IF;

    IF NEW.collective_group_id IS NOT NULL THEN
      SELECT min(b.id) INTO v_rep_id FROM public.internal_bookings b
       WHERE b.collective_group_id = NEW.collective_group_id;
      IF v_rep_id IS DISTINCT FROM NEW.id THEN RETURN NEW; END IF;
    END IF;

    v_title := v_verb || ': ' || COALESCE(NULLIF(btrim(NEW.title), ''), 'a meeting');

    PERFORM public.record_rail_event(
      p_contact_id => NEW.contact_id, p_event_kind => v_kind,
      p_surface => 'client_portal', p_actor_type => 'client', p_title => v_title,
      p_summary => NULL,
      p_payload => jsonb_build_object('booking_kind', NEW.booking_kind, 'start_at', NEW.start_at, 'status', NEW.status),
      p_ref_table => 'internal_bookings', p_ref_id => NEW.id,
      p_from_department => 'client_experience', p_to_department => 'owner_ops',
      p_occurred_at => NULL, p_narrow_to_owner => false, p_tenant_id => NEW.tenant_id
    );
    RETURN NEW;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'emit_booking_rail skipped for booking % (op %): %', NEW.id, TG_OP, SQLERRM;
    RETURN NEW;
  END;
END $$;
REVOKE ALL ON FUNCTION public.emit_booking_rail() FROM PUBLIC, anon;

DROP TRIGGER IF EXISTS trg_emit_booking_rail ON public.internal_bookings;
CREATE TRIGGER trg_emit_booking_rail
  AFTER INSERT OR UPDATE ON public.internal_bookings
  FOR EACH ROW EXECUTE FUNCTION public.emit_booking_rail();
