-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260708203607 (calendars_first_class)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260708203607 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.calendars (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id          uuid REFERENCES public.tenants(id) ON DELETE CASCADE,
  created_by         uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  slug               text NOT NULL UNIQUE,
  type               text NOT NULL DEFAULT 'personal',
  title              text,
  description        text,
  logo_url           text,
  accent             text,
  cover_url          text,
  duration_min       integer NOT NULL DEFAULT 30,
  buffer_before_min  integer NOT NULL DEFAULT 0,
  buffer_after_min   integer NOT NULL DEFAULT 0,
  min_notice_min     integer NOT NULL DEFAULT 60,
  timezone           text NOT NULL DEFAULT 'America/New_York',
  availability_json  jsonb,
  enabled            boolean NOT NULL DEFAULT false,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS calendars_tenant_idx ON public.calendars (tenant_id);
CREATE INDEX IF NOT EXISTS calendars_created_by_idx ON public.calendars (created_by);

CREATE TABLE IF NOT EXISTS public.calendar_hosts (
  calendar_id uuid NOT NULL REFERENCES public.calendars(id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  priority    integer NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (calendar_id, user_id)
);
CREATE INDEX IF NOT EXISTS calendar_hosts_user_idx ON public.calendar_hosts (user_id);

ALTER TABLE public.internal_bookings
  ADD COLUMN IF NOT EXISTS calendar_id uuid REFERENCES public.calendars(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS internal_bookings_calendar_idx ON public.internal_bookings (calendar_id);

CREATE OR REPLACE FUNCTION public.is_calendar_host(_cal uuid)
RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE SET search_path TO 'public'
AS $$ SELECT EXISTS (SELECT 1 FROM public.calendar_hosts WHERE calendar_id = _cal AND user_id = auth.uid()); $$;

CREATE OR REPLACE FUNCTION public.can_manage_calendar(_cal uuid)
RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE SET search_path TO 'public'
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.calendars c
     WHERE c.id = _cal
       AND (c.created_by = auth.uid()
            OR public.is_platform_admin()
            OR (c.tenant_id IS NOT NULL AND public.is_tenant_admin(c.tenant_id)))
  );
$$;

ALTER TABLE public.calendars ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_hosts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "manage calendars" ON public.calendars;
CREATE POLICY "manage calendars" ON public.calendars
  FOR ALL TO authenticated
  USING (
    created_by = auth.uid()
    OR public.is_platform_admin()
    OR (tenant_id IS NOT NULL AND public.is_tenant_admin(tenant_id))
  )
  WITH CHECK (
    public.is_platform_admin()
    OR (tenant_id IS NOT NULL AND public.is_tenant_admin(tenant_id))
    OR (created_by = auth.uid() AND tenant_id IS NOT NULL AND public.is_tenant_member(tenant_id))
  );

DROP POLICY IF EXISTS "hosts read calendars" ON public.calendars;
CREATE POLICY "hosts read calendars" ON public.calendars
  FOR SELECT TO authenticated
  USING (public.is_calendar_host(id));

DROP POLICY IF EXISTS "manage calendar hosts" ON public.calendar_hosts;
CREATE POLICY "manage calendar hosts" ON public.calendar_hosts
  FOR ALL TO authenticated
  USING (user_id = auth.uid() OR public.can_manage_calendar(calendar_id))
  WITH CHECK (public.can_manage_calendar(calendar_id));

GRANT EXECUTE ON FUNCTION public.is_calendar_host(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.can_manage_calendar(uuid) TO authenticated;
