-- =============================================================================
-- RECONSTRUCTED from prod ledger — version 20260713023715 (agency_switch_rpcs)
-- =============================================================================
-- This file is the SQL recorded in
-- supabase_migrations.schema_migrations.statements for version 20260713023715 on prod
-- (ref xygzykjyynhzqytbqnzu) — i.e. the statements that ACTUALLY RAN on prod when
-- this migration was applied via the owner's dashboard/MCP.
--
-- It is NOT a recovered original-authored migration file, and NO `supabase db
-- pull` / schema introspection was run to produce it. It is reconstructed
-- verbatim from the recorded ledger statements for the SOLE purpose of restoring
-- repo<->prod migration-history parity, so `supabase db push` no longer trips its
-- "remote migration versions not found in local" history guard.
--
-- Because prod already records this version, `db push` treats it as
-- already-applied and does NOT re-run it; it re-executes only on a fresh-DB
-- reset (idempotency is this file's own responsibility, per the recorded SQL).
--
-- Generated by scripts/reconcile-missing-migrations.mjs (task #421). Do not edit
-- to "fix" behavior — this is a faithful transcript of the applied prod SQL.
-- =============================================================================

CREATE OR REPLACE FUNCTION public.agency_enter_subaccount(_child uuid)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.agency_can_manage_child(_child, auth.uid()) THEN
    RAISE EXCEPTION 'agency_scope_forbidden' USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.tenant_members (tenant_id, user_id, role, status, joined_at)
  VALUES (_child, auth.uid(), 'admin', 'active', now())
  ON CONFLICT (tenant_id, user_id) DO UPDATE
    SET status = 'active',
        role   = CASE WHEN tenant_members.role = 'owner' THEN 'owner' ELSE 'admin' END;

  UPDATE public.profiles SET active_tenant_id = _child WHERE user_id = auth.uid();

  RETURN jsonb_build_object(
    'active_tenant_id', _child,
    'name',             (SELECT name FROM public.tenants WHERE id = _child)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.agency_exit_subaccount()
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  _agency uuid;
BEGIN
  SELECT t.id INTO _agency
  FROM public.tenant_members m
  JOIN public.tenants t ON t.id = m.tenant_id
  WHERE m.user_id = auth.uid()
    AND m.status = 'active'
    AND m.role IN ('owner', 'admin')
    AND t.account_type IN ('agency', 'enterprise')
  ORDER BY m.joined_at ASC NULLS LAST, t.created_at ASC
  LIMIT 1;

  IF _agency IS NULL THEN
    RAISE EXCEPTION 'not_an_agency_manager' USING ERRCODE = '42501';
  END IF;

  UPDATE public.profiles SET active_tenant_id = _agency WHERE user_id = auth.uid();
  RETURN jsonb_build_object('active_tenant_id', _agency);
END;
$$;

CREATE OR REPLACE FUNCTION public.agency_switch_context()
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  _agency_id   uuid;
  _agency_name text;
  _active      uuid;
BEGIN
  SELECT t.id, t.name INTO _agency_id, _agency_name
  FROM public.tenant_members m
  JOIN public.tenants t ON t.id = m.tenant_id
  WHERE m.user_id = auth.uid()
    AND m.status = 'active'
    AND m.role IN ('owner', 'admin')
    AND t.account_type IN ('agency', 'enterprise')
  ORDER BY m.joined_at ASC NULLS LAST, t.created_at ASC
  LIMIT 1;

  SELECT active_tenant_id INTO _active FROM public.profiles WHERE user_id = auth.uid();

  RETURN jsonb_build_object(
    'is_agency_manager', _agency_id IS NOT NULL,
    'agency_id',         _agency_id,
    'agency_name',       _agency_name,
    'active_tenant_id',  _active
  );
END;
$$;

REVOKE ALL ON FUNCTION public.agency_enter_subaccount(uuid) FROM public, anon;
REVOKE ALL ON FUNCTION public.agency_exit_subaccount()      FROM public, anon;
REVOKE ALL ON FUNCTION public.agency_switch_context()       FROM public, anon;
GRANT EXECUTE ON FUNCTION public.agency_enter_subaccount(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.agency_exit_subaccount()      TO authenticated;
GRANT EXECUTE ON FUNCTION public.agency_switch_context()       TO authenticated;
